/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by binval.awk with options header

#ifndef _DC3tbinval_HEADER_
#define _DC3tbinval_HEADER_

char *	DC3BinaryValueDescription_PregnancyStatus(Uint16 value);
char *	DC3BinaryValueDescription_RegionSpatialFormat(Uint16 value);
char *	DC3BinaryValueDescription_RegionDataType(Uint16 value);
char *	DC3BinaryBitMapDescription_RegionFlags(Uint16 value);
char *	DC3BinaryValueDescription_PixelComponentOrganization(Uint16 value);
char *	DC3BinaryValueDescription_PixelComponentPhysicalUnits(Uint16 value);
char *	DC3BinaryValueDescription_PixelComponentDataType(Uint16 value);
char *	DC3BinaryBitMapDescription_USImageType4(Uint16 value);
char *	DC3BinaryValueDescription_PixelRepresentation(Uint16 value);
char *	DC3BinaryValueDescription_PixelRepresentationUnsigned(Uint16 value);
char *	DC3BinaryValueDescription_PlanarConfiguration(Uint16 value);
char *	DC3BinaryValueDescription_SamplesPerPixelIsOne(Uint16 value);
char *	DC3BinaryValueDescription_SamplesPerPixelIsThree(Uint16 value);
char *	DC3BinaryValueDescription_PlanarConfigurationIsFrameInterleave(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre16(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre8(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre12Or16(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre11Or15(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre8Or16(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre7Or15(Uint16 value);
char *	DC3BinaryValueDescription_BitsAre7(Uint16 value);
char *	DC3BinaryValueDescription_CurveDataValueRepresentation(Uint16 value);
char *	DC3BinaryValueDescription_CurveDataDescriptor(Uint16 value);
char *	DC3BinaryValueDescription_AudioType(Uint16 value);
char *	DC3BinaryValueDescription_AudioSampleFormat(Uint16 value);
char *	DC3BinaryValueDescription_NumberOfChannels(Uint16 value);

#endif /* _DC3tbinval_HEADER_ */





/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
