/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by condition.awk with options header

#ifndef _DC3tcond_HEADER_
#define _DC3tcond_HEADER_

int DC3Condition_Never(DC3ListofAttributes *list);
int DC3Condition_Always(DC3ListofAttributes *list);
int	DC3Condition_CRImageInstance(DC3ListofAttributes *list);
int	DC3Condition_CTImageInstance(DC3ListofAttributes *list);
int	DC3Condition_MRImageInstance(DC3ListofAttributes *list);
int	DC3Condition_NMImageInstance(DC3ListofAttributes *list);
int	DC3Condition_NMOverlayInstance(DC3ListofAttributes *list);
int	DC3Condition_NMCurveInstance(DC3ListofAttributes *list);
int	DC3Condition_USImageInstance(DC3ListofAttributes *list);
int	DC3Condition_USCurveInstance(DC3ListofAttributes *list);
int	DC3Condition_USMultiFrameImageInstance(DC3ListofAttributes *list);
int	DC3Condition_USMultiFrameCurveInstance(DC3ListofAttributes *list);
int	DC3Condition_SCImageInstance(DC3ListofAttributes *list);
int	DC3Condition_StandaloneOverlayInstance(DC3ListofAttributes *list);
int	DC3Condition_StandaloneCurveInstance(DC3ListofAttributes *list);
int	DC3Condition_StandaloneModalityLUTInstance(DC3ListofAttributes *list);
int	DC3Condition_StandaloneVOILUTInstance(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleContrastBolus(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleCine(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleMultiFrame(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleNMMultiGatedAcquisitionImage(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleNMSPECTAcquisitionImage(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleUSFrameOfReference(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleOverlayPlane(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleCurve(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleAudio(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleModalityLUT(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleVOILUT(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleFrameOfReference(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleImagePlane(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleMultiFrameOverlay(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleUSRegionCalibration(DC3ListofAttributes *list);
int	DC3Condition_NeedModuleGeneralEquipment(DC3ListofAttributes *list);
int	DC3Condition_SamplesPerPixelGreaterThanOne(DC3ListofAttributes *list);
int	DC3Condition_PhotometricInterpretationNeedsPalette(DC3ListofAttributes *list);
int	DC3Condition_ModalityIsCTOrMR(DC3ListofAttributes *list);
int	DC3Condition_ImagePlaneModuleNotRequired(DC3ListofAttributes *list);
int	DC3Condition_MRIsNotEchoPlanarNotSegmentedKSpace(DC3ListofAttributes *list);
int	DC3Condition_MRIsInversionRecovery(DC3ListofAttributes *list);
int	DC3Condition_MRIsCardiacOrPulseGated(DC3ListofAttributes *list);
int	DC3Condition_NMIsWholeBody(DC3ListofAttributes *list);
int	DC3Condition_CurveDataDescriptorPresent(DC3ListofAttributes *list);
int	DC3Condition_ModalityLUTSequenceNotPresent(DC3ListofAttributes *list);
int	DC3Condition_RescaleInterceptPresent(DC3ListofAttributes *list);
int	DC3Condition_WindowCenterPresent(DC3ListofAttributes *list);

#endif /* _DC3tcond_HEADER_ */





/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
