/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by condition.awk with options method

#include "tcondt.h"
#include "tcond.h"

int DC3Condition_Never(DC3ListofAttributes *list)  { (void)list; return 0; }
int DC3Condition_Always(DC3ListofAttributes *list) { (void)list; return 1; }
int
DC3Condition_CRImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"CR");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3ComputedRadiographyImageStorageSOPClass);

	return condition;
}

int
DC3Condition_CTImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"CT");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3CTImageStorageSOPClass);

	return condition;
}

int
DC3Condition_MRImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"MR");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3MRImageStorageSOPClass);

	return condition;
}

int
DC3Condition_NMImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"NM");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3NuclearMedicineImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(ImageNumber));

	return condition;
}

int
DC3Condition_NMOverlayInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"NM");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3NuclearMedicineImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(OverlayNumber));

	return condition;
}

int
DC3Condition_NMCurveInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"NM");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3NuclearMedicineImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(CurveNumber));

	return condition;
}

int
DC3Condition_USImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"US");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3UltrasoundImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(ImageNumber));

	return condition;
}

int
DC3Condition_USCurveInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"US");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3UltrasoundImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(CurveNumber));

	return condition;
}

int
DC3Condition_USMultiFrameImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3UltrasoundMultiframeImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(ImageNumber));

	return condition;
}

int
DC3Condition_USMultiFrameCurveInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3UltrasoundMultiframeImageStorageSOPClass);
	condition&=ElementPresent(list,DC3TagFromName(CurveNumber));

	return condition;
}

int
DC3Condition_SCImageInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"SC");
	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3SecondaryCaptureImageStorageSOPClass);

	return condition;
}

int
DC3Condition_StandaloneOverlayInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3StandaloneOverlayStorageSOPClass);

	return condition;
}

int
DC3Condition_StandaloneCurveInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3StandaloneCurveStorageSOPClass);

	return condition;
}

int
DC3Condition_StandaloneModalityLUTInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3StandaloneModalityLUTStorageSOPClass);

	return condition;
}

int
DC3Condition_StandaloneVOILUTInstance(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(SOPClassUID),DC3StandaloneVOILUTStorageSOPClass);

	return condition;
}

int
DC3Condition_NeedModuleContrastBolus(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(ContrastBolusAgent));

	return condition;
}

int
DC3Condition_NeedModuleCine(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(FrameTime));
	condition|=ElementPresent(list,DC3TagFromName(FrameTimeVector));

	return condition;
}

int
DC3Condition_NeedModuleMultiFrame(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(FrameIncrementPointer));
	condition|=ElementPresent(list,DC3TagFromName(NumberOfFrames));

	return condition;
}

int
DC3Condition_NeedModuleNMMultiGatedAcquisitionImage(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(FrameTime));

	return condition;
}

int
DC3Condition_NeedModuleNMSPECTAcquisitionImage(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(AngularStep));

	return condition;
}

int
DC3Condition_NeedModuleUSFrameOfReference(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(RegionLocationMinX0));
	condition|=ElementPresent(list,DC3TagFromName(RegionLocationMinY0));
	condition|=ElementPresent(list,DC3TagFromName(RegionLocationMaxX1));
	condition|=ElementPresent(list,DC3TagFromName(RegionLocationMaxY1));
	condition|=ElementPresent(list,DC3TagFromName(PhysicalUnitsXDirection));
	condition|=ElementPresent(list,DC3TagFromName(PhysicalUnitsYDirection));
	condition|=ElementPresent(list,DC3TagFromName(PhysicalDeltaX));
	condition|=ElementPresent(list,DC3TagFromName(PhysicalDeltaY));

	return condition;
}

int
DC3Condition_NeedModuleOverlayPlane(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=GroupPresentMasked(list,DC3TagFromName(OverlayRows),0xff00);

	return condition;
}

int
DC3Condition_NeedModuleCurve(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresentMasked(list,DC3TagFromName(CurveDimensions),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(NumberOfPoints),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(TypeOfData),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(DataValueRepresentation),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(CurveData),0xff00);

	return condition;
}

int
DC3Condition_NeedModuleAudio(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresentMasked(list,DC3TagFromName(AudioType),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(AudioSampleFormat),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(NumberOfChannels),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(NumberOfSamples),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(SampleRate),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(TotalTime),0xff00);
	condition|=ElementPresentMasked(list,DC3TagFromName(AudioSampleData),0xff00);

	return condition;
}

int
DC3Condition_NeedModuleModalityLUT(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(RescaleIntercept));

	return condition;
}

int
DC3Condition_NeedModuleVOILUT(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(WindowCenter));

	return condition;
}

int
DC3Condition_NeedModuleFrameOfReference(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(FrameOfReferenceUID));
	condition|=ElementPresent(list,DC3TagFromName(PositionReferenceIndicator));

	return condition;
}

int
DC3Condition_NeedModuleImagePlane(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(PixelSpacing));
	condition|=ElementPresent(list,DC3TagFromName(ImageOrientationPatient));
	condition|=ElementPresent(list,DC3TagFromName(ImagePositionPatient));

	return condition;
}

int
DC3Condition_NeedModuleMultiFrameOverlay(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(OverlayNumberOfFrames));

	return condition;
}

int
DC3Condition_NeedModuleUSRegionCalibration(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;


	return condition;
}

int
DC3Condition_NeedModuleGeneralEquipment(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(Manufacturer));

	return condition;
}

int
DC3Condition_SamplesPerPixelGreaterThanOne(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	{
		Xint value;
		if (BinaryValueGet(list,DC3TagFromName(SamplesPerPixel),value))
			condition|=(value > 1);
	}

	return condition;
}

int
DC3Condition_PhotometricInterpretationNeedsPalette(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(PhotometricInterpretation),"PALETTE COLOR");
	condition|=StringValueMatch(list,DC3TagFromName(PhotometricInterpretation),"ARGB");

	return condition;
}

int
DC3Condition_ModalityIsCTOrMR(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"CT");
	condition|=StringValueMatch(list,DC3TagFromName(Modality),"MR");

	return condition;
}

int
DC3Condition_ImagePlaneModuleNotRequired(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(Modality),"CR");
	condition|=StringValueMatch(list,DC3TagFromName(Modality),"NM");
	condition|=StringValueMatch(list,DC3TagFromName(Modality),"US");
	condition|=StringValueMatch(list,DC3TagFromName(Modality),"SC");

	return condition;
}

int
DC3Condition_MRIsNotEchoPlanarNotSegmentedKSpace(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(ScanningSequence),"SE");
	condition|=StringValueMatch(list,DC3TagFromName(ScanningSequence),"IR");
	condition|=StringValueMatch(list,DC3TagFromName(ScanningSequence),"GR");
	condition|=StringValueMatch(list,DC3TagFromName(ScanningSequence),"RM");

	return condition;
}

int
DC3Condition_MRIsInversionRecovery(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(ScanningSequence),"IR");

	return condition;
}

int
DC3Condition_MRIsCardiacOrPulseGated(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(ScanOptions),"CG");
	condition|=StringValueMatch(list,DC3TagFromName(ScanOptions),"PPG");

	return condition;
}

int
DC3Condition_NMIsWholeBody(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=StringValueMatch(list,DC3TagFromName(NuclearMedicineSeriesType),"WHOLE BODY");

	return condition;
}

int
DC3Condition_CurveDataDescriptorPresent(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresentMasked(list,DC3TagFromName(CurveDataDescriptor),0xff00);

	return condition;
}

int
DC3Condition_ModalityLUTSequenceNotPresent(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=!ElementPresent(list,DC3TagFromName(ModalityLUTSequence));

	return condition;
}

int
DC3Condition_RescaleInterceptPresent(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(RescaleIntercept));

	return condition;
}

int
DC3Condition_WindowCenterPresent(DC3ListofAttributes *list)
{
	int condition=0;	// default is false
	(void)list;

	condition|=ElementPresent(list,DC3TagFromName(WindowCenter));

	return condition;
}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
