/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by iodcmp.awk with options select

#include "tlist.h"
#include "tmodulet.h"
#include "tmodule.h"
#include "tiodcmpt.h"
#include "tiodcmp.h"
#include "tiodcmps.h"
#include "tcond.h"

DC3CompositeIOD *
DC3SelectCompositeIOD(DC3ListofAttributes *list)
{
	DC3CompositeIOD *iod = 0;

	if (DC3Condition_CRImageInstance(list)) {
		iod = new DC3CompositeIOD_CRImage(list);
	}
	else if (DC3Condition_CTImageInstance(list)) {
		iod = new DC3CompositeIOD_CTImage(list);
	}
	else if (DC3Condition_MRImageInstance(list)) {
		iod = new DC3CompositeIOD_MRImage(list);
	}
	else if (DC3Condition_NMImageInstance(list)) {
		iod = new DC3CompositeIOD_NMImage(list);
	}
	else if (DC3Condition_NMOverlayInstance(list)) {
		iod = new DC3CompositeIOD_NMOverlay(list);
	}
	else if (DC3Condition_NMCurveInstance(list)) {
		iod = new DC3CompositeIOD_NMCurve(list);
	}
	else if (DC3Condition_USImageInstance(list)) {
		iod = new DC3CompositeIOD_USImage(list);
	}
	else if (DC3Condition_USCurveInstance(list)) {
		iod = new DC3CompositeIOD_USCurve(list);
	}
	else if (DC3Condition_USMultiFrameImageInstance(list)) {
		iod = new DC3CompositeIOD_USMultiFrameImage(list);
	}
	else if (DC3Condition_USMultiFrameCurveInstance(list)) {
		iod = new DC3CompositeIOD_USMultiFrameCurve(list);
	}
	else if (DC3Condition_SCImageInstance(list)) {
		iod = new DC3CompositeIOD_SCImage(list);
	}
	else if (DC3Condition_StandaloneOverlayInstance(list)) {
		iod = new DC3CompositeIOD_StandaloneOverlay(list);
	}
	else if (DC3Condition_StandaloneCurveInstance(list)) {
		iod = new DC3CompositeIOD_StandaloneCurve(list);
	}
	else if (DC3Condition_StandaloneModalityLUTInstance(list)) {
		iod = new DC3CompositeIOD_StandaloneModalityLUT(list);
	}
	else if (DC3Condition_StandaloneVOILUTInstance(list)) {
		iod = new DC3CompositeIOD_StandaloneVOILUT(list);
	}

	return iod;
}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
