/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by iodcmp.awk with options put

#include <iostream.h>

#include "tlist.h"
#include "tmodulet.h"
#include "tmodule.h"
#include "tiodcmpt.h"
#include "tiodcmp.h"

void
DC3CompositeIOD_CRImage::Put(ostream& stream)
{
	stream << "Composite IOD <CRImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (CRSeries)
		CRSeries->Put(stream);
	else
		stream << "\tModule <CRSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (ContrastBolus)
		ContrastBolus->Put(stream);
	else
		stream << "\tModule <ContrastBolus> not present\n";

	if (CRImage)
		CRImage->Put(stream);
	else
		stream << "\tModule <CRImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (ModalityLUT)
		ModalityLUT->Put(stream);
	else
		stream << "\tModule <ModalityLUT> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_CTImage::Put(ostream& stream)
{
	stream << "Composite IOD <CTImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePlane)
		ImagePlane->Put(stream);
	else
		stream << "\tModule <ImagePlane> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (ContrastBolus)
		ContrastBolus->Put(stream);
	else
		stream << "\tModule <ContrastBolus> not present\n";

	if (CTImage)
		CTImage->Put(stream);
	else
		stream << "\tModule <CTImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_MRImage::Put(ostream& stream)
{
	stream << "Composite IOD <MRImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePlane)
		ImagePlane->Put(stream);
	else
		stream << "\tModule <ImagePlane> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (ContrastBolus)
		ContrastBolus->Put(stream);
	else
		stream << "\tModule <ContrastBolus> not present\n";

	if (MRImage)
		MRImage->Put(stream);
	else
		stream << "\tModule <MRImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_NMImage::Put(ostream& stream)
{
	stream << "Composite IOD <NMImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (NMSeries)
		NMSeries->Put(stream);
	else
		stream << "\tModule <NMSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (NMEquipment)
		NMEquipment->Put(stream);
	else
		stream << "\tModule <NMEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePlane)
		ImagePlane->Put(stream);
	else
		stream << "\tModule <ImagePlane> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (Cine)
		Cine->Put(stream);
	else
		stream << "\tModule <Cine> not present\n";

	if (MultiFrame)
		MultiFrame->Put(stream);
	else
		stream << "\tModule <MultiFrame> not present\n";

	if (NMImage)
		NMImage->Put(stream);
	else
		stream << "\tModule <NMImage> not present\n";

	if (NMSPECTAcquisitionImage)
		NMSPECTAcquisitionImage->Put(stream);
	else
		stream << "\tModule <NMSPECTAcquisitionImage> not present\n";

	if (NMMultiGatedAcquisitionImage)
		NMMultiGatedAcquisitionImage->Put(stream);
	else
		stream << "\tModule <NMMultiGatedAcquisitionImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (MultiFrameOverlay)
		MultiFrameOverlay->Put(stream);
	else
		stream << "\tModule <MultiFrameOverlay> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_NMOverlay::Put(ostream& stream)
{
	stream << "Composite IOD <NMOverlay>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (NMSeries)
		NMSeries->Put(stream);
	else
		stream << "\tModule <NMSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (NMEquipment)
		NMEquipment->Put(stream);
	else
		stream << "\tModule <NMEquipment> not present\n";

	if (OverlayIdentification)
		OverlayIdentification->Put(stream);
	else
		stream << "\tModule <OverlayIdentification> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (MultiFrameOverlay)
		MultiFrameOverlay->Put(stream);
	else
		stream << "\tModule <MultiFrameOverlay> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_NMCurve::Put(ostream& stream)
{
	stream << "Composite IOD <NMCurve>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (NMSeries)
		NMSeries->Put(stream);
	else
		stream << "\tModule <NMSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (NMEquipment)
		NMEquipment->Put(stream);
	else
		stream << "\tModule <NMEquipment> not present\n";

	if (CurveIdentification)
		CurveIdentification->Put(stream);
	else
		stream << "\tModule <CurveIdentification> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_USImage::Put(ostream& stream)
{
	stream << "Composite IOD <USImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (USFrameOfReference)
		USFrameOfReference->Put(stream);
	else
		stream << "\tModule <USFrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (ContrastBolus)
		ContrastBolus->Put(stream);
	else
		stream << "\tModule <ContrastBolus> not present\n";

	if (USRegionCalibration)
		USRegionCalibration->Put(stream);
	else
		stream << "\tModule <USRegionCalibration> not present\n";

	if (USImage)
		USImage->Put(stream);
	else
		stream << "\tModule <USImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_USCurve::Put(ostream& stream)
{
	stream << "Composite IOD <USCurve>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (USFrameOfReference)
		USFrameOfReference->Put(stream);
	else
		stream << "\tModule <USFrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (CurveIdentification)
		CurveIdentification->Put(stream);
	else
		stream << "\tModule <CurveIdentification> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (Audio)
		Audio->Put(stream);
	else
		stream << "\tModule <Audio> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_USMultiFrameImage::Put(ostream& stream)
{
	stream << "Composite IOD <USMultiFrameImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (USFrameOfReference)
		USFrameOfReference->Put(stream);
	else
		stream << "\tModule <USFrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (ContrastBolus)
		ContrastBolus->Put(stream);
	else
		stream << "\tModule <ContrastBolus> not present\n";

	if (Cine)
		Cine->Put(stream);
	else
		stream << "\tModule <Cine> not present\n";

	if (MultiFrame)
		MultiFrame->Put(stream);
	else
		stream << "\tModule <MultiFrame> not present\n";

	if (USRegionCalibration)
		USRegionCalibration->Put(stream);
	else
		stream << "\tModule <USRegionCalibration> not present\n";

	if (USImage)
		USImage->Put(stream);
	else
		stream << "\tModule <USImage> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_USMultiFrameCurve::Put(ostream& stream)
{
	stream << "Composite IOD <USMultiFrameCurve>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (FrameOfReference)
		FrameOfReference->Put(stream);
	else
		stream << "\tModule <FrameOfReference> not present\n";

	if (USFrameOfReference)
		USFrameOfReference->Put(stream);
	else
		stream << "\tModule <USFrameOfReference> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (CurveIdentification)
		CurveIdentification->Put(stream);
	else
		stream << "\tModule <CurveIdentification> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (Audio)
		Audio->Put(stream);
	else
		stream << "\tModule <Audio> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_SCImage::Put(ostream& stream)
{
	stream << "Composite IOD <SCImage>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (SCImageEquipment)
		SCImageEquipment->Put(stream);
	else
		stream << "\tModule <SCImageEquipment> not present\n";

	if (GeneralImage)
		GeneralImage->Put(stream);
	else
		stream << "\tModule <GeneralImage> not present\n";

	if (ImagePixel)
		ImagePixel->Put(stream);
	else
		stream << "\tModule <ImagePixel> not present\n";

	if (SCImage)
		SCImage->Put(stream);
	else
		stream << "\tModule <SCImage> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (ModalityLUT)
		ModalityLUT->Put(stream);
	else
		stream << "\tModule <ModalityLUT> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_StandaloneOverlay::Put(ostream& stream)
{
	stream << "Composite IOD <StandaloneOverlay>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (OverlayIdentification)
		OverlayIdentification->Put(stream);
	else
		stream << "\tModule <OverlayIdentification> not present\n";

	if (OverlayPlane)
		OverlayPlane->Put(stream);
	else
		stream << "\tModule <OverlayPlane> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_StandaloneCurve::Put(ostream& stream)
{
	stream << "Composite IOD <StandaloneCurve>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (CurveIdentification)
		CurveIdentification->Put(stream);
	else
		stream << "\tModule <CurveIdentification> not present\n";

	if (Curve)
		Curve->Put(stream);
	else
		stream << "\tModule <Curve> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_BasicStudyDescriptor::Put(ostream& stream)
{
	stream << "Composite IOD <BasicStudyDescriptor>\n";

	if (PatientSummary)
		PatientSummary->Put(stream);
	else
		stream << "\tModule <PatientSummary> not present\n";

	if (StudyContent)
		StudyContent->Put(stream);
	else
		stream << "\tModule <StudyContent> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_StandaloneModalityLUT::Put(ostream& stream)
{
	stream << "Composite IOD <StandaloneModalityLUT>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (ModalityLUT)
		ModalityLUT->Put(stream);
	else
		stream << "\tModule <ModalityLUT> not present\n";

	if (LUTIdentification)
		LUTIdentification->Put(stream);
	else
		stream << "\tModule <LUTIdentification> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}

void
DC3CompositeIOD_StandaloneVOILUT::Put(ostream& stream)
{
	stream << "Composite IOD <StandaloneVOILUT>\n";

	if (Patient)
		Patient->Put(stream);
	else
		stream << "\tModule <Patient> not present\n";

	if (GeneralStudy)
		GeneralStudy->Put(stream);
	else
		stream << "\tModule <GeneralStudy> not present\n";

	if (PatientStudy)
		PatientStudy->Put(stream);
	else
		stream << "\tModule <PatientStudy> not present\n";

	if (GeneralSeries)
		GeneralSeries->Put(stream);
	else
		stream << "\tModule <GeneralSeries> not present\n";

	if (GeneralEquipment)
		GeneralEquipment->Put(stream);
	else
		stream << "\tModule <GeneralEquipment> not present\n";

	if (VOILUT)
		VOILUT->Put(stream);
	else
		stream << "\tModule <VOILUT> not present\n";

	if (LUTIdentification)
		LUTIdentification->Put(stream);
	else
		stream << "\tModule <LUTIdentification> not present\n";

	if (SOPCommon)
		SOPCommon->Put(stream);
	else
		stream << "\tModule <SOPCommon> not present\n";

}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
