/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by iodcmp.awk with options method

#include "tlist.h"
#include "tmodulet.h"
#include "tmodule.h"
#include "tiodcmpt.h"
#include "tiodcmp.h"
#include "tcond.h"

char *
DC3CompositeIOD_CRImage::Identify(void)
{
	return "CRImage";
}

DC3CompositeIOD_CRImage::DC3CompositeIOD_CRImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	CRSeries = new DC3Module_CRSeries(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleContrastBolus(list))
		ContrastBolus = new DC3Module_ContrastBolus(list);
	CRImage = new DC3Module_CRImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleCurve(list))
		Curve = new DC3Module_Curve(list);
	if (DC3Condition_NeedModuleModalityLUT(list))
		ModalityLUT = new DC3Module_ModalityLUT(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_CTImage::Identify(void)
{
	return "CTImage";
}

DC3CompositeIOD_CTImage::DC3CompositeIOD_CTImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	FrameOfReference = new DC3Module_FrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePlane = new DC3Module_ImagePlane(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleContrastBolus(list))
		ContrastBolus = new DC3Module_ContrastBolus(list);
	CTImage = new DC3Module_CTImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_MRImage::Identify(void)
{
	return "MRImage";
}

DC3CompositeIOD_MRImage::DC3CompositeIOD_MRImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	FrameOfReference = new DC3Module_FrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePlane = new DC3Module_ImagePlane(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleContrastBolus(list))
		ContrastBolus = new DC3Module_ContrastBolus(list);
	MRImage = new DC3Module_MRImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_NMImage::Identify(void)
{
	return "NMImage";
}

DC3CompositeIOD_NMImage::DC3CompositeIOD_NMImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	NMSeries = new DC3Module_NMSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	NMEquipment = new DC3Module_NMEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	if (DC3Condition_NeedModuleImagePlane(list))
		ImagePlane = new DC3Module_ImagePlane(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleCine(list))
		Cine = new DC3Module_Cine(list);
	if (DC3Condition_NeedModuleMultiFrame(list))
		MultiFrame = new DC3Module_MultiFrame(list);
	NMImage = new DC3Module_NMImage(list);
	if (DC3Condition_NeedModuleNMSPECTAcquisitionImage(list))
		NMSPECTAcquisitionImage = new DC3Module_NMSPECTAcquisitionImage(list);
	if (DC3Condition_NeedModuleNMMultiGatedAcquisitionImage(list))
		NMMultiGatedAcquisitionImage = new DC3Module_NMMultiGatedAcquisitionImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleMultiFrameOverlay(list))
		MultiFrameOverlay = new DC3Module_MultiFrameOverlay(list);
	if (DC3Condition_NeedModuleCurve(list))
		Curve = new DC3Module_Curve(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_NMOverlay::Identify(void)
{
	return "NMOverlay";
}

DC3CompositeIOD_NMOverlay::DC3CompositeIOD_NMOverlay(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	NMSeries = new DC3Module_NMSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	NMEquipment = new DC3Module_NMEquipment(list);
	OverlayIdentification = new DC3Module_OverlayIdentification(list);
	OverlayPlane = new DC3Module_OverlayPlane(list);
	MultiFrameOverlay = new DC3Module_MultiFrameOverlay(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_NMCurve::Identify(void)
{
	return "NMCurve";
}

DC3CompositeIOD_NMCurve::DC3CompositeIOD_NMCurve(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	NMSeries = new DC3Module_NMSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	NMEquipment = new DC3Module_NMEquipment(list);
	CurveIdentification = new DC3Module_CurveIdentification(list);
	Curve = new DC3Module_Curve(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_USImage::Identify(void)
{
	return "USImage";
}

DC3CompositeIOD_USImage::DC3CompositeIOD_USImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	if (DC3Condition_NeedModuleUSFrameOfReference(list))
		USFrameOfReference = new DC3Module_USFrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleContrastBolus(list))
		ContrastBolus = new DC3Module_ContrastBolus(list);
	if (DC3Condition_NeedModuleUSRegionCalibration(list))
		USRegionCalibration = new DC3Module_USRegionCalibration(list);
	USImage = new DC3Module_USImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_USCurve::Identify(void)
{
	return "USCurve";
}

DC3CompositeIOD_USCurve::DC3CompositeIOD_USCurve(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	if (DC3Condition_NeedModuleUSFrameOfReference(list))
		USFrameOfReference = new DC3Module_USFrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	CurveIdentification = new DC3Module_CurveIdentification(list);
	Curve = new DC3Module_Curve(list);
	if (DC3Condition_NeedModuleAudio(list))
		Audio = new DC3Module_Audio(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_USMultiFrameImage::Identify(void)
{
	return "USMultiFrameImage";
}

DC3CompositeIOD_USMultiFrameImage::DC3CompositeIOD_USMultiFrameImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	if (DC3Condition_NeedModuleUSFrameOfReference(list))
		USFrameOfReference = new DC3Module_USFrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	if (DC3Condition_NeedModuleContrastBolus(list))
		ContrastBolus = new DC3Module_ContrastBolus(list);
	if (DC3Condition_NeedModuleCine(list))
		Cine = new DC3Module_Cine(list);
	MultiFrame = new DC3Module_MultiFrame(list);
	if (DC3Condition_NeedModuleUSRegionCalibration(list))
		USRegionCalibration = new DC3Module_USRegionCalibration(list);
	USImage = new DC3Module_USImage(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_USMultiFrameCurve::Identify(void)
{
	return "USMultiFrameCurve";
}

DC3CompositeIOD_USMultiFrameCurve::DC3CompositeIOD_USMultiFrameCurve(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	if (DC3Condition_NeedModuleFrameOfReference(list))
		FrameOfReference = new DC3Module_FrameOfReference(list);
	if (DC3Condition_NeedModuleUSFrameOfReference(list))
		USFrameOfReference = new DC3Module_USFrameOfReference(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	CurveIdentification = new DC3Module_CurveIdentification(list);
	Curve = new DC3Module_Curve(list);
	if (DC3Condition_NeedModuleAudio(list))
		Audio = new DC3Module_Audio(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_SCImage::Identify(void)
{
	return "SCImage";
}

DC3CompositeIOD_SCImage::DC3CompositeIOD_SCImage(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	if (DC3Condition_NeedModuleGeneralEquipment(list))
		GeneralEquipment = new DC3Module_GeneralEquipment(list);
	SCImageEquipment = new DC3Module_SCImageEquipment(list);
	GeneralImage = new DC3Module_GeneralImage(list);
	ImagePixel = new DC3Module_ImagePixel(list);
	SCImage = new DC3Module_SCImage(list);
	if (DC3Condition_NeedModuleOverlayPlane(list))
		OverlayPlane = new DC3Module_OverlayPlane(list);
	if (DC3Condition_NeedModuleModalityLUT(list))
		ModalityLUT = new DC3Module_ModalityLUT(list);
	if (DC3Condition_NeedModuleVOILUT(list))
		VOILUT = new DC3Module_VOILUT(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_StandaloneOverlay::Identify(void)
{
	return "StandaloneOverlay";
}

DC3CompositeIOD_StandaloneOverlay::DC3CompositeIOD_StandaloneOverlay(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	OverlayIdentification = new DC3Module_OverlayIdentification(list);
	OverlayPlane = new DC3Module_OverlayPlane(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_StandaloneCurve::Identify(void)
{
	return "StandaloneCurve";
}

DC3CompositeIOD_StandaloneCurve::DC3CompositeIOD_StandaloneCurve(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	CurveIdentification = new DC3Module_CurveIdentification(list);
	Curve = new DC3Module_Curve(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_BasicStudyDescriptor::Identify(void)
{
	return "BasicStudyDescriptor";
}

DC3CompositeIOD_BasicStudyDescriptor::DC3CompositeIOD_BasicStudyDescriptor(DC3ListofAttributes *list)
{
	PatientSummary = new DC3Module_PatientSummary(list);
	StudyContent = new DC3Module_StudyContent(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_StandaloneModalityLUT::Identify(void)
{
	return "StandaloneModalityLUT";
}

DC3CompositeIOD_StandaloneModalityLUT::DC3CompositeIOD_StandaloneModalityLUT(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	ModalityLUT = new DC3Module_ModalityLUT(list);
	LUTIdentification = new DC3Module_LUTIdentification(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}

char *
DC3CompositeIOD_StandaloneVOILUT::Identify(void)
{
	return "StandaloneVOILUT";
}

DC3CompositeIOD_StandaloneVOILUT::DC3CompositeIOD_StandaloneVOILUT(DC3ListofAttributes *list)
{
	Patient = new DC3Module_Patient(list);
	GeneralStudy = new DC3Module_GeneralStudy(list);
	PatientStudy = new DC3Module_PatientStudy(list);
	GeneralSeries = new DC3Module_GeneralSeries(list);
	GeneralEquipment = new DC3Module_GeneralEquipment(list);
	VOILUT = new DC3Module_VOILUT(list);
	LUTIdentification = new DC3Module_LUTIdentification(list);
	SOPCommon = new DC3Module_SOPCommon(list);
}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
