/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by module.awk with options put

#include <iostream.h>

#include "tlist.h"
#include "tmodulet.h"
#include "tmodule.h"

void
DC3Module_PatientRelationship::Put(ostream& stream)
{
	stream << "\tModule <PatientRelationship>\n";

}

void
DC3Module_PatientIdentification::Put(ostream& stream)
{
	stream << "\tModule <PatientIdentification>\n";

	if (PatientName) {
		stream << "\t\t";
		PatientName->put(stream);
	}
	else
		stream << "\t\tElement <PatientName> not present\n";

	if (PatientID) {
		stream << "\t\t";
		PatientID->put(stream);
	}
	else
		stream << "\t\tElement <PatientID> not present\n";

	if (IssuerOfPatientID) {
		stream << "\t\t";
		IssuerOfPatientID->put(stream);
	}
	else
		stream << "\t\tElement <IssuerOfPatientID> not present\n";

	if (OtherPatientID) {
		stream << "\t\t";
		OtherPatientID->put(stream);
	}
	else
		stream << "\t\tElement <OtherPatientID> not present\n";

	if (OtherPatientName) {
		stream << "\t\t";
		OtherPatientName->put(stream);
	}
	else
		stream << "\t\tElement <OtherPatientName> not present\n";

	if (PatientBirthName) {
		stream << "\t\t";
		PatientBirthName->put(stream);
	}
	else
		stream << "\t\tElement <PatientBirthName> not present\n";

	if (PatientMotherBirthName) {
		stream << "\t\t";
		PatientMotherBirthName->put(stream);
	}
	else
		stream << "\t\tElement <PatientMotherBirthName> not present\n";

	if (MedicalRecordLocator) {
		stream << "\t\t";
		MedicalRecordLocator->put(stream);
	}
	else
		stream << "\t\tElement <MedicalRecordLocator> not present\n";

}

void
DC3Module_PatientDemographic::Put(ostream& stream)
{
	stream << "\tModule <PatientDemographic>\n";

	if (PatientBirthDate) {
		stream << "\t\t";
		PatientBirthDate->put(stream);
	}
	else
		stream << "\t\tElement <PatientBirthDate> not present\n";

	if (PatientBirthTime) {
		stream << "\t\t";
		PatientBirthTime->put(stream);
	}
	else
		stream << "\t\tElement <PatientBirthTime> not present\n";

	if (PatientSex) {
		stream << "\t\t";
		PatientSex->put(stream);
	}
	else
		stream << "\t\tElement <PatientSex> not present\n";

	if (PatientSize) {
		stream << "\t\t";
		PatientSize->put(stream);
	}
	else
		stream << "\t\tElement <PatientSize> not present\n";

	if (PatientWeight) {
		stream << "\t\t";
		PatientWeight->put(stream);
	}
	else
		stream << "\t\tElement <PatientWeight> not present\n";

	if (PatientAddress) {
		stream << "\t\t";
		PatientAddress->put(stream);
	}
	else
		stream << "\t\tElement <PatientAddress> not present\n";

	if (MilitaryRank) {
		stream << "\t\t";
		MilitaryRank->put(stream);
	}
	else
		stream << "\t\tElement <MilitaryRank> not present\n";

	if (BranchOfService) {
		stream << "\t\t";
		BranchOfService->put(stream);
	}
	else
		stream << "\t\tElement <BranchOfService> not present\n";

	if (CountryOfResidence) {
		stream << "\t\t";
		CountryOfResidence->put(stream);
	}
	else
		stream << "\t\tElement <CountryOfResidence> not present\n";

	if (RegionOfResidence) {
		stream << "\t\t";
		RegionOfResidence->put(stream);
	}
	else
		stream << "\t\tElement <RegionOfResidence> not present\n";

	if (PatientTelephoneNumber) {
		stream << "\t\t";
		PatientTelephoneNumber->put(stream);
	}
	else
		stream << "\t\tElement <PatientTelephoneNumber> not present\n";

	if (EthnicGroup) {
		stream << "\t\t";
		EthnicGroup->put(stream);
	}
	else
		stream << "\t\tElement <EthnicGroup> not present\n";

	if (PatientReligiousPreference) {
		stream << "\t\t";
		PatientReligiousPreference->put(stream);
	}
	else
		stream << "\t\tElement <PatientReligiousPreference> not present\n";

	if (PatientComments) {
		stream << "\t\t";
		PatientComments->put(stream);
	}
	else
		stream << "\t\tElement <PatientComments> not present\n";

}

void
DC3Module_PatientMedical::Put(ostream& stream)
{
	stream << "\tModule <PatientMedical>\n";

	if (MedicalAlerts) {
		stream << "\t\t";
		MedicalAlerts->put(stream);
	}
	else
		stream << "\t\tElement <MedicalAlerts> not present\n";

	if (ContrastAllergies) {
		stream << "\t\t";
		ContrastAllergies->put(stream);
	}
	else
		stream << "\t\tElement <ContrastAllergies> not present\n";

	if (SmokingStatus) {
		stream << "\t\t";
		SmokingStatus->put(stream);
	}
	else
		stream << "\t\tElement <SmokingStatus> not present\n";

	if (AdditionalPatientHistory) {
		stream << "\t\t";
		AdditionalPatientHistory->put(stream);
	}
	else
		stream << "\t\tElement <AdditionalPatientHistory> not present\n";

	if (PregnancyStatus) {
		stream << "\t\t";
		PregnancyStatus->put(stream);
	}
	else
		stream << "\t\tElement <PregnancyStatus> not present\n";

	if (LastMenstrualDate) {
		stream << "\t\t";
		LastMenstrualDate->put(stream);
	}
	else
		stream << "\t\tElement <LastMenstrualDate> not present\n";

	if (SpecialNeeds) {
		stream << "\t\t";
		SpecialNeeds->put(stream);
	}
	else
		stream << "\t\tElement <SpecialNeeds> not present\n";

	if (PatientState) {
		stream << "\t\t";
		PatientState->put(stream);
	}
	else
		stream << "\t\tElement <PatientState> not present\n";

}

void
DC3Module_VisitRelationship::Put(ostream& stream)
{
	stream << "\tModule <VisitRelationship>\n";

}

void
DC3Module_VisitIdentification::Put(ostream& stream)
{
	stream << "\tModule <VisitIdentification>\n";

	if (InstitutionName) {
		stream << "\t\t";
		InstitutionName->put(stream);
	}
	else
		stream << "\t\tElement <InstitutionName> not present\n";

	if (InstitutionAddress) {
		stream << "\t\t";
		InstitutionAddress->put(stream);
	}
	else
		stream << "\t\tElement <InstitutionAddress> not present\n";

	if (AdmissionID) {
		stream << "\t\t";
		AdmissionID->put(stream);
	}
	else
		stream << "\t\tElement <AdmissionID> not present\n";

	if (IssuerOfAdmissionID) {
		stream << "\t\t";
		IssuerOfAdmissionID->put(stream);
	}
	else
		stream << "\t\tElement <IssuerOfAdmissionID> not present\n";

}

void
DC3Module_VisitStatus::Put(ostream& stream)
{
	stream << "\tModule <VisitStatus>\n";

	if (VisitStatusID) {
		stream << "\t\t";
		VisitStatusID->put(stream);
	}
	else
		stream << "\t\tElement <VisitStatusID> not present\n";

	if (CurrentPatientLocation) {
		stream << "\t\t";
		CurrentPatientLocation->put(stream);
	}
	else
		stream << "\t\tElement <CurrentPatientLocation> not present\n";

	if (PatientInstitutionResidence) {
		stream << "\t\t";
		PatientInstitutionResidence->put(stream);
	}
	else
		stream << "\t\tElement <PatientInstitutionResidence> not present\n";

	if (VisitComments) {
		stream << "\t\t";
		VisitComments->put(stream);
	}
	else
		stream << "\t\tElement <VisitComments> not present\n";

}

void
DC3Module_VisitAdmission::Put(ostream& stream)
{
	stream << "\tModule <VisitAdmission>\n";

	if (ReferringPhysicianName) {
		stream << "\t\t";
		ReferringPhysicianName->put(stream);
	}
	else
		stream << "\t\tElement <ReferringPhysicianName> not present\n";

	if (ReferringPhysicianAddress) {
		stream << "\t\t";
		ReferringPhysicianAddress->put(stream);
	}
	else
		stream << "\t\tElement <ReferringPhysicianAddress> not present\n";

	if (ReferringPhysicianTelephoneNumber) {
		stream << "\t\t";
		ReferringPhysicianTelephoneNumber->put(stream);
	}
	else
		stream << "\t\tElement <ReferringPhysicianTelephoneNumber> not present\n";

	if (AdmittingDiagnosisDescription) {
		stream << "\t\t";
		AdmittingDiagnosisDescription->put(stream);
	}
	else
		stream << "\t\tElement <AdmittingDiagnosisDescription> not present\n";

	if (RouteOfAdmissions) {
		stream << "\t\t";
		RouteOfAdmissions->put(stream);
	}
	else
		stream << "\t\tElement <RouteOfAdmissions> not present\n";

	if (AdmittingDate) {
		stream << "\t\t";
		AdmittingDate->put(stream);
	}
	else
		stream << "\t\tElement <AdmittingDate> not present\n";

	if (AdmittingTime) {
		stream << "\t\t";
		AdmittingTime->put(stream);
	}
	else
		stream << "\t\tElement <AdmittingTime> not present\n";

}

void
DC3Module_VisitDischarge::Put(ostream& stream)
{
	stream << "\tModule <VisitDischarge>\n";

	if (DischargeDate) {
		stream << "\t\t";
		DischargeDate->put(stream);
	}
	else
		stream << "\t\tElement <DischargeDate> not present\n";

	if (DischargeTime) {
		stream << "\t\t";
		DischargeTime->put(stream);
	}
	else
		stream << "\t\tElement <DischargeTime> not present\n";

	if (DischargeDiagnosisDescription) {
		stream << "\t\t";
		DischargeDiagnosisDescription->put(stream);
	}
	else
		stream << "\t\tElement <DischargeDiagnosisDescription> not present\n";

}

void
DC3Module_VisitScheduling::Put(ostream& stream)
{
	stream << "\tModule <VisitScheduling>\n";

	if (ScheduledAdmissionDate) {
		stream << "\t\t";
		ScheduledAdmissionDate->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledAdmissionDate> not present\n";

	if (ScheduledAdmissionTime) {
		stream << "\t\t";
		ScheduledAdmissionTime->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledAdmissionTime> not present\n";

	if (ScheduledDischargeDate) {
		stream << "\t\t";
		ScheduledDischargeDate->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledDischargeDate> not present\n";

	if (ScheduledDischargeTime) {
		stream << "\t\t";
		ScheduledDischargeTime->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledDischargeTime> not present\n";

	if (ScheduledPatientInstitutionResidence) {
		stream << "\t\t";
		ScheduledPatientInstitutionResidence->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledPatientInstitutionResidence> not present\n";

}

void
DC3Module_StudyRelationship::Put(ostream& stream)
{
	stream << "\tModule <StudyRelationship>\n";

	if (StudyInstanceUID) {
		stream << "\t\t";
		StudyInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <StudyInstanceUID> not present\n";

	if (AccessionNumber) {
		stream << "\t\t";
		AccessionNumber->put(stream);
	}
	else
		stream << "\t\tElement <AccessionNumber> not present\n";

}

void
DC3Module_StudyIdentification::Put(ostream& stream)
{
	stream << "\tModule <StudyIdentification>\n";

	if (StudyID) {
		stream << "\t\t";
		StudyID->put(stream);
	}
	else
		stream << "\t\tElement <StudyID> not present\n";

	if (StudyIDIssuer) {
		stream << "\t\t";
		StudyIDIssuer->put(stream);
	}
	else
		stream << "\t\tElement <StudyIDIssuer> not present\n";

	if (OtherStudyNumbers) {
		stream << "\t\t";
		OtherStudyNumbers->put(stream);
	}
	else
		stream << "\t\tElement <OtherStudyNumbers> not present\n";

}

void
DC3Module_StudyClassification::Put(ostream& stream)
{
	stream << "\tModule <StudyClassification>\n";

	if (StudyStatusID) {
		stream << "\t\t";
		StudyStatusID->put(stream);
	}
	else
		stream << "\t\tElement <StudyStatusID> not present\n";

	if (StudyPriorityID) {
		stream << "\t\t";
		StudyPriorityID->put(stream);
	}
	else
		stream << "\t\tElement <StudyPriorityID> not present\n";

	if (StudyComments) {
		stream << "\t\t";
		StudyComments->put(stream);
	}
	else
		stream << "\t\tElement <StudyComments> not present\n";

}

void
DC3Module_StudyScheduling::Put(ostream& stream)
{
	stream << "\tModule <StudyScheduling>\n";

	if (ScheduledStudyStartDate) {
		stream << "\t\t";
		ScheduledStudyStartDate->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyStartDate> not present\n";

	if (ScheduledStudyStartTime) {
		stream << "\t\t";
		ScheduledStudyStartTime->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyStartTime> not present\n";

	if (ScheduledStudyStopDate) {
		stream << "\t\t";
		ScheduledStudyStopDate->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyStopDate> not present\n";

	if (ScheduledStudyStopTime) {
		stream << "\t\t";
		ScheduledStudyStopTime->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyStopTime> not present\n";

	if (ScheduledStudyLocation) {
		stream << "\t\t";
		ScheduledStudyLocation->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyLocation> not present\n";

	if (ScheduledStudyLocationAETitle) {
		stream << "\t\t";
		ScheduledStudyLocationAETitle->put(stream);
	}
	else
		stream << "\t\tElement <ScheduledStudyLocationAETitle> not present\n";

	if (ReasonForStudy) {
		stream << "\t\t";
		ReasonForStudy->put(stream);
	}
	else
		stream << "\t\tElement <ReasonForStudy> not present\n";

	if (RequestingPhysician) {
		stream << "\t\t";
		RequestingPhysician->put(stream);
	}
	else
		stream << "\t\tElement <RequestingPhysician> not present\n";

	if (RequestingService) {
		stream << "\t\t";
		RequestingService->put(stream);
	}
	else
		stream << "\t\tElement <RequestingService> not present\n";

	if (RequestedProcedureDescription) {
		stream << "\t\t";
		RequestedProcedureDescription->put(stream);
	}
	else
		stream << "\t\tElement <RequestedProcedureDescription> not present\n";

	if (RequestedContrastAgent) {
		stream << "\t\t";
		RequestedContrastAgent->put(stream);
	}
	else
		stream << "\t\tElement <RequestedContrastAgent> not present\n";

}

void
DC3Module_StudyAcquisition::Put(ostream& stream)
{
	stream << "\tModule <StudyAcquisition>\n";

	if (StudyArrivalDate) {
		stream << "\t\t";
		StudyArrivalDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyArrivalDate> not present\n";

	if (StudyArrivalTime) {
		stream << "\t\t";
		StudyArrivalTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyArrivalTime> not present\n";

	if (StudyDate) {
		stream << "\t\t";
		StudyDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyDate> not present\n";

	if (StudyTime) {
		stream << "\t\t";
		StudyTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyTime> not present\n";

	if (StudyCompletionDate) {
		stream << "\t\t";
		StudyCompletionDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyCompletionDate> not present\n";

	if (StudyCompletionTime) {
		stream << "\t\t";
		StudyCompletionTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyCompletionTime> not present\n";

	if (StudyVerifiedDate) {
		stream << "\t\t";
		StudyVerifiedDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyVerifiedDate> not present\n";

	if (StudyVerifiedTime) {
		stream << "\t\t";
		StudyVerifiedTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyVerifiedTime> not present\n";

	if (SeriesInStudy) {
		stream << "\t\t";
		SeriesInStudy->put(stream);
	}
	else
		stream << "\t\tElement <SeriesInStudy> not present\n";

	if (AcquisitionsInStudy) {
		stream << "\t\t";
		AcquisitionsInStudy->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionsInStudy> not present\n";

}

void
DC3Module_StudyRead::Put(ostream& stream)
{
	stream << "\tModule <StudyRead>\n";

	if (PhysicianReadingStudy) {
		stream << "\t\t";
		PhysicianReadingStudy->put(stream);
	}
	else
		stream << "\t\tElement <PhysicianReadingStudy> not present\n";

	if (StudyReadDate) {
		stream << "\t\t";
		StudyReadDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyReadDate> not present\n";

	if (StudyReadTime) {
		stream << "\t\t";
		StudyReadTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyReadTime> not present\n";

}

void
DC3Module_StudyComponent::Put(ostream& stream)
{
	stream << "\tModule <StudyComponent>\n";

	if (StudyID) {
		stream << "\t\t";
		StudyID->put(stream);
	}
	else
		stream << "\t\tElement <StudyID> not present\n";

	if (StudyInstanceUID) {
		stream << "\t\t";
		StudyInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <StudyInstanceUID> not present\n";

}

void
DC3Module_StudyComponentRelationship::Put(ostream& stream)
{
	stream << "\tModule <StudyComponentRelationship>\n";

}

void
DC3Module_StudyComponentAcquisition::Put(ostream& stream)
{
	stream << "\tModule <StudyComponentAcquisition>\n";

	if (Modality) {
		stream << "\t\t";
		Modality->put(stream);
	}
	else
		stream << "\t\tElement <Modality> not present\n";

	if (StudyDescription) {
		stream << "\t\t";
		StudyDescription->put(stream);
	}
	else
		stream << "\t\tElement <StudyDescription> not present\n";

	if (PerformingPhysicianName) {
		stream << "\t\t";
		PerformingPhysicianName->put(stream);
	}
	else
		stream << "\t\tElement <PerformingPhysicianName> not present\n";

	if (StudyComponentStatusID) {
		stream << "\t\t";
		StudyComponentStatusID->put(stream);
	}
	else
		stream << "\t\tElement <StudyComponentStatusID> not present\n";

}

void
DC3Module_ResultsRelationship::Put(ostream& stream)
{
	stream << "\tModule <ResultsRelationship>\n";

}

void
DC3Module_ResultsIdentification::Put(ostream& stream)
{
	stream << "\tModule <ResultsIdentification>\n";

	if (ResultsID) {
		stream << "\t\t";
		ResultsID->put(stream);
	}
	else
		stream << "\t\tElement <ResultsID> not present\n";

	if (ResultsIDIssuer) {
		stream << "\t\t";
		ResultsIDIssuer->put(stream);
	}
	else
		stream << "\t\tElement <ResultsIDIssuer> not present\n";

}

void
DC3Module_ResultsImpression::Put(ostream& stream)
{
	stream << "\tModule <ResultsImpression>\n";

	if (Impressions) {
		stream << "\t\t";
		Impressions->put(stream);
	}
	else
		stream << "\t\tElement <Impressions> not present\n";

	if (ResultsComments) {
		stream << "\t\t";
		ResultsComments->put(stream);
	}
	else
		stream << "\t\tElement <ResultsComments> not present\n";

}

void
DC3Module_InterpretationRelationship::Put(ostream& stream)
{
	stream << "\tModule <InterpretationRelationship>\n";

}

void
DC3Module_InterpretationIdentification::Put(ostream& stream)
{
	stream << "\tModule <InterpretationIdentification>\n";

	if (InterpretationID) {
		stream << "\t\t";
		InterpretationID->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationID> not present\n";

	if (InterpretationIDIssuer) {
		stream << "\t\t";
		InterpretationIDIssuer->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationIDIssuer> not present\n";

}

void
DC3Module_InterpretationState::Put(ostream& stream)
{
	stream << "\tModule <InterpretationState>\n";

	if (InterpretationTypeID) {
		stream << "\t\t";
		InterpretationTypeID->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationTypeID> not present\n";

	if (InterpretationStatusID) {
		stream << "\t\t";
		InterpretationStatusID->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationStatusID> not present\n";

}

void
DC3Module_InterpretationRecording::Put(ostream& stream)
{
	stream << "\tModule <InterpretationRecording>\n";

	if (InterpretationRecordedDate) {
		stream << "\t\t";
		InterpretationRecordedDate->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationRecordedDate> not present\n";

	if (InterpretationRecordedTime) {
		stream << "\t\t";
		InterpretationRecordedTime->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationRecordedTime> not present\n";

	if (InterpretationRecorder) {
		stream << "\t\t";
		InterpretationRecorder->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationRecorder> not present\n";

	if (ReferenceToRecordedSound) {
		stream << "\t\t";
		ReferenceToRecordedSound->put(stream);
	}
	else
		stream << "\t\tElement <ReferenceToRecordedSound> not present\n";

}

void
DC3Module_InterpretationTranscription::Put(ostream& stream)
{
	stream << "\tModule <InterpretationTranscription>\n";

	if (InterpretationTranscriptionDate) {
		stream << "\t\t";
		InterpretationTranscriptionDate->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationTranscriptionDate> not present\n";

	if (InterpretationTranscriptionTime) {
		stream << "\t\t";
		InterpretationTranscriptionTime->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationTranscriptionTime> not present\n";

	if (InterpretationTranscriber) {
		stream << "\t\t";
		InterpretationTranscriber->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationTranscriber> not present\n";

	if (InterpretationText) {
		stream << "\t\t";
		InterpretationText->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationText> not present\n";

	if (InterpretationAuthor) {
		stream << "\t\t";
		InterpretationAuthor->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationAuthor> not present\n";

}

void
DC3Module_InterpretationApproval::Put(ostream& stream)
{
	stream << "\tModule <InterpretationApproval>\n";

	if (InterpretationDiagnosisDescription) {
		stream << "\t\t";
		InterpretationDiagnosisDescription->put(stream);
	}
	else
		stream << "\t\tElement <InterpretationDiagnosisDescription> not present\n";

}

void
DC3Module_Patient::Put(ostream& stream)
{
	stream << "\tModule <Patient>\n";

	if (PatientName) {
		stream << "\t\t";
		PatientName->put(stream);
	}
	else
		stream << "\t\tElement <PatientName> not present\n";

	if (PatientID) {
		stream << "\t\t";
		PatientID->put(stream);
	}
	else
		stream << "\t\tElement <PatientID> not present\n";

	if (PatientBirthDate) {
		stream << "\t\t";
		PatientBirthDate->put(stream);
	}
	else
		stream << "\t\tElement <PatientBirthDate> not present\n";

	if (PatientSex) {
		stream << "\t\t";
		PatientSex->put(stream);
	}
	else
		stream << "\t\tElement <PatientSex> not present\n";

	if (PatientBirthTime) {
		stream << "\t\t";
		PatientBirthTime->put(stream);
	}
	else
		stream << "\t\tElement <PatientBirthTime> not present\n";

	if (OtherPatientID) {
		stream << "\t\t";
		OtherPatientID->put(stream);
	}
	else
		stream << "\t\tElement <OtherPatientID> not present\n";

	if (OtherPatientName) {
		stream << "\t\t";
		OtherPatientName->put(stream);
	}
	else
		stream << "\t\tElement <OtherPatientName> not present\n";

	if (EthnicGroup) {
		stream << "\t\t";
		EthnicGroup->put(stream);
	}
	else
		stream << "\t\tElement <EthnicGroup> not present\n";

	if (PatientComments) {
		stream << "\t\t";
		PatientComments->put(stream);
	}
	else
		stream << "\t\tElement <PatientComments> not present\n";

}

void
DC3Module_GeneralStudy::Put(ostream& stream)
{
	stream << "\tModule <GeneralStudy>\n";

	if (StudyInstanceUID) {
		stream << "\t\t";
		StudyInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <StudyInstanceUID> not present\n";

	if (StudyDate) {
		stream << "\t\t";
		StudyDate->put(stream);
	}
	else
		stream << "\t\tElement <StudyDate> not present\n";

	if (StudyTime) {
		stream << "\t\t";
		StudyTime->put(stream);
	}
	else
		stream << "\t\tElement <StudyTime> not present\n";

	if (ReferringPhysicianName) {
		stream << "\t\t";
		ReferringPhysicianName->put(stream);
	}
	else
		stream << "\t\tElement <ReferringPhysicianName> not present\n";

	if (StudyID) {
		stream << "\t\t";
		StudyID->put(stream);
	}
	else
		stream << "\t\tElement <StudyID> not present\n";

	if (AccessionNumber) {
		stream << "\t\t";
		AccessionNumber->put(stream);
	}
	else
		stream << "\t\tElement <AccessionNumber> not present\n";

	if (StudyDescription) {
		stream << "\t\t";
		StudyDescription->put(stream);
	}
	else
		stream << "\t\tElement <StudyDescription> not present\n";

	if (PhysicianReadingStudy) {
		stream << "\t\t";
		PhysicianReadingStudy->put(stream);
	}
	else
		stream << "\t\tElement <PhysicianReadingStudy> not present\n";

}

void
DC3Module_PatientStudy::Put(ostream& stream)
{
	stream << "\tModule <PatientStudy>\n";

	if (AdmittingDiagnosisDescription) {
		stream << "\t\t";
		AdmittingDiagnosisDescription->put(stream);
	}
	else
		stream << "\t\tElement <AdmittingDiagnosisDescription> not present\n";

	if (PatientAge) {
		stream << "\t\t";
		PatientAge->put(stream);
	}
	else
		stream << "\t\tElement <PatientAge> not present\n";

	if (PatientSize) {
		stream << "\t\t";
		PatientSize->put(stream);
	}
	else
		stream << "\t\tElement <PatientSize> not present\n";

	if (PatientWeight) {
		stream << "\t\t";
		PatientWeight->put(stream);
	}
	else
		stream << "\t\tElement <PatientWeight> not present\n";

	if (Occupation) {
		stream << "\t\t";
		Occupation->put(stream);
	}
	else
		stream << "\t\tElement <Occupation> not present\n";

	if (AdditionalPatientHistory) {
		stream << "\t\t";
		AdditionalPatientHistory->put(stream);
	}
	else
		stream << "\t\tElement <AdditionalPatientHistory> not present\n";

}

void
DC3Module_GeneralSeries::Put(ostream& stream)
{
	stream << "\tModule <GeneralSeries>\n";

	if (Modality) {
		stream << "\t\t";
		Modality->put(stream);
	}
	else
		stream << "\t\tElement <Modality> not present\n";

	if (SeriesInstanceUID) {
		stream << "\t\t";
		SeriesInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <SeriesInstanceUID> not present\n";

	if (SeriesNumber) {
		stream << "\t\t";
		SeriesNumber->put(stream);
	}
	else
		stream << "\t\tElement <SeriesNumber> not present\n";

	if (Laterality) {
		stream << "\t\t";
		Laterality->put(stream);
	}
	else
		stream << "\t\tElement <Laterality> not present\n";

	if (SeriesDate) {
		stream << "\t\t";
		SeriesDate->put(stream);
	}
	else
		stream << "\t\tElement <SeriesDate> not present\n";

	if (SeriesTime) {
		stream << "\t\t";
		SeriesTime->put(stream);
	}
	else
		stream << "\t\tElement <SeriesTime> not present\n";

	if (PerformingPhysicianName) {
		stream << "\t\t";
		PerformingPhysicianName->put(stream);
	}
	else
		stream << "\t\tElement <PerformingPhysicianName> not present\n";

	if (ProtocolName) {
		stream << "\t\t";
		ProtocolName->put(stream);
	}
	else
		stream << "\t\tElement <ProtocolName> not present\n";

	if (SeriesDescription) {
		stream << "\t\t";
		SeriesDescription->put(stream);
	}
	else
		stream << "\t\tElement <SeriesDescription> not present\n";

	if (OperatorName) {
		stream << "\t\t";
		OperatorName->put(stream);
	}
	else
		stream << "\t\tElement <OperatorName> not present\n";

	if (BodyPartExamined) {
		stream << "\t\t";
		BodyPartExamined->put(stream);
	}
	else
		stream << "\t\tElement <BodyPartExamined> not present\n";

	if (PatientPosition) {
		stream << "\t\t";
		PatientPosition->put(stream);
	}
	else
		stream << "\t\tElement <PatientPosition> not present\n";

	if (SmallestPixelValueInSeries) {
		stream << "\t\t";
		SmallestPixelValueInSeries->put(stream);
	}
	else
		stream << "\t\tElement <SmallestPixelValueInSeries> not present\n";

	if (LargestPixelValueInSeries) {
		stream << "\t\t";
		LargestPixelValueInSeries->put(stream);
	}
	else
		stream << "\t\tElement <LargestPixelValueInSeries> not present\n";

}

void
DC3Module_FrameOfReference::Put(ostream& stream)
{
	stream << "\tModule <FrameOfReference>\n";

	if (FrameOfReferenceUID) {
		stream << "\t\t";
		FrameOfReferenceUID->put(stream);
	}
	else
		stream << "\t\tElement <FrameOfReferenceUID> not present\n";

	if (PositionReferenceIndicator) {
		stream << "\t\t";
		PositionReferenceIndicator->put(stream);
	}
	else
		stream << "\t\tElement <PositionReferenceIndicator> not present\n";

}

void
DC3Module_GeneralEquipment::Put(ostream& stream)
{
	stream << "\tModule <GeneralEquipment>\n";

	if (Manufacturer) {
		stream << "\t\t";
		Manufacturer->put(stream);
	}
	else
		stream << "\t\tElement <Manufacturer> not present\n";

	if (InstitutionName) {
		stream << "\t\t";
		InstitutionName->put(stream);
	}
	else
		stream << "\t\tElement <InstitutionName> not present\n";

	if (InstitutionAddress) {
		stream << "\t\t";
		InstitutionAddress->put(stream);
	}
	else
		stream << "\t\tElement <InstitutionAddress> not present\n";

	if (StationName) {
		stream << "\t\t";
		StationName->put(stream);
	}
	else
		stream << "\t\tElement <StationName> not present\n";

	if (InstitutionalDepartmentName) {
		stream << "\t\t";
		InstitutionalDepartmentName->put(stream);
	}
	else
		stream << "\t\tElement <InstitutionalDepartmentName> not present\n";

	if (ManufacturerModelName) {
		stream << "\t\t";
		ManufacturerModelName->put(stream);
	}
	else
		stream << "\t\tElement <ManufacturerModelName> not present\n";

	if (DeviceSerialNumber) {
		stream << "\t\t";
		DeviceSerialNumber->put(stream);
	}
	else
		stream << "\t\tElement <DeviceSerialNumber> not present\n";

	if (SoftwareVersion) {
		stream << "\t\t";
		SoftwareVersion->put(stream);
	}
	else
		stream << "\t\tElement <SoftwareVersion> not present\n";

	if (SpatialResolution) {
		stream << "\t\t";
		SpatialResolution->put(stream);
	}
	else
		stream << "\t\tElement <SpatialResolution> not present\n";

	if (DateOfLastCalibration) {
		stream << "\t\t";
		DateOfLastCalibration->put(stream);
	}
	else
		stream << "\t\tElement <DateOfLastCalibration> not present\n";

	if (TimeOfLastCalibration) {
		stream << "\t\t";
		TimeOfLastCalibration->put(stream);
	}
	else
		stream << "\t\tElement <TimeOfLastCalibration> not present\n";

	if (PixelPaddingValue) {
		stream << "\t\t";
		PixelPaddingValue->put(stream);
	}
	else
		stream << "\t\tElement <PixelPaddingValue> not present\n";

}

void
DC3Module_GeneralImage::Put(ostream& stream)
{
	stream << "\tModule <GeneralImage>\n";

	if (ImageNumber) {
		stream << "\t\t";
		ImageNumber->put(stream);
	}
	else
		stream << "\t\tElement <ImageNumber> not present\n";

	if (PatientOrientation) {
		stream << "\t\t";
		PatientOrientation->put(stream);
	}
	else
		stream << "\t\tElement <PatientOrientation> not present\n";

	if (ImageDate) {
		stream << "\t\t";
		ImageDate->put(stream);
	}
	else
		stream << "\t\tElement <ImageDate> not present\n";

	if (ImageTime) {
		stream << "\t\t";
		ImageTime->put(stream);
	}
	else
		stream << "\t\tElement <ImageTime> not present\n";

	if (ImageType) {
		stream << "\t\t";
		ImageType->put(stream);
	}
	else
		stream << "\t\tElement <ImageType> not present\n";

	if (AcquisitionNumber) {
		stream << "\t\t";
		AcquisitionNumber->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionNumber> not present\n";

	if (AcquisitionDate) {
		stream << "\t\t";
		AcquisitionDate->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionDate> not present\n";

	if (AcquisitionTime) {
		stream << "\t\t";
		AcquisitionTime->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionTime> not present\n";

	if (DerivationDescription) {
		stream << "\t\t";
		DerivationDescription->put(stream);
	}
	else
		stream << "\t\tElement <DerivationDescription> not present\n";

	if (ImagesInAcquisition) {
		stream << "\t\t";
		ImagesInAcquisition->put(stream);
	}
	else
		stream << "\t\tElement <ImagesInAcquisition> not present\n";

	if (ImageComments) {
		stream << "\t\t";
		ImageComments->put(stream);
	}
	else
		stream << "\t\tElement <ImageComments> not present\n";

}

void
DC3Module_ImagePlane::Put(ostream& stream)
{
	stream << "\tModule <ImagePlane>\n";

	if (PixelSpacing) {
		stream << "\t\t";
		PixelSpacing->put(stream);
	}
	else
		stream << "\t\tElement <PixelSpacing> not present\n";

	if (ImageOrientationPatient) {
		stream << "\t\t";
		ImageOrientationPatient->put(stream);
	}
	else
		stream << "\t\tElement <ImageOrientationPatient> not present\n";

	if (ImagePositionPatient) {
		stream << "\t\t";
		ImagePositionPatient->put(stream);
	}
	else
		stream << "\t\tElement <ImagePositionPatient> not present\n";

	if (SliceThickness) {
		stream << "\t\t";
		SliceThickness->put(stream);
	}
	else
		stream << "\t\tElement <SliceThickness> not present\n";

	if (SliceLocation) {
		stream << "\t\t";
		SliceLocation->put(stream);
	}
	else
		stream << "\t\tElement <SliceLocation> not present\n";

}

void
DC3Module_ImagePixel::Put(ostream& stream)
{
	stream << "\tModule <ImagePixel>\n";

	if (SamplesPerPixel) {
		stream << "\t\t";
		SamplesPerPixel->put(stream);
	}
	else
		stream << "\t\tElement <SamplesPerPixel> not present\n";

	if (PhotometricInterpretation) {
		stream << "\t\t";
		PhotometricInterpretation->put(stream);
	}
	else
		stream << "\t\tElement <PhotometricInterpretation> not present\n";

	if (Rows) {
		stream << "\t\t";
		Rows->put(stream);
	}
	else
		stream << "\t\tElement <Rows> not present\n";

	if (Columns) {
		stream << "\t\t";
		Columns->put(stream);
	}
	else
		stream << "\t\tElement <Columns> not present\n";

	if (BitsAllocated) {
		stream << "\t\t";
		BitsAllocated->put(stream);
	}
	else
		stream << "\t\tElement <BitsAllocated> not present\n";

	if (BitsStored) {
		stream << "\t\t";
		BitsStored->put(stream);
	}
	else
		stream << "\t\tElement <BitsStored> not present\n";

	if (HighBit) {
		stream << "\t\t";
		HighBit->put(stream);
	}
	else
		stream << "\t\tElement <HighBit> not present\n";

	if (PixelRepresentation) {
		stream << "\t\t";
		PixelRepresentation->put(stream);
	}
	else
		stream << "\t\tElement <PixelRepresentation> not present\n";

	if (PixelData) {
		stream << "\t\t";
		PixelData->put(stream);
	}
	else
		stream << "\t\tElement <PixelData> not present\n";

	if (PlanarConfiguration) {
		stream << "\t\t";
		PlanarConfiguration->put(stream);
	}
	else
		stream << "\t\tElement <PlanarConfiguration> not present\n";

	if (PixelAspectRatio) {
		stream << "\t\t";
		PixelAspectRatio->put(stream);
	}
	else
		stream << "\t\tElement <PixelAspectRatio> not present\n";

	if (SmallestImagePixelValue) {
		stream << "\t\t";
		SmallestImagePixelValue->put(stream);
	}
	else
		stream << "\t\tElement <SmallestImagePixelValue> not present\n";

	if (LargestImagePixelValue) {
		stream << "\t\t";
		LargestImagePixelValue->put(stream);
	}
	else
		stream << "\t\tElement <LargestImagePixelValue> not present\n";

	if (RedPaletteColorLookupTableDescriptor) {
		stream << "\t\t";
		RedPaletteColorLookupTableDescriptor->put(stream);
	}
	else
		stream << "\t\tElement <RedPaletteColorLookupTableDescriptor> not present\n";

	if (GreenPaletteColorLookupTableDescriptor) {
		stream << "\t\t";
		GreenPaletteColorLookupTableDescriptor->put(stream);
	}
	else
		stream << "\t\tElement <GreenPaletteColorLookupTableDescriptor> not present\n";

	if (BluePaletteColorLookupTableDescriptor) {
		stream << "\t\t";
		BluePaletteColorLookupTableDescriptor->put(stream);
	}
	else
		stream << "\t\tElement <BluePaletteColorLookupTableDescriptor> not present\n";

	if (RedPaletteColorLookupTableData) {
		stream << "\t\t";
		RedPaletteColorLookupTableData->put(stream);
	}
	else
		stream << "\t\tElement <RedPaletteColorLookupTableData> not present\n";

	if (GreenPaletteColorLookupTableData) {
		stream << "\t\t";
		GreenPaletteColorLookupTableData->put(stream);
	}
	else
		stream << "\t\tElement <GreenPaletteColorLookupTableData> not present\n";

	if (BluePaletteColorLookupTableData) {
		stream << "\t\t";
		BluePaletteColorLookupTableData->put(stream);
	}
	else
		stream << "\t\tElement <BluePaletteColorLookupTableData> not present\n";

}

void
DC3Module_ContrastBolus::Put(ostream& stream)
{
	stream << "\tModule <ContrastBolus>\n";

	if (ContrastBolusAgent) {
		stream << "\t\t";
		ContrastBolusAgent->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusAgent> not present\n";

	if (ContrastBolusRoute) {
		stream << "\t\t";
		ContrastBolusRoute->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusRoute> not present\n";

	if (ContrastBolusVolume) {
		stream << "\t\t";
		ContrastBolusVolume->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusVolume> not present\n";

	if (ContrastBolusStartTime) {
		stream << "\t\t";
		ContrastBolusStartTime->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusStartTime> not present\n";

	if (ContrastBolusStopTime) {
		stream << "\t\t";
		ContrastBolusStopTime->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusStopTime> not present\n";

	if (ContrastBolusTotalDose) {
		stream << "\t\t";
		ContrastBolusTotalDose->put(stream);
	}
	else
		stream << "\t\tElement <ContrastBolusTotalDose> not present\n";

}

void
DC3Module_Cine::Put(ostream& stream)
{
	stream << "\tModule <Cine>\n";

	if (FrameTime) {
		stream << "\t\t";
		FrameTime->put(stream);
	}
	else
		stream << "\t\tElement <FrameTime> not present\n";

	if (FrameTimeVector) {
		stream << "\t\t";
		FrameTimeVector->put(stream);
	}
	else
		stream << "\t\tElement <FrameTimeVector> not present\n";

	if (StartTrim) {
		stream << "\t\t";
		StartTrim->put(stream);
	}
	else
		stream << "\t\tElement <StartTrim> not present\n";

	if (StopTrim) {
		stream << "\t\t";
		StopTrim->put(stream);
	}
	else
		stream << "\t\tElement <StopTrim> not present\n";

	if (RecommendedDisplayFrameRate) {
		stream << "\t\t";
		RecommendedDisplayFrameRate->put(stream);
	}
	else
		stream << "\t\tElement <RecommendedDisplayFrameRate> not present\n";

	if (CineRate) {
		stream << "\t\t";
		CineRate->put(stream);
	}
	else
		stream << "\t\tElement <CineRate> not present\n";

	if (FrameDelay) {
		stream << "\t\t";
		FrameDelay->put(stream);
	}
	else
		stream << "\t\tElement <FrameDelay> not present\n";

	if (EffectiveSeriesDuration) {
		stream << "\t\t";
		EffectiveSeriesDuration->put(stream);
	}
	else
		stream << "\t\tElement <EffectiveSeriesDuration> not present\n";

	if (ActualFrameDuration) {
		stream << "\t\t";
		ActualFrameDuration->put(stream);
	}
	else
		stream << "\t\tElement <ActualFrameDuration> not present\n";

}

void
DC3Module_MultiFrame::Put(ostream& stream)
{
	stream << "\tModule <MultiFrame>\n";

	if (NumberOfFrames) {
		stream << "\t\t";
		NumberOfFrames->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfFrames> not present\n";

	if (FrameIncrementPointer) {
		stream << "\t\t";
		FrameIncrementPointer->put(stream);
	}
	else
		stream << "\t\tElement <FrameIncrementPointer> not present\n";

}

void
DC3Module_PatientSummary::Put(ostream& stream)
{
	stream << "\tModule <PatientSummary>\n";

	if (PatientName) {
		stream << "\t\t";
		PatientName->put(stream);
	}
	else
		stream << "\t\tElement <PatientName> not present\n";

	if (PatientID) {
		stream << "\t\t";
		PatientID->put(stream);
	}
	else
		stream << "\t\tElement <PatientID> not present\n";

}

void
DC3Module_StudyContent::Put(ostream& stream)
{
	stream << "\tModule <StudyContent>\n";

	if (StudyID) {
		stream << "\t\t";
		StudyID->put(stream);
	}
	else
		stream << "\t\tElement <StudyID> not present\n";

	if (StudyInstanceUID) {
		stream << "\t\t";
		StudyInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <StudyInstanceUID> not present\n";

}

void
DC3Module_CRSeries::Put(ostream& stream)
{
	stream << "\tModule <CRSeries>\n";

	if (BodyPartExamined) {
		stream << "\t\t";
		BodyPartExamined->put(stream);
	}
	else
		stream << "\t\tElement <BodyPartExamined> not present\n";

	if (ViewPosition) {
		stream << "\t\t";
		ViewPosition->put(stream);
	}
	else
		stream << "\t\tElement <ViewPosition> not present\n";

	if (FilterType) {
		stream << "\t\t";
		FilterType->put(stream);
	}
	else
		stream << "\t\tElement <FilterType> not present\n";

	if (CollimatorGridName) {
		stream << "\t\t";
		CollimatorGridName->put(stream);
	}
	else
		stream << "\t\tElement <CollimatorGridName> not present\n";

	if (FocalSpot) {
		stream << "\t\t";
		FocalSpot->put(stream);
	}
	else
		stream << "\t\tElement <FocalSpot> not present\n";

	if (PlateType) {
		stream << "\t\t";
		PlateType->put(stream);
	}
	else
		stream << "\t\tElement <PlateType> not present\n";

	if (PhosphorType) {
		stream << "\t\t";
		PhosphorType->put(stream);
	}
	else
		stream << "\t\tElement <PhosphorType> not present\n";

}

void
DC3Module_CRImage::Put(ostream& stream)
{
	stream << "\tModule <CRImage>\n";

	if (KVP) {
		stream << "\t\t";
		KVP->put(stream);
	}
	else
		stream << "\t\tElement <KVP> not present\n";

	if (PlateID) {
		stream << "\t\t";
		PlateID->put(stream);
	}
	else
		stream << "\t\tElement <PlateID> not present\n";

	if (DistanceSourceToDetector) {
		stream << "\t\t";
		DistanceSourceToDetector->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToDetector> not present\n";

	if (DistanceSourceToPatient) {
		stream << "\t\t";
		DistanceSourceToPatient->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToPatient> not present\n";

	if (ExposureTime) {
		stream << "\t\t";
		ExposureTime->put(stream);
	}
	else
		stream << "\t\tElement <ExposureTime> not present\n";

	if (XrayTubeCurrent) {
		stream << "\t\t";
		XrayTubeCurrent->put(stream);
	}
	else
		stream << "\t\tElement <XrayTubeCurrent> not present\n";

	if (Exposure) {
		stream << "\t\t";
		Exposure->put(stream);
	}
	else
		stream << "\t\tElement <Exposure> not present\n";

	if (GeneratorPower) {
		stream << "\t\t";
		GeneratorPower->put(stream);
	}
	else
		stream << "\t\tElement <GeneratorPower> not present\n";

	if (AcquisitionDeviceProcessingDescription) {
		stream << "\t\t";
		AcquisitionDeviceProcessingDescription->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionDeviceProcessingDescription> not present\n";

	if (AcquisitionDeviceProcessingCode) {
		stream << "\t\t";
		AcquisitionDeviceProcessingCode->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionDeviceProcessingCode> not present\n";

	if (CassetteOrientation) {
		stream << "\t\t";
		CassetteOrientation->put(stream);
	}
	else
		stream << "\t\tElement <CassetteOrientation> not present\n";

	if (CassetteSize) {
		stream << "\t\t";
		CassetteSize->put(stream);
	}
	else
		stream << "\t\tElement <CassetteSize> not present\n";

	if (ExposuresOnPlate) {
		stream << "\t\t";
		ExposuresOnPlate->put(stream);
	}
	else
		stream << "\t\tElement <ExposuresOnPlate> not present\n";

	if (RelativeXrayExposure) {
		stream << "\t\t";
		RelativeXrayExposure->put(stream);
	}
	else
		stream << "\t\tElement <RelativeXrayExposure> not present\n";

	if (Sensitivity) {
		stream << "\t\t";
		Sensitivity->put(stream);
	}
	else
		stream << "\t\tElement <Sensitivity> not present\n";

}

void
DC3Module_CTImage::Put(ostream& stream)
{
	stream << "\tModule <CTImage>\n";

	if (ImageType) {
		stream << "\t\t";
		ImageType->put(stream);
	}
	else
		stream << "\t\tElement <ImageType> not present\n";

	if (SamplesPerPixel) {
		stream << "\t\t";
		SamplesPerPixel->put(stream);
	}
	else
		stream << "\t\tElement <SamplesPerPixel> not present\n";

	if (PhotometricInterpretation) {
		stream << "\t\t";
		PhotometricInterpretation->put(stream);
	}
	else
		stream << "\t\tElement <PhotometricInterpretation> not present\n";

	if (BitsAllocated) {
		stream << "\t\t";
		BitsAllocated->put(stream);
	}
	else
		stream << "\t\tElement <BitsAllocated> not present\n";

	if (BitsStored) {
		stream << "\t\t";
		BitsStored->put(stream);
	}
	else
		stream << "\t\tElement <BitsStored> not present\n";

	if (HighBit) {
		stream << "\t\t";
		HighBit->put(stream);
	}
	else
		stream << "\t\tElement <HighBit> not present\n";

	if (RescaleIntercept) {
		stream << "\t\t";
		RescaleIntercept->put(stream);
	}
	else
		stream << "\t\tElement <RescaleIntercept> not present\n";

	if (RescaleSlope) {
		stream << "\t\t";
		RescaleSlope->put(stream);
	}
	else
		stream << "\t\tElement <RescaleSlope> not present\n";

	if (KVP) {
		stream << "\t\t";
		KVP->put(stream);
	}
	else
		stream << "\t\tElement <KVP> not present\n";

	if (AcquisitionNumber) {
		stream << "\t\t";
		AcquisitionNumber->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionNumber> not present\n";

	if (ScanOptions) {
		stream << "\t\t";
		ScanOptions->put(stream);
	}
	else
		stream << "\t\tElement <ScanOptions> not present\n";

	if (DataCollectionDiameter) {
		stream << "\t\t";
		DataCollectionDiameter->put(stream);
	}
	else
		stream << "\t\tElement <DataCollectionDiameter> not present\n";

	if (DistanceSourceToDetector) {
		stream << "\t\t";
		DistanceSourceToDetector->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToDetector> not present\n";

	if (DistanceSourceToPatient) {
		stream << "\t\t";
		DistanceSourceToPatient->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToPatient> not present\n";

	if (GantryDetectorTilt) {
		stream << "\t\t";
		GantryDetectorTilt->put(stream);
	}
	else
		stream << "\t\tElement <GantryDetectorTilt> not present\n";

	if (TableHeight) {
		stream << "\t\t";
		TableHeight->put(stream);
	}
	else
		stream << "\t\tElement <TableHeight> not present\n";

	if (RotationDirection) {
		stream << "\t\t";
		RotationDirection->put(stream);
	}
	else
		stream << "\t\tElement <RotationDirection> not present\n";

	if (ExposureTime) {
		stream << "\t\t";
		ExposureTime->put(stream);
	}
	else
		stream << "\t\tElement <ExposureTime> not present\n";

	if (XrayTubeCurrent) {
		stream << "\t\t";
		XrayTubeCurrent->put(stream);
	}
	else
		stream << "\t\tElement <XrayTubeCurrent> not present\n";

	if (Exposure) {
		stream << "\t\t";
		Exposure->put(stream);
	}
	else
		stream << "\t\tElement <Exposure> not present\n";

	if (FilterType) {
		stream << "\t\t";
		FilterType->put(stream);
	}
	else
		stream << "\t\tElement <FilterType> not present\n";

	if (GeneratorPower) {
		stream << "\t\t";
		GeneratorPower->put(stream);
	}
	else
		stream << "\t\tElement <GeneratorPower> not present\n";

	if (FocalSpot) {
		stream << "\t\t";
		FocalSpot->put(stream);
	}
	else
		stream << "\t\tElement <FocalSpot> not present\n";

	if (ConvolutionKernel) {
		stream << "\t\t";
		ConvolutionKernel->put(stream);
	}
	else
		stream << "\t\tElement <ConvolutionKernel> not present\n";

}

void
DC3Module_MRImage::Put(ostream& stream)
{
	stream << "\tModule <MRImage>\n";

	if (ImageType) {
		stream << "\t\t";
		ImageType->put(stream);
	}
	else
		stream << "\t\tElement <ImageType> not present\n";

	if (SamplesPerPixel) {
		stream << "\t\t";
		SamplesPerPixel->put(stream);
	}
	else
		stream << "\t\tElement <SamplesPerPixel> not present\n";

	if (PhotometricInterpretation) {
		stream << "\t\t";
		PhotometricInterpretation->put(stream);
	}
	else
		stream << "\t\tElement <PhotometricInterpretation> not present\n";

	if (BitsAllocated) {
		stream << "\t\t";
		BitsAllocated->put(stream);
	}
	else
		stream << "\t\tElement <BitsAllocated> not present\n";

	if (ScanningSequence) {
		stream << "\t\t";
		ScanningSequence->put(stream);
	}
	else
		stream << "\t\tElement <ScanningSequence> not present\n";

	if (SequenceVariant) {
		stream << "\t\t";
		SequenceVariant->put(stream);
	}
	else
		stream << "\t\tElement <SequenceVariant> not present\n";

	if (ScanOptions) {
		stream << "\t\t";
		ScanOptions->put(stream);
	}
	else
		stream << "\t\tElement <ScanOptions> not present\n";

	if (MRAcquisitionType) {
		stream << "\t\t";
		MRAcquisitionType->put(stream);
	}
	else
		stream << "\t\tElement <MRAcquisitionType> not present\n";

	if (RepetitionTime) {
		stream << "\t\t";
		RepetitionTime->put(stream);
	}
	else
		stream << "\t\tElement <RepetitionTime> not present\n";

	if (EchoTime) {
		stream << "\t\t";
		EchoTime->put(stream);
	}
	else
		stream << "\t\tElement <EchoTime> not present\n";

	if (EchoTrainLength) {
		stream << "\t\t";
		EchoTrainLength->put(stream);
	}
	else
		stream << "\t\tElement <EchoTrainLength> not present\n";

	if (InversionTime) {
		stream << "\t\t";
		InversionTime->put(stream);
	}
	else
		stream << "\t\tElement <InversionTime> not present\n";

	if (TriggerTime) {
		stream << "\t\t";
		TriggerTime->put(stream);
	}
	else
		stream << "\t\tElement <TriggerTime> not present\n";

	if (SequenceName) {
		stream << "\t\t";
		SequenceName->put(stream);
	}
	else
		stream << "\t\tElement <SequenceName> not present\n";

	if (AngioFlag) {
		stream << "\t\t";
		AngioFlag->put(stream);
	}
	else
		stream << "\t\tElement <AngioFlag> not present\n";

	if (NumberOfAverages) {
		stream << "\t\t";
		NumberOfAverages->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfAverages> not present\n";

	if (ImagingFrequency) {
		stream << "\t\t";
		ImagingFrequency->put(stream);
	}
	else
		stream << "\t\tElement <ImagingFrequency> not present\n";

	if (ImagedNucleus) {
		stream << "\t\t";
		ImagedNucleus->put(stream);
	}
	else
		stream << "\t\tElement <ImagedNucleus> not present\n";

	if (EchoNumber) {
		stream << "\t\t";
		EchoNumber->put(stream);
	}
	else
		stream << "\t\tElement <EchoNumber> not present\n";

	if (MagneticFieldStrength) {
		stream << "\t\t";
		MagneticFieldStrength->put(stream);
	}
	else
		stream << "\t\tElement <MagneticFieldStrength> not present\n";

	if (SpacingBetweenSlices) {
		stream << "\t\t";
		SpacingBetweenSlices->put(stream);
	}
	else
		stream << "\t\tElement <SpacingBetweenSlices> not present\n";

	if (NumberOfPhaseEncodingSteps) {
		stream << "\t\t";
		NumberOfPhaseEncodingSteps->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfPhaseEncodingSteps> not present\n";

	if (PercentSampling) {
		stream << "\t\t";
		PercentSampling->put(stream);
	}
	else
		stream << "\t\tElement <PercentSampling> not present\n";

	if (PercentPhaseFieldOfView) {
		stream << "\t\t";
		PercentPhaseFieldOfView->put(stream);
	}
	else
		stream << "\t\tElement <PercentPhaseFieldOfView> not present\n";

	if (PixelBandwidth) {
		stream << "\t\t";
		PixelBandwidth->put(stream);
	}
	else
		stream << "\t\tElement <PixelBandwidth> not present\n";

	if (NominalInterval) {
		stream << "\t\t";
		NominalInterval->put(stream);
	}
	else
		stream << "\t\tElement <NominalInterval> not present\n";

	if (BeatRejectionFlag) {
		stream << "\t\t";
		BeatRejectionFlag->put(stream);
	}
	else
		stream << "\t\tElement <BeatRejectionFlag> not present\n";

	if (LowRRValue) {
		stream << "\t\t";
		LowRRValue->put(stream);
	}
	else
		stream << "\t\tElement <LowRRValue> not present\n";

	if (HighRRValue) {
		stream << "\t\t";
		HighRRValue->put(stream);
	}
	else
		stream << "\t\tElement <HighRRValue> not present\n";

	if (IntervalsAcquired) {
		stream << "\t\t";
		IntervalsAcquired->put(stream);
	}
	else
		stream << "\t\tElement <IntervalsAcquired> not present\n";

	if (IntervalsRejected) {
		stream << "\t\t";
		IntervalsRejected->put(stream);
	}
	else
		stream << "\t\tElement <IntervalsRejected> not present\n";

	if (PVCRejection) {
		stream << "\t\t";
		PVCRejection->put(stream);
	}
	else
		stream << "\t\tElement <PVCRejection> not present\n";

	if (SkipBeats) {
		stream << "\t\t";
		SkipBeats->put(stream);
	}
	else
		stream << "\t\tElement <SkipBeats> not present\n";

	if (HeartRate) {
		stream << "\t\t";
		HeartRate->put(stream);
	}
	else
		stream << "\t\tElement <HeartRate> not present\n";

	if (CardiacNumberOfImages) {
		stream << "\t\t";
		CardiacNumberOfImages->put(stream);
	}
	else
		stream << "\t\tElement <CardiacNumberOfImages> not present\n";

	if (TriggerWindow) {
		stream << "\t\t";
		TriggerWindow->put(stream);
	}
	else
		stream << "\t\tElement <TriggerWindow> not present\n";

	if (ReconstructionDiameter) {
		stream << "\t\t";
		ReconstructionDiameter->put(stream);
	}
	else
		stream << "\t\tElement <ReconstructionDiameter> not present\n";

	if (ReceivingCoil) {
		stream << "\t\t";
		ReceivingCoil->put(stream);
	}
	else
		stream << "\t\tElement <ReceivingCoil> not present\n";

	if (TransmittingCoil) {
		stream << "\t\t";
		TransmittingCoil->put(stream);
	}
	else
		stream << "\t\tElement <TransmittingCoil> not present\n";

	if (AcquisitionMatrix) {
		stream << "\t\t";
		AcquisitionMatrix->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionMatrix> not present\n";

	if (PhaseEncodingDirection) {
		stream << "\t\t";
		PhaseEncodingDirection->put(stream);
	}
	else
		stream << "\t\tElement <PhaseEncodingDirection> not present\n";

	if (FlipAngle) {
		stream << "\t\t";
		FlipAngle->put(stream);
	}
	else
		stream << "\t\tElement <FlipAngle> not present\n";

	if (SAR) {
		stream << "\t\t";
		SAR->put(stream);
	}
	else
		stream << "\t\tElement <SAR> not present\n";

	if (VariableFlipAngleFlag) {
		stream << "\t\t";
		VariableFlipAngleFlag->put(stream);
	}
	else
		stream << "\t\tElement <VariableFlipAngleFlag> not present\n";

	if (dBdt) {
		stream << "\t\t";
		dBdt->put(stream);
	}
	else
		stream << "\t\tElement <dBdt> not present\n";

	if (TemporalPositionIdentifier) {
		stream << "\t\t";
		TemporalPositionIdentifier->put(stream);
	}
	else
		stream << "\t\tElement <TemporalPositionIdentifier> not present\n";

	if (NumberOfTemporalPositions) {
		stream << "\t\t";
		NumberOfTemporalPositions->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfTemporalPositions> not present\n";

	if (TemporalResolution) {
		stream << "\t\t";
		TemporalResolution->put(stream);
	}
	else
		stream << "\t\tElement <TemporalResolution> not present\n";

}

void
DC3Module_NMSeries::Put(ostream& stream)
{
	stream << "\tModule <NMSeries>\n";

	if (Radionuclide) {
		stream << "\t\t";
		Radionuclide->put(stream);
	}
	else
		stream << "\t\tElement <Radionuclide> not present\n";

	if (NuclearMedicineSeriesType) {
		stream << "\t\t";
		NuclearMedicineSeriesType->put(stream);
	}
	else
		stream << "\t\tElement <NuclearMedicineSeriesType> not present\n";

	if (ScanVelocity) {
		stream << "\t\t";
		ScanVelocity->put(stream);
	}
	else
		stream << "\t\tElement <ScanVelocity> not present\n";

	if (WholeBodyTechnique) {
		stream << "\t\t";
		WholeBodyTechnique->put(stream);
	}
	else
		stream << "\t\tElement <WholeBodyTechnique> not present\n";

	if (ScanLength) {
		stream << "\t\t";
		ScanLength->put(stream);
	}
	else
		stream << "\t\tElement <ScanLength> not present\n";

	if (Radiopharmaceutical) {
		stream << "\t\t";
		Radiopharmaceutical->put(stream);
	}
	else
		stream << "\t\tElement <Radiopharmaceutical> not present\n";

	if (EnergyWindowCenterline) {
		stream << "\t\t";
		EnergyWindowCenterline->put(stream);
	}
	else
		stream << "\t\tElement <EnergyWindowCenterline> not present\n";

	if (EnergyWindowTotalWidth) {
		stream << "\t\t";
		EnergyWindowTotalWidth->put(stream);
	}
	else
		stream << "\t\tElement <EnergyWindowTotalWidth> not present\n";

	if (InterventionalDrugName) {
		stream << "\t\t";
		InterventionalDrugName->put(stream);
	}
	else
		stream << "\t\tElement <InterventionalDrugName> not present\n";

	if (InterventionalDrugStartTime) {
		stream << "\t\t";
		InterventionalDrugStartTime->put(stream);
	}
	else
		stream << "\t\tElement <InterventionalDrugStartTime> not present\n";

	if (EffectiveSeriesDuration) {
		stream << "\t\t";
		EffectiveSeriesDuration->put(stream);
	}
	else
		stream << "\t\tElement <EffectiveSeriesDuration> not present\n";

	if (SyringeCounts) {
		stream << "\t\t";
		SyringeCounts->put(stream);
	}
	else
		stream << "\t\tElement <SyringeCounts> not present\n";

	if (TriggerSourceOrType) {
		stream << "\t\t";
		TriggerSourceOrType->put(stream);
	}
	else
		stream << "\t\tElement <TriggerSourceOrType> not present\n";

	if (RadionuclideRoute) {
		stream << "\t\t";
		RadionuclideRoute->put(stream);
	}
	else
		stream << "\t\tElement <RadionuclideRoute> not present\n";

	if (RadionuclideVolume) {
		stream << "\t\t";
		RadionuclideVolume->put(stream);
	}
	else
		stream << "\t\tElement <RadionuclideVolume> not present\n";

	if (RadionuclideStartTime) {
		stream << "\t\t";
		RadionuclideStartTime->put(stream);
	}
	else
		stream << "\t\tElement <RadionuclideStartTime> not present\n";

	if (RadionuclideStopTime) {
		stream << "\t\t";
		RadionuclideStopTime->put(stream);
	}
	else
		stream << "\t\tElement <RadionuclideStopTime> not present\n";

	if (RadionuclideTotalDose) {
		stream << "\t\t";
		RadionuclideTotalDose->put(stream);
	}
	else
		stream << "\t\tElement <RadionuclideTotalDose> not present\n";

	if (GantryDetectorTilt) {
		stream << "\t\t";
		GantryDetectorTilt->put(stream);
	}
	else
		stream << "\t\tElement <GantryDetectorTilt> not present\n";

	if (IsotopeNumber) {
		stream << "\t\t";
		IsotopeNumber->put(stream);
	}
	else
		stream << "\t\tElement <IsotopeNumber> not present\n";

}

void
DC3Module_NMEquipment::Put(ostream& stream)
{
	stream << "\tModule <NMEquipment>\n";

	if (CenterOfRotationOffset) {
		stream << "\t\t";
		CenterOfRotationOffset->put(stream);
	}
	else
		stream << "\t\tElement <CenterOfRotationOffset> not present\n";

	if (FieldOfViewShape) {
		stream << "\t\t";
		FieldOfViewShape->put(stream);
	}
	else
		stream << "\t\tElement <FieldOfViewShape> not present\n";

	if (FieldOfViewDimension) {
		stream << "\t\t";
		FieldOfViewDimension->put(stream);
	}
	else
		stream << "\t\tElement <FieldOfViewDimension> not present\n";

	if (CollimatorGridName) {
		stream << "\t\t";
		CollimatorGridName->put(stream);
	}
	else
		stream << "\t\tElement <CollimatorGridName> not present\n";

	if (CollimatorType) {
		stream << "\t\t";
		CollimatorType->put(stream);
	}
	else
		stream << "\t\tElement <CollimatorType> not present\n";

	if (FocalDistance) {
		stream << "\t\t";
		FocalDistance->put(stream);
	}
	else
		stream << "\t\tElement <FocalDistance> not present\n";

	if (XFocusCenter) {
		stream << "\t\t";
		XFocusCenter->put(stream);
	}
	else
		stream << "\t\tElement <XFocusCenter> not present\n";

	if (YFocusCenter) {
		stream << "\t\t";
		YFocusCenter->put(stream);
	}
	else
		stream << "\t\tElement <YFocusCenter> not present\n";

}

void
DC3Module_NMImage::Put(ostream& stream)
{
	stream << "\tModule <NMImage>\n";

	if (FrameIncrementPointer) {
		stream << "\t\t";
		FrameIncrementPointer->put(stream);
	}
	else
		stream << "\t\tElement <FrameIncrementPointer> not present\n";

	if (ZoomFactor) {
		stream << "\t\t";
		ZoomFactor->put(stream);
	}
	else
		stream << "\t\tElement <ZoomFactor> not present\n";

	if (CountsAccumulated) {
		stream << "\t\t";
		CountsAccumulated->put(stream);
	}
	else
		stream << "\t\tElement <CountsAccumulated> not present\n";

	if (AcquisitionTerminationCondition) {
		stream << "\t\t";
		AcquisitionTerminationCondition->put(stream);
	}
	else
		stream << "\t\tElement <AcquisitionTerminationCondition> not present\n";

	if (ReconstructionDiameter) {
		stream << "\t\t";
		ReconstructionDiameter->put(stream);
	}
	else
		stream << "\t\tElement <ReconstructionDiameter> not present\n";

	if (DistanceSourceToDetector) {
		stream << "\t\t";
		DistanceSourceToDetector->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToDetector> not present\n";

	if (TableHeight) {
		stream << "\t\t";
		TableHeight->put(stream);
	}
	else
		stream << "\t\tElement <TableHeight> not present\n";

	if (TableTraverse) {
		stream << "\t\t";
		TableTraverse->put(stream);
	}
	else
		stream << "\t\tElement <TableTraverse> not present\n";

	if (AngularPosition) {
		stream << "\t\t";
		AngularPosition->put(stream);
	}
	else
		stream << "\t\tElement <AngularPosition> not present\n";

	if (RadialPosition) {
		stream << "\t\t";
		RadialPosition->put(stream);
	}
	else
		stream << "\t\tElement <RadialPosition> not present\n";

	if (ConvolutionKernel) {
		stream << "\t\t";
		ConvolutionKernel->put(stream);
	}
	else
		stream << "\t\tElement <ConvolutionKernel> not present\n";

	if (ActualFrameDuration) {
		stream << "\t\t";
		ActualFrameDuration->put(stream);
	}
	else
		stream << "\t\tElement <ActualFrameDuration> not present\n";

	if (CountRate) {
		stream << "\t\t";
		CountRate->put(stream);
	}
	else
		stream << "\t\tElement <CountRate> not present\n";

	if (PreprocessingFunction) {
		stream << "\t\t";
		PreprocessingFunction->put(stream);
	}
	else
		stream << "\t\tElement <PreprocessingFunction> not present\n";

	if (PostprocessingFunction) {
		stream << "\t\t";
		PostprocessingFunction->put(stream);
	}
	else
		stream << "\t\tElement <PostprocessingFunction> not present\n";

	if (PhaseNumber) {
		stream << "\t\t";
		PhaseNumber->put(stream);
	}
	else
		stream << "\t\tElement <PhaseNumber> not present\n";

	if (IntervalNumber) {
		stream << "\t\t";
		IntervalNumber->put(stream);
	}
	else
		stream << "\t\tElement <IntervalNumber> not present\n";

	if (TimeSlotNumber) {
		stream << "\t\t";
		TimeSlotNumber->put(stream);
	}
	else
		stream << "\t\tElement <TimeSlotNumber> not present\n";

	if (AngleNumber) {
		stream << "\t\t";
		AngleNumber->put(stream);
	}
	else
		stream << "\t\tElement <AngleNumber> not present\n";

	if (ZoomCenter) {
		stream << "\t\t";
		ZoomCenter->put(stream);
	}
	else
		stream << "\t\tElement <ZoomCenter> not present\n";

	if (CorrectedImage) {
		stream << "\t\t";
		CorrectedImage->put(stream);
	}
	else
		stream << "\t\tElement <CorrectedImage> not present\n";

}

void
DC3Module_NMSPECTAcquisitionImage::Put(ostream& stream)
{
	stream << "\tModule <NMSPECTAcquisitionImage>\n";

	if (FrameIncrementPointer) {
		stream << "\t\t";
		FrameIncrementPointer->put(stream);
	}
	else
		stream << "\t\tElement <FrameIncrementPointer> not present\n";

	if (AngularStep) {
		stream << "\t\t";
		AngularStep->put(stream);
	}
	else
		stream << "\t\tElement <AngularStep> not present\n";

	if (ZoomFactor) {
		stream << "\t\t";
		ZoomFactor->put(stream);
	}
	else
		stream << "\t\tElement <ZoomFactor> not present\n";

	if (ScanArc) {
		stream << "\t\t";
		ScanArc->put(stream);
	}
	else
		stream << "\t\tElement <ScanArc> not present\n";

	if (ReconstructionDiameter) {
		stream << "\t\t";
		ReconstructionDiameter->put(stream);
	}
	else
		stream << "\t\tElement <ReconstructionDiameter> not present\n";

	if (DistanceSourceToDetector) {
		stream << "\t\t";
		DistanceSourceToDetector->put(stream);
	}
	else
		stream << "\t\tElement <DistanceSourceToDetector> not present\n";

	if (TableHeight) {
		stream << "\t\t";
		TableHeight->put(stream);
	}
	else
		stream << "\t\tElement <TableHeight> not present\n";

	if (TableTraverse) {
		stream << "\t\t";
		TableTraverse->put(stream);
	}
	else
		stream << "\t\tElement <TableTraverse> not present\n";

	if (RotationDirection) {
		stream << "\t\t";
		RotationDirection->put(stream);
	}
	else
		stream << "\t\tElement <RotationDirection> not present\n";

	if (AngularPosition) {
		stream << "\t\t";
		AngularPosition->put(stream);
	}
	else
		stream << "\t\tElement <AngularPosition> not present\n";

	if (RadialPosition) {
		stream << "\t\t";
		RadialPosition->put(stream);
	}
	else
		stream << "\t\tElement <RadialPosition> not present\n";

	if (RotationOffset) {
		stream << "\t\t";
		RotationOffset->put(stream);
	}
	else
		stream << "\t\tElement <RotationOffset> not present\n";

	if (AngleNumber) {
		stream << "\t\t";
		AngleNumber->put(stream);
	}
	else
		stream << "\t\tElement <AngleNumber> not present\n";

	if (ZoomCenter) {
		stream << "\t\t";
		ZoomCenter->put(stream);
	}
	else
		stream << "\t\tElement <ZoomCenter> not present\n";

}

void
DC3Module_NMMultiGatedAcquisitionImage::Put(ostream& stream)
{
	stream << "\tModule <NMMultiGatedAcquisitionImage>\n";

	if (FrameIncrementPointer) {
		stream << "\t\t";
		FrameIncrementPointer->put(stream);
	}
	else
		stream << "\t\tElement <FrameIncrementPointer> not present\n";

	if (TriggerSourceOrType) {
		stream << "\t\t";
		TriggerSourceOrType->put(stream);
	}
	else
		stream << "\t\tElement <TriggerSourceOrType> not present\n";

	if (FrameTime) {
		stream << "\t\t";
		FrameTime->put(stream);
	}
	else
		stream << "\t\tElement <FrameTime> not present\n";

	if (TriggerTime) {
		stream << "\t\t";
		TriggerTime->put(stream);
	}
	else
		stream << "\t\tElement <TriggerTime> not present\n";

	if (NominalInterval) {
		stream << "\t\t";
		NominalInterval->put(stream);
	}
	else
		stream << "\t\tElement <NominalInterval> not present\n";

	if (FramingType) {
		stream << "\t\t";
		FramingType->put(stream);
	}
	else
		stream << "\t\tElement <FramingType> not present\n";

	if (BeatRejectionFlag) {
		stream << "\t\t";
		BeatRejectionFlag->put(stream);
	}
	else
		stream << "\t\tElement <BeatRejectionFlag> not present\n";

	if (LowRRValue) {
		stream << "\t\t";
		LowRRValue->put(stream);
	}
	else
		stream << "\t\tElement <LowRRValue> not present\n";

	if (HighRRValue) {
		stream << "\t\t";
		HighRRValue->put(stream);
	}
	else
		stream << "\t\tElement <HighRRValue> not present\n";

	if (IntervalsAcquired) {
		stream << "\t\t";
		IntervalsAcquired->put(stream);
	}
	else
		stream << "\t\tElement <IntervalsAcquired> not present\n";

	if (IntervalsRejected) {
		stream << "\t\t";
		IntervalsRejected->put(stream);
	}
	else
		stream << "\t\tElement <IntervalsRejected> not present\n";

	if (PVCRejection) {
		stream << "\t\t";
		PVCRejection->put(stream);
	}
	else
		stream << "\t\tElement <PVCRejection> not present\n";

	if (SkipBeats) {
		stream << "\t\t";
		SkipBeats->put(stream);
	}
	else
		stream << "\t\tElement <SkipBeats> not present\n";

	if (HeartRate) {
		stream << "\t\t";
		HeartRate->put(stream);
	}
	else
		stream << "\t\tElement <HeartRate> not present\n";

	if (CardiacNumberOfImages) {
		stream << "\t\t";
		CardiacNumberOfImages->put(stream);
	}
	else
		stream << "\t\tElement <CardiacNumberOfImages> not present\n";

}

void
DC3Module_USFrameOfReference::Put(ostream& stream)
{
	stream << "\tModule <USFrameOfReference>\n";

	if (RegionLocationMinX0) {
		stream << "\t\t";
		RegionLocationMinX0->put(stream);
	}
	else
		stream << "\t\tElement <RegionLocationMinX0> not present\n";

	if (RegionLocationMinY0) {
		stream << "\t\t";
		RegionLocationMinY0->put(stream);
	}
	else
		stream << "\t\tElement <RegionLocationMinY0> not present\n";

	if (RegionLocationMaxX1) {
		stream << "\t\t";
		RegionLocationMaxX1->put(stream);
	}
	else
		stream << "\t\tElement <RegionLocationMaxX1> not present\n";

	if (RegionLocationMaxY1) {
		stream << "\t\t";
		RegionLocationMaxY1->put(stream);
	}
	else
		stream << "\t\tElement <RegionLocationMaxY1> not present\n";

	if (PhysicalUnitsXDirection) {
		stream << "\t\t";
		PhysicalUnitsXDirection->put(stream);
	}
	else
		stream << "\t\tElement <PhysicalUnitsXDirection> not present\n";

	if (PhysicalUnitsYDirection) {
		stream << "\t\t";
		PhysicalUnitsYDirection->put(stream);
	}
	else
		stream << "\t\tElement <PhysicalUnitsYDirection> not present\n";

	if (PhysicalDeltaX) {
		stream << "\t\t";
		PhysicalDeltaX->put(stream);
	}
	else
		stream << "\t\tElement <PhysicalDeltaX> not present\n";

	if (PhysicalDeltaY) {
		stream << "\t\t";
		PhysicalDeltaY->put(stream);
	}
	else
		stream << "\t\tElement <PhysicalDeltaY> not present\n";

	if (ReferencePixelX0) {
		stream << "\t\t";
		ReferencePixelX0->put(stream);
	}
	else
		stream << "\t\tElement <ReferencePixelX0> not present\n";

	if (ReferencePixelY0) {
		stream << "\t\t";
		ReferencePixelY0->put(stream);
	}
	else
		stream << "\t\tElement <ReferencePixelY0> not present\n";

	if (ReferencePixelPhysicalValueX) {
		stream << "\t\t";
		ReferencePixelPhysicalValueX->put(stream);
	}
	else
		stream << "\t\tElement <ReferencePixelPhysicalValueX> not present\n";

	if (ReferencePixelPhysicalValueY) {
		stream << "\t\t";
		ReferencePixelPhysicalValueY->put(stream);
	}
	else
		stream << "\t\tElement <ReferencePixelPhysicalValueY> not present\n";

}

void
DC3Module_USRegionCalibration::Put(ostream& stream)
{
	stream << "\tModule <USRegionCalibration>\n";

}

void
DC3Module_USImage::Put(ostream& stream)
{
	stream << "\tModule <USImage>\n";

	if (PhotometricInterpretation) {
		stream << "\t\t";
		PhotometricInterpretation->put(stream);
	}
	else
		stream << "\t\tElement <PhotometricInterpretation> not present\n";

	if (PixelRepresentation) {
		stream << "\t\t";
		PixelRepresentation->put(stream);
	}
	else
		stream << "\t\tElement <PixelRepresentation> not present\n";

	if (FrameIncrementPointer) {
		stream << "\t\t";
		FrameIncrementPointer->put(stream);
	}
	else
		stream << "\t\tElement <FrameIncrementPointer> not present\n";

	if (ImageType) {
		stream << "\t\t";
		ImageType->put(stream);
	}
	else
		stream << "\t\tElement <ImageType> not present\n";

	if (NumberOfStages) {
		stream << "\t\t";
		NumberOfStages->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfStages> not present\n";

	if (NumberOfViewsInStage) {
		stream << "\t\t";
		NumberOfViewsInStage->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfViewsInStage> not present\n";

	if (StageName) {
		stream << "\t\t";
		StageName->put(stream);
	}
	else
		stream << "\t\tElement <StageName> not present\n";

	if (StageNumber) {
		stream << "\t\t";
		StageNumber->put(stream);
	}
	else
		stream << "\t\tElement <StageNumber> not present\n";

	if (ViewNumber) {
		stream << "\t\t";
		ViewNumber->put(stream);
	}
	else
		stream << "\t\tElement <ViewNumber> not present\n";

	if (NumberOfEventTimers) {
		stream << "\t\t";
		NumberOfEventTimers->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfEventTimers> not present\n";

	if (EventElapsedTime) {
		stream << "\t\t";
		EventElapsedTime->put(stream);
	}
	else
		stream << "\t\tElement <EventElapsedTime> not present\n";

	if (EventTimerName) {
		stream << "\t\t";
		EventTimerName->put(stream);
	}
	else
		stream << "\t\tElement <EventTimerName> not present\n";

	if (TransducerPosition) {
		stream << "\t\t";
		TransducerPosition->put(stream);
	}
	else
		stream << "\t\tElement <TransducerPosition> not present\n";

	if (TransducerOrientation) {
		stream << "\t\t";
		TransducerOrientation->put(stream);
	}
	else
		stream << "\t\tElement <TransducerOrientation> not present\n";

	if (AnatomicStructure) {
		stream << "\t\t";
		AnatomicStructure->put(stream);
	}
	else
		stream << "\t\tElement <AnatomicStructure> not present\n";

	if (TriggerTime) {
		stream << "\t\t";
		TriggerTime->put(stream);
	}
	else
		stream << "\t\tElement <TriggerTime> not present\n";

	if (NominalInterval) {
		stream << "\t\t";
		NominalInterval->put(stream);
	}
	else
		stream << "\t\tElement <NominalInterval> not present\n";

	if (BeatRejectionFlag) {
		stream << "\t\t";
		BeatRejectionFlag->put(stream);
	}
	else
		stream << "\t\tElement <BeatRejectionFlag> not present\n";

	if (LowRRValue) {
		stream << "\t\t";
		LowRRValue->put(stream);
	}
	else
		stream << "\t\tElement <LowRRValue> not present\n";

	if (HighRRValue) {
		stream << "\t\t";
		HighRRValue->put(stream);
	}
	else
		stream << "\t\tElement <HighRRValue> not present\n";

	if (HeartRate) {
		stream << "\t\t";
		HeartRate->put(stream);
	}
	else
		stream << "\t\tElement <HeartRate> not present\n";

	if (OutputPower) {
		stream << "\t\t";
		OutputPower->put(stream);
	}
	else
		stream << "\t\tElement <OutputPower> not present\n";

	if (TransducerData) {
		stream << "\t\t";
		TransducerData->put(stream);
	}
	else
		stream << "\t\tElement <TransducerData> not present\n";

	if (TransducerType) {
		stream << "\t\t";
		TransducerType->put(stream);
	}
	else
		stream << "\t\tElement <TransducerType> not present\n";

	if (FocusDepth) {
		stream << "\t\t";
		FocusDepth->put(stream);
	}
	else
		stream << "\t\tElement <FocusDepth> not present\n";

	if (PreprocessingFunction) {
		stream << "\t\t";
		PreprocessingFunction->put(stream);
	}
	else
		stream << "\t\tElement <PreprocessingFunction> not present\n";

	if (MechanicalIndex) {
		stream << "\t\t";
		MechanicalIndex->put(stream);
	}
	else
		stream << "\t\tElement <MechanicalIndex> not present\n";

	if (ThermalIndex) {
		stream << "\t\t";
		ThermalIndex->put(stream);
	}
	else
		stream << "\t\tElement <ThermalIndex> not present\n";

	if (CranialThermalIndex) {
		stream << "\t\t";
		CranialThermalIndex->put(stream);
	}
	else
		stream << "\t\tElement <CranialThermalIndex> not present\n";

	if (SoftTissueThermalIndex) {
		stream << "\t\t";
		SoftTissueThermalIndex->put(stream);
	}
	else
		stream << "\t\tElement <SoftTissueThermalIndex> not present\n";

	if (SoftTissueFocusThermalIndex) {
		stream << "\t\t";
		SoftTissueFocusThermalIndex->put(stream);
	}
	else
		stream << "\t\tElement <SoftTissueFocusThermalIndex> not present\n";

	if (SoftTissueSurfaceThermalIndex) {
		stream << "\t\t";
		SoftTissueSurfaceThermalIndex->put(stream);
	}
	else
		stream << "\t\tElement <SoftTissueSurfaceThermalIndex> not present\n";

	if (DepthOfScanField) {
		stream << "\t\t";
		DepthOfScanField->put(stream);
	}
	else
		stream << "\t\tElement <DepthOfScanField> not present\n";

	if (ImageTransformationMatrix) {
		stream << "\t\t";
		ImageTransformationMatrix->put(stream);
	}
	else
		stream << "\t\tElement <ImageTransformationMatrix> not present\n";

	if (ImageTranslationVector) {
		stream << "\t\t";
		ImageTranslationVector->put(stream);
	}
	else
		stream << "\t\tElement <ImageTranslationVector> not present\n";

}

void
DC3Module_SCImageEquipment::Put(ostream& stream)
{
	stream << "\tModule <SCImageEquipment>\n";

	if (ConversionType) {
		stream << "\t\t";
		ConversionType->put(stream);
	}
	else
		stream << "\t\tElement <ConversionType> not present\n";

	if (Modality) {
		stream << "\t\t";
		Modality->put(stream);
	}
	else
		stream << "\t\tElement <Modality> not present\n";

	if (SecondaryCaptureDeviceID) {
		stream << "\t\t";
		SecondaryCaptureDeviceID->put(stream);
	}
	else
		stream << "\t\tElement <SecondaryCaptureDeviceID> not present\n";

	if (SecondaryCaptureDeviceManufacturer) {
		stream << "\t\t";
		SecondaryCaptureDeviceManufacturer->put(stream);
	}
	else
		stream << "\t\tElement <SecondaryCaptureDeviceManufacturer> not present\n";

	if (SecondaryCaptureDeviceManufacturerModelName) {
		stream << "\t\t";
		SecondaryCaptureDeviceManufacturerModelName->put(stream);
	}
	else
		stream << "\t\tElement <SecondaryCaptureDeviceManufacturerModelName> not present\n";

	if (SecondaryCaptureDeviceSoftwareVersion) {
		stream << "\t\t";
		SecondaryCaptureDeviceSoftwareVersion->put(stream);
	}
	else
		stream << "\t\tElement <SecondaryCaptureDeviceSoftwareVersion> not present\n";

	if (VideoImageFormatAcquired) {
		stream << "\t\t";
		VideoImageFormatAcquired->put(stream);
	}
	else
		stream << "\t\tElement <VideoImageFormatAcquired> not present\n";

	if (DigitalImageFormatAcquired) {
		stream << "\t\t";
		DigitalImageFormatAcquired->put(stream);
	}
	else
		stream << "\t\tElement <DigitalImageFormatAcquired> not present\n";

}

void
DC3Module_SCImage::Put(ostream& stream)
{
	stream << "\tModule <SCImage>\n";

	if (DateOfSecondaryCapture) {
		stream << "\t\t";
		DateOfSecondaryCapture->put(stream);
	}
	else
		stream << "\t\tElement <DateOfSecondaryCapture> not present\n";

	if (TimeOfSecondaryCapture) {
		stream << "\t\t";
		TimeOfSecondaryCapture->put(stream);
	}
	else
		stream << "\t\tElement <TimeOfSecondaryCapture> not present\n";

}

void
DC3Module_OverlayIdentification::Put(ostream& stream)
{
	stream << "\tModule <OverlayIdentification>\n";

	if (OverlayNumber) {
		stream << "\t\t";
		OverlayNumber->put(stream);
	}
	else
		stream << "\t\tElement <OverlayNumber> not present\n";

	if (OverlayDate) {
		stream << "\t\t";
		OverlayDate->put(stream);
	}
	else
		stream << "\t\tElement <OverlayDate> not present\n";

	if (OverlayTime) {
		stream << "\t\t";
		OverlayTime->put(stream);
	}
	else
		stream << "\t\tElement <OverlayTime> not present\n";

}

void
DC3Module_OverlayPlane::Put(ostream& stream)
{
	stream << "\tModule <OverlayPlane>\n";

	if (OverlayRows) {
		stream << "\t\t";
		OverlayRows->put(stream);
	}
	else
		stream << "\t\tElement <OverlayRows> not present\n";

	if (OverlayColumns) {
		stream << "\t\t";
		OverlayColumns->put(stream);
	}
	else
		stream << "\t\tElement <OverlayColumns> not present\n";

	if (OverlayType) {
		stream << "\t\t";
		OverlayType->put(stream);
	}
	else
		stream << "\t\tElement <OverlayType> not present\n";

	if (OverlayOrigin) {
		stream << "\t\t";
		OverlayOrigin->put(stream);
	}
	else
		stream << "\t\tElement <OverlayOrigin> not present\n";

	if (OverlayBitsAllocated) {
		stream << "\t\t";
		OverlayBitsAllocated->put(stream);
	}
	else
		stream << "\t\tElement <OverlayBitsAllocated> not present\n";

	if (OverlayBitPosition) {
		stream << "\t\t";
		OverlayBitPosition->put(stream);
	}
	else
		stream << "\t\tElement <OverlayBitPosition> not present\n";

	if (OverlayData) {
		stream << "\t\t";
		OverlayData->put(stream);
	}
	else
		stream << "\t\tElement <OverlayData> not present\n";

	if (ROIArea) {
		stream << "\t\t";
		ROIArea->put(stream);
	}
	else
		stream << "\t\tElement <ROIArea> not present\n";

	if (ROIMean) {
		stream << "\t\t";
		ROIMean->put(stream);
	}
	else
		stream << "\t\tElement <ROIMean> not present\n";

	if (ROIStandardDeviation) {
		stream << "\t\t";
		ROIStandardDeviation->put(stream);
	}
	else
		stream << "\t\tElement <ROIStandardDeviation> not present\n";

	if (OverlayDescriptorGray) {
		stream << "\t\t";
		OverlayDescriptorGray->put(stream);
	}
	else
		stream << "\t\tElement <OverlayDescriptorGray> not present\n";

	if (OverlayDescriptorRed) {
		stream << "\t\t";
		OverlayDescriptorRed->put(stream);
	}
	else
		stream << "\t\tElement <OverlayDescriptorRed> not present\n";

	if (OverlayDescriptorGreen) {
		stream << "\t\t";
		OverlayDescriptorGreen->put(stream);
	}
	else
		stream << "\t\tElement <OverlayDescriptorGreen> not present\n";

	if (OverlayDescriptorBlue) {
		stream << "\t\t";
		OverlayDescriptorBlue->put(stream);
	}
	else
		stream << "\t\tElement <OverlayDescriptorBlue> not present\n";

	if (OverlayGray) {
		stream << "\t\t";
		OverlayGray->put(stream);
	}
	else
		stream << "\t\tElement <OverlayGray> not present\n";

	if (OverlayRed) {
		stream << "\t\t";
		OverlayRed->put(stream);
	}
	else
		stream << "\t\tElement <OverlayRed> not present\n";

	if (OverlayGreen) {
		stream << "\t\t";
		OverlayGreen->put(stream);
	}
	else
		stream << "\t\tElement <OverlayGreen> not present\n";

	if (OverlayBlue) {
		stream << "\t\t";
		OverlayBlue->put(stream);
	}
	else
		stream << "\t\tElement <OverlayBlue> not present\n";

}

void
DC3Module_MultiFrameOverlay::Put(ostream& stream)
{
	stream << "\tModule <MultiFrameOverlay>\n";

	if (OverlayNumberOfFrames) {
		stream << "\t\t";
		OverlayNumberOfFrames->put(stream);
	}
	else
		stream << "\t\tElement <OverlayNumberOfFrames> not present\n";

}

void
DC3Module_CurveIdentification::Put(ostream& stream)
{
	stream << "\tModule <CurveIdentification>\n";

	if (CurveNumber) {
		stream << "\t\t";
		CurveNumber->put(stream);
	}
	else
		stream << "\t\tElement <CurveNumber> not present\n";

	if (CurveDate) {
		stream << "\t\t";
		CurveDate->put(stream);
	}
	else
		stream << "\t\tElement <CurveDate> not present\n";

	if (CurveTime) {
		stream << "\t\t";
		CurveTime->put(stream);
	}
	else
		stream << "\t\tElement <CurveTime> not present\n";

}

void
DC3Module_Curve::Put(ostream& stream)
{
	stream << "\tModule <Curve>\n";

	if (CurveDimensions) {
		stream << "\t\t";
		CurveDimensions->put(stream);
	}
	else
		stream << "\t\tElement <CurveDimensions> not present\n";

	if (NumberOfPoints) {
		stream << "\t\t";
		NumberOfPoints->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfPoints> not present\n";

	if (TypeOfData) {
		stream << "\t\t";
		TypeOfData->put(stream);
	}
	else
		stream << "\t\tElement <TypeOfData> not present\n";

	if (DataValueRepresentation) {
		stream << "\t\t";
		DataValueRepresentation->put(stream);
	}
	else
		stream << "\t\tElement <DataValueRepresentation> not present\n";

	if (CurveData) {
		stream << "\t\t";
		CurveData->put(stream);
	}
	else
		stream << "\t\tElement <CurveData> not present\n";

	if (CurveDescription) {
		stream << "\t\t";
		CurveDescription->put(stream);
	}
	else
		stream << "\t\tElement <CurveDescription> not present\n";

	if (AxisUnits) {
		stream << "\t\t";
		AxisUnits->put(stream);
	}
	else
		stream << "\t\tElement <AxisUnits> not present\n";

	if (AxisLabels) {
		stream << "\t\t";
		AxisLabels->put(stream);
	}
	else
		stream << "\t\tElement <AxisLabels> not present\n";

	if (MinimumCoordinateValue) {
		stream << "\t\t";
		MinimumCoordinateValue->put(stream);
	}
	else
		stream << "\t\tElement <MinimumCoordinateValue> not present\n";

	if (MaximumCoordinateValue) {
		stream << "\t\t";
		MaximumCoordinateValue->put(stream);
	}
	else
		stream << "\t\tElement <MaximumCoordinateValue> not present\n";

	if (CurveRange) {
		stream << "\t\t";
		CurveRange->put(stream);
	}
	else
		stream << "\t\tElement <CurveRange> not present\n";

	if (CurveDataDescriptor) {
		stream << "\t\t";
		CurveDataDescriptor->put(stream);
	}
	else
		stream << "\t\tElement <CurveDataDescriptor> not present\n";

	if (CoordinateStartValue) {
		stream << "\t\t";
		CoordinateStartValue->put(stream);
	}
	else
		stream << "\t\tElement <CoordinateStartValue> not present\n";

	if (CoordinateStepValue) {
		stream << "\t\t";
		CoordinateStepValue->put(stream);
	}
	else
		stream << "\t\tElement <CoordinateStepValue> not present\n";

}

void
DC3Module_Audio::Put(ostream& stream)
{
	stream << "\tModule <Audio>\n";

	if (AudioType) {
		stream << "\t\t";
		AudioType->put(stream);
	}
	else
		stream << "\t\tElement <AudioType> not present\n";

	if (AudioSampleFormat) {
		stream << "\t\t";
		AudioSampleFormat->put(stream);
	}
	else
		stream << "\t\tElement <AudioSampleFormat> not present\n";

	if (NumberOfChannels) {
		stream << "\t\t";
		NumberOfChannels->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfChannels> not present\n";

	if (NumberOfSamples) {
		stream << "\t\t";
		NumberOfSamples->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfSamples> not present\n";

	if (SampleRate) {
		stream << "\t\t";
		SampleRate->put(stream);
	}
	else
		stream << "\t\tElement <SampleRate> not present\n";

	if (TotalTime) {
		stream << "\t\t";
		TotalTime->put(stream);
	}
	else
		stream << "\t\tElement <TotalTime> not present\n";

	if (AudioSampleData) {
		stream << "\t\t";
		AudioSampleData->put(stream);
	}
	else
		stream << "\t\tElement <AudioSampleData> not present\n";

	if (AudioComments) {
		stream << "\t\t";
		AudioComments->put(stream);
	}
	else
		stream << "\t\tElement <AudioComments> not present\n";

}

void
DC3Module_ModalityLUT::Put(ostream& stream)
{
	stream << "\tModule <ModalityLUT>\n";

	if (RescaleIntercept) {
		stream << "\t\t";
		RescaleIntercept->put(stream);
	}
	else
		stream << "\t\tElement <RescaleIntercept> not present\n";

	if (RescaleSlope) {
		stream << "\t\t";
		RescaleSlope->put(stream);
	}
	else
		stream << "\t\tElement <RescaleSlope> not present\n";

	if (RescaleType) {
		stream << "\t\t";
		RescaleType->put(stream);
	}
	else
		stream << "\t\tElement <RescaleType> not present\n";

}

void
DC3Module_VOILUT::Put(ostream& stream)
{
	stream << "\tModule <VOILUT>\n";

	if (WindowCenter) {
		stream << "\t\t";
		WindowCenter->put(stream);
	}
	else
		stream << "\t\tElement <WindowCenter> not present\n";

	if (WindowWidth) {
		stream << "\t\t";
		WindowWidth->put(stream);
	}
	else
		stream << "\t\tElement <WindowWidth> not present\n";

	if (WindowCenterWidthExplanation) {
		stream << "\t\t";
		WindowCenterWidthExplanation->put(stream);
	}
	else
		stream << "\t\tElement <WindowCenterWidthExplanation> not present\n";

}

void
DC3Module_LUTIdentification::Put(ostream& stream)
{
	stream << "\tModule <LUTIdentification>\n";

	if (LUTNumber) {
		stream << "\t\t";
		LUTNumber->put(stream);
	}
	else
		stream << "\t\tElement <LUTNumber> not present\n";

}

void
DC3Module_SOPCommon::Put(ostream& stream)
{
	stream << "\tModule <SOPCommon>\n";

	if (SOPClassUID) {
		stream << "\t\t";
		SOPClassUID->put(stream);
	}
	else
		stream << "\t\tElement <SOPClassUID> not present\n";

	if (SOPInstanceUID) {
		stream << "\t\t";
		SOPInstanceUID->put(stream);
	}
	else
		stream << "\t\tElement <SOPInstanceUID> not present\n";

	if (SpecificCharacterSet) {
		stream << "\t\t";
		SpecificCharacterSet->put(stream);
	}
	else
		stream << "\t\tElement <SpecificCharacterSet> not present\n";

	if (InstanceCreationDate) {
		stream << "\t\t";
		InstanceCreationDate->put(stream);
	}
	else
		stream << "\t\tElement <InstanceCreationDate> not present\n";

	if (InstanceCreationTime) {
		stream << "\t\t";
		InstanceCreationTime->put(stream);
	}
	else
		stream << "\t\tElement <InstanceCreationTime> not present\n";

	if (InstanceCreatorUID) {
		stream << "\t\t";
		InstanceCreatorUID->put(stream);
	}
	else
		stream << "\t\tElement <InstanceCreatorUID> not present\n";

}

void
DC3Module_BasicFilmSessionPresentation::Put(ostream& stream)
{
	stream << "\tModule <BasicFilmSessionPresentation>\n";

	if (NumberOfCopies) {
		stream << "\t\t";
		NumberOfCopies->put(stream);
	}
	else
		stream << "\t\tElement <NumberOfCopies> not present\n";

	if (PrintPriority) {
		stream << "\t\t";
		PrintPriority->put(stream);
	}
	else
		stream << "\t\tElement <PrintPriority> not present\n";

	if (MediumType) {
		stream << "\t\t";
		MediumType->put(stream);
	}
	else
		stream << "\t\tElement <MediumType> not present\n";

	if (FilmDestination) {
		stream << "\t\t";
		FilmDestination->put(stream);
	}
	else
		stream << "\t\tElement <FilmDestination> not present\n";

	if (FilmSessionLabel) {
		stream << "\t\t";
		FilmSessionLabel->put(stream);
	}
	else
		stream << "\t\tElement <FilmSessionLabel> not present\n";

	if (MemoryAllocation) {
		stream << "\t\t";
		MemoryAllocation->put(stream);
	}
	else
		stream << "\t\tElement <MemoryAllocation> not present\n";

}

void
DC3Module_BasicFilmSessionRelationship::Put(ostream& stream)
{
	stream << "\tModule <BasicFilmSessionRelationship>\n";

}

void
DC3Module_BasicFilmBoxPresentation::Put(ostream& stream)
{
	stream << "\tModule <BasicFilmBoxPresentation>\n";

	if (ImageDisplayFormat) {
		stream << "\t\t";
		ImageDisplayFormat->put(stream);
	}
	else
		stream << "\t\tElement <ImageDisplayFormat> not present\n";

	if (AnnotationDisplayFormatID) {
		stream << "\t\t";
		AnnotationDisplayFormatID->put(stream);
	}
	else
		stream << "\t\tElement <AnnotationDisplayFormatID> not present\n";

	if (FilmOrientation) {
		stream << "\t\t";
		FilmOrientation->put(stream);
	}
	else
		stream << "\t\tElement <FilmOrientation> not present\n";

	if (FilmSizeID) {
		stream << "\t\t";
		FilmSizeID->put(stream);
	}
	else
		stream << "\t\tElement <FilmSizeID> not present\n";

	if (MagnificationType) {
		stream << "\t\t";
		MagnificationType->put(stream);
	}
	else
		stream << "\t\tElement <MagnificationType> not present\n";

	if (SmoothingType) {
		stream << "\t\t";
		SmoothingType->put(stream);
	}
	else
		stream << "\t\tElement <SmoothingType> not present\n";

	if (BorderDensity) {
		stream << "\t\t";
		BorderDensity->put(stream);
	}
	else
		stream << "\t\tElement <BorderDensity> not present\n";

	if (EmptyImageDensity) {
		stream << "\t\t";
		EmptyImageDensity->put(stream);
	}
	else
		stream << "\t\tElement <EmptyImageDensity> not present\n";

	if (MinDensity) {
		stream << "\t\t";
		MinDensity->put(stream);
	}
	else
		stream << "\t\tElement <MinDensity> not present\n";

	if (MaxDensity) {
		stream << "\t\t";
		MaxDensity->put(stream);
	}
	else
		stream << "\t\tElement <MaxDensity> not present\n";

	if (Trim) {
		stream << "\t\t";
		Trim->put(stream);
	}
	else
		stream << "\t\tElement <Trim> not present\n";

	if (ConfigurationInformation) {
		stream << "\t\t";
		ConfigurationInformation->put(stream);
	}
	else
		stream << "\t\tElement <ConfigurationInformation> not present\n";

}

void
DC3Module_BasicFilmBoxRelationship::Put(ostream& stream)
{
	stream << "\tModule <BasicFilmBoxRelationship>\n";

}

void
DC3Module_ImageBoxPixelPresentation::Put(ostream& stream)
{
	stream << "\tModule <ImageBoxPixelPresentation>\n";

	if (ImagePosition) {
		stream << "\t\t";
		ImagePosition->put(stream);
	}
	else
		stream << "\t\tElement <ImagePosition> not present\n";

	if (Polarity) {
		stream << "\t\t";
		Polarity->put(stream);
	}
	else
		stream << "\t\tElement <Polarity> not present\n";

	if (MagnificationType) {
		stream << "\t\t";
		MagnificationType->put(stream);
	}
	else
		stream << "\t\tElement <MagnificationType> not present\n";

	if (SmoothingType) {
		stream << "\t\t";
		SmoothingType->put(stream);
	}
	else
		stream << "\t\tElement <SmoothingType> not present\n";

	if (RequestedImageSize) {
		stream << "\t\t";
		RequestedImageSize->put(stream);
	}
	else
		stream << "\t\tElement <RequestedImageSize> not present\n";

}

void
DC3Module_ImageBoxRelationship::Put(ostream& stream)
{
	stream << "\tModule <ImageBoxRelationship>\n";

}

void
DC3Module_BasicAnnotationPresentation::Put(ostream& stream)
{
	stream << "\tModule <BasicAnnotationPresentation>\n";

	if (AnnotationPosition) {
		stream << "\t\t";
		AnnotationPosition->put(stream);
	}
	else
		stream << "\t\tElement <AnnotationPosition> not present\n";

	if (TextString) {
		stream << "\t\t";
		TextString->put(stream);
	}
	else
		stream << "\t\tElement <TextString> not present\n";

}

void
DC3Module_PrintJob::Put(ostream& stream)
{
	stream << "\tModule <PrintJob>\n";

	if (ExecutionStatus) {
		stream << "\t\t";
		ExecutionStatus->put(stream);
	}
	else
		stream << "\t\tElement <ExecutionStatus> not present\n";

	if (ExecutionStatusInfo) {
		stream << "\t\t";
		ExecutionStatusInfo->put(stream);
	}
	else
		stream << "\t\tElement <ExecutionStatusInfo> not present\n";

	if (CreationDate) {
		stream << "\t\t";
		CreationDate->put(stream);
	}
	else
		stream << "\t\tElement <CreationDate> not present\n";

	if (CreationTime) {
		stream << "\t\t";
		CreationTime->put(stream);
	}
	else
		stream << "\t\tElement <CreationTime> not present\n";

	if (PrintPriority) {
		stream << "\t\t";
		PrintPriority->put(stream);
	}
	else
		stream << "\t\tElement <PrintPriority> not present\n";

	if (PrinterName) {
		stream << "\t\t";
		PrinterName->put(stream);
	}
	else
		stream << "\t\tElement <PrinterName> not present\n";

	if (Originator) {
		stream << "\t\t";
		Originator->put(stream);
	}
	else
		stream << "\t\tElement <Originator> not present\n";

}

void
DC3Module_Printer::Put(ostream& stream)
{
	stream << "\tModule <Printer>\n";

	if (PrinterStatus) {
		stream << "\t\t";
		PrinterStatus->put(stream);
	}
	else
		stream << "\t\tElement <PrinterStatus> not present\n";

	if (PrinterStatusInfo) {
		stream << "\t\t";
		PrinterStatusInfo->put(stream);
	}
	else
		stream << "\t\tElement <PrinterStatusInfo> not present\n";

	if (PrinterName) {
		stream << "\t\t";
		PrinterName->put(stream);
	}
	else
		stream << "\t\tElement <PrinterName> not present\n";

	if (Manufacturer) {
		stream << "\t\t";
		Manufacturer->put(stream);
	}
	else
		stream << "\t\tElement <Manufacturer> not present\n";

	if (ManufacturerModelName) {
		stream << "\t\t";
		ManufacturerModelName->put(stream);
	}
	else
		stream << "\t\tElement <ManufacturerModelName> not present\n";

	if (DeviceSerialNumber) {
		stream << "\t\t";
		DeviceSerialNumber->put(stream);
	}
	else
		stream << "\t\tElement <DeviceSerialNumber> not present\n";

	if (SoftwareVersion) {
		stream << "\t\t";
		SoftwareVersion->put(stream);
	}
	else
		stream << "\t\tElement <SoftwareVersion> not present\n";

	if (DateOfLastCalibration) {
		stream << "\t\t";
		DateOfLastCalibration->put(stream);
	}
	else
		stream << "\t\tElement <DateOfLastCalibration> not present\n";

	if (TimeOfLastCalibration) {
		stream << "\t\t";
		TimeOfLastCalibration->put(stream);
	}
	else
		stream << "\t\tElement <TimeOfLastCalibration> not present\n";

}

void
DC3Module_ImageOverlayBoxPresentation::Put(ostream& stream)
{
	stream << "\tModule <ImageOverlayBoxPresentation>\n";

	if (OverlayMagnificationType) {
		stream << "\t\t";
		OverlayMagnificationType->put(stream);
	}
	else
		stream << "\t\tElement <OverlayMagnificationType> not present\n";

	if (OverlaySmoothingType) {
		stream << "\t\t";
		OverlaySmoothingType->put(stream);
	}
	else
		stream << "\t\tElement <OverlaySmoothingType> not present\n";

	if (OverlayForegroundDensity) {
		stream << "\t\t";
		OverlayForegroundDensity->put(stream);
	}
	else
		stream << "\t\tElement <OverlayForegroundDensity> not present\n";

	if (OverlayMode) {
		stream << "\t\t";
		OverlayMode->put(stream);
	}
	else
		stream << "\t\tElement <OverlayMode> not present\n";

	if (ThresholdDensity) {
		stream << "\t\t";
		ThresholdDensity->put(stream);
	}
	else
		stream << "\t\tElement <ThresholdDensity> not present\n";

}

void
DC3Module_ImageOverlayBoxRelationship::Put(ostream& stream)
{
	stream << "\tModule <ImageOverlayBoxRelationship>\n";

}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
