/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by module.awk with options method

#include "tmodulet.h"
#include "tmodule.h"
#include "tcond.h"

char *
DC3Module_PatientRelationship::Identify(void)
{
	return "PatientRelationship";
}

DC3Module_PatientRelationship::DC3Module_PatientRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_PatientIdentification::Identify(void)
{
	return "PatientIdentification";
}

DC3Module_PatientIdentification::DC3Module_PatientIdentification(DC3ListofAttributes *list)
{
	(void)list;
	PatientName=
		getDataElementUntyped(
			list,DC3TagFromName(PatientName),
			0,
			"PatientIdentification","PatientName");

	PatientID=
		getDataElementUntyped(
			list,DC3TagFromName(PatientID),
			0,
			"PatientIdentification","PatientID");

	IssuerOfPatientID=
		getDataElementUntyped(
			list,DC3TagFromName(IssuerOfPatientID),
			0,
			"PatientIdentification","IssuerOfPatientID");

	OtherPatientID=
		getDataElementUntyped(
			list,DC3TagFromName(OtherPatientID),
			0,
			"PatientIdentification","OtherPatientID");

	OtherPatientName=
		getDataElementUntyped(
			list,DC3TagFromName(OtherPatientName),
			0,
			"PatientIdentification","OtherPatientName");

	PatientBirthName=
		getDataElementUntyped(
			list,DC3TagFromName(PatientBirthName),
			0,
			"PatientIdentification","PatientBirthName");

	PatientMotherBirthName=
		getDataElementUntyped(
			list,DC3TagFromName(PatientMotherBirthName),
			0,
			"PatientIdentification","PatientMotherBirthName");

	MedicalRecordLocator=
		getDataElementUntyped(
			list,DC3TagFromName(MedicalRecordLocator),
			0,
			"PatientIdentification","MedicalRecordLocator");

}

char *
DC3Module_PatientDemographic::Identify(void)
{
	return "PatientDemographic";
}

DC3Module_PatientDemographic::DC3Module_PatientDemographic(DC3ListofAttributes *list)
{
	(void)list;
	PatientBirthDate=
		getDataElementUntyped(
			list,DC3TagFromName(PatientBirthDate),
			0,
			"PatientDemographic","PatientBirthDate");

	PatientBirthTime=
		getDataElementUntyped(
			list,DC3TagFromName(PatientBirthTime),
			0,
			"PatientDemographic","PatientBirthTime");

	PatientSex=
		getDataElementUntyped(
			list,DC3TagFromName(PatientSex),
			0,
			"PatientDemographic","PatientSex");
	DC3VerifyStringEnumValues(PatientSex,
		DC3StringValueDescription_Sex);

	PatientSize=
		getDataElementUntyped(
			list,DC3TagFromName(PatientSize),
			0,
			"PatientDemographic","PatientSize");

	PatientWeight=
		getDataElementUntyped(
			list,DC3TagFromName(PatientWeight),
			0,
			"PatientDemographic","PatientWeight");

	PatientAddress=
		getDataElementUntyped(
			list,DC3TagFromName(PatientAddress),
			0,
			"PatientDemographic","PatientAddress");

	MilitaryRank=
		getDataElementUntyped(
			list,DC3TagFromName(MilitaryRank),
			0,
			"PatientDemographic","MilitaryRank");

	BranchOfService=
		getDataElementUntyped(
			list,DC3TagFromName(BranchOfService),
			0,
			"PatientDemographic","BranchOfService");

	CountryOfResidence=
		getDataElementUntyped(
			list,DC3TagFromName(CountryOfResidence),
			0,
			"PatientDemographic","CountryOfResidence");

	RegionOfResidence=
		getDataElementUntyped(
			list,DC3TagFromName(RegionOfResidence),
			0,
			"PatientDemographic","RegionOfResidence");

	PatientTelephoneNumber=
		getDataElementUntyped(
			list,DC3TagFromName(PatientTelephoneNumber),
			0,
			"PatientDemographic","PatientTelephoneNumber");

	EthnicGroup=
		getDataElementUntyped(
			list,DC3TagFromName(EthnicGroup),
			0,
			"PatientDemographic","EthnicGroup");

	PatientReligiousPreference=
		getDataElementUntyped(
			list,DC3TagFromName(PatientReligiousPreference),
			0,
			"PatientDemographic","PatientReligiousPreference");

	PatientComments=
		getDataElementUntyped(
			list,DC3TagFromName(PatientComments),
			0,
			"PatientDemographic","PatientComments");

}

char *
DC3Module_PatientMedical::Identify(void)
{
	return "PatientMedical";
}

DC3Module_PatientMedical::DC3Module_PatientMedical(DC3ListofAttributes *list)
{
	(void)list;
	MedicalAlerts=
		getDataElementUntyped(
			list,DC3TagFromName(MedicalAlerts),
			0,
			"PatientMedical","MedicalAlerts");

	ContrastAllergies=
		getDataElementUntyped(
			list,DC3TagFromName(ContrastAllergies),
			0,
			"PatientMedical","ContrastAllergies");

	SmokingStatus=
		getDataElementUntyped(
			list,DC3TagFromName(SmokingStatus),
			0,
			"PatientMedical","SmokingStatus");
	DC3VerifyStringEnumValues(SmokingStatus,
		DC3StringValueDescription_SmokingStatus);

	AdditionalPatientHistory=
		getDataElementUntyped(
			list,DC3TagFromName(AdditionalPatientHistory),
			0,
			"PatientMedical","AdditionalPatientHistory");

	PregnancyStatus=
		getDataElementUntyped(
			list,DC3TagFromName(PregnancyStatus),
			0,
			"PatientMedical","PregnancyStatus");
	DC3VerifyBinaryEnumValues(PregnancyStatus,
		DC3BinaryValueDescription_PregnancyStatus);

	LastMenstrualDate=
		getDataElementUntyped(
			list,DC3TagFromName(LastMenstrualDate),
			0,
			"PatientMedical","LastMenstrualDate");

	SpecialNeeds=
		getDataElementUntyped(
			list,DC3TagFromName(SpecialNeeds),
			0,
			"PatientMedical","SpecialNeeds");

	PatientState=
		getDataElementUntyped(
			list,DC3TagFromName(PatientState),
			0,
			"PatientMedical","PatientState");

}

char *
DC3Module_VisitRelationship::Identify(void)
{
	return "VisitRelationship";
}

DC3Module_VisitRelationship::DC3Module_VisitRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_VisitIdentification::Identify(void)
{
	return "VisitIdentification";
}

DC3Module_VisitIdentification::DC3Module_VisitIdentification(DC3ListofAttributes *list)
{
	(void)list;
	InstitutionName=
		getDataElementUntyped(
			list,DC3TagFromName(InstitutionName),
			0,
			"VisitIdentification","InstitutionName");

	InstitutionAddress=
		getDataElementUntyped(
			list,DC3TagFromName(InstitutionAddress),
			0,
			"VisitIdentification","InstitutionAddress");

	AdmissionID=
		getDataElementUntyped(
			list,DC3TagFromName(AdmissionID),
			0,
			"VisitIdentification","AdmissionID");

	IssuerOfAdmissionID=
		getDataElementUntyped(
			list,DC3TagFromName(IssuerOfAdmissionID),
			0,
			"VisitIdentification","IssuerOfAdmissionID");

}

char *
DC3Module_VisitStatus::Identify(void)
{
	return "VisitStatus";
}

DC3Module_VisitStatus::DC3Module_VisitStatus(DC3ListofAttributes *list)
{
	(void)list;
	VisitStatusID=
		getDataElementUntyped(
			list,DC3TagFromName(VisitStatusID),
			0,
			"VisitStatus","VisitStatusID");
	DC3VerifyStringDefinedTerms(VisitStatusID,
		DC3StringValueDescription_VisitStatusID);

	CurrentPatientLocation=
		getDataElementUntyped(
			list,DC3TagFromName(CurrentPatientLocation),
			0,
			"VisitStatus","CurrentPatientLocation");

	PatientInstitutionResidence=
		getDataElementUntyped(
			list,DC3TagFromName(PatientInstitutionResidence),
			0,
			"VisitStatus","PatientInstitutionResidence");

	VisitComments=
		getDataElementUntyped(
			list,DC3TagFromName(VisitComments),
			0,
			"VisitStatus","VisitComments");

}

char *
DC3Module_VisitAdmission::Identify(void)
{
	return "VisitAdmission";
}

DC3Module_VisitAdmission::DC3Module_VisitAdmission(DC3ListofAttributes *list)
{
	(void)list;
	ReferringPhysicianName=
		getDataElementUntyped(
			list,DC3TagFromName(ReferringPhysicianName),
			0,
			"VisitAdmission","ReferringPhysicianName");

	ReferringPhysicianAddress=
		getDataElementUntyped(
			list,DC3TagFromName(ReferringPhysicianAddress),
			0,
			"VisitAdmission","ReferringPhysicianAddress");

	ReferringPhysicianTelephoneNumber=
		getDataElementUntyped(
			list,DC3TagFromName(ReferringPhysicianTelephoneNumber),
			0,
			"VisitAdmission","ReferringPhysicianTelephoneNumber");

	AdmittingDiagnosisDescription=
		getDataElementUntyped(
			list,DC3TagFromName(AdmittingDiagnosisDescription),
			0,
			"VisitAdmission","AdmittingDiagnosisDescription");

	RouteOfAdmissions=
		getDataElementUntyped(
			list,DC3TagFromName(RouteOfAdmissions),
			0,
			"VisitAdmission","RouteOfAdmissions");

	AdmittingDate=
		getDataElementUntyped(
			list,DC3TagFromName(AdmittingDate),
			0,
			"VisitAdmission","AdmittingDate");

	AdmittingTime=
		getDataElementUntyped(
			list,DC3TagFromName(AdmittingTime),
			0,
			"VisitAdmission","AdmittingTime");

}

char *
DC3Module_VisitDischarge::Identify(void)
{
	return "VisitDischarge";
}

DC3Module_VisitDischarge::DC3Module_VisitDischarge(DC3ListofAttributes *list)
{
	(void)list;
	DischargeDate=
		getDataElementUntyped(
			list,DC3TagFromName(DischargeDate),
			0,
			"VisitDischarge","DischargeDate");

	DischargeTime=
		getDataElementUntyped(
			list,DC3TagFromName(DischargeTime),
			0,
			"VisitDischarge","DischargeTime");

	DischargeDiagnosisDescription=
		getDataElementUntyped(
			list,DC3TagFromName(DischargeDiagnosisDescription),
			0,
			"VisitDischarge","DischargeDiagnosisDescription");

}

char *
DC3Module_VisitScheduling::Identify(void)
{
	return "VisitScheduling";
}

DC3Module_VisitScheduling::DC3Module_VisitScheduling(DC3ListofAttributes *list)
{
	(void)list;
	ScheduledAdmissionDate=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledAdmissionDate),
			0,
			"VisitScheduling","ScheduledAdmissionDate");

	ScheduledAdmissionTime=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledAdmissionTime),
			0,
			"VisitScheduling","ScheduledAdmissionTime");

	ScheduledDischargeDate=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledDischargeDate),
			0,
			"VisitScheduling","ScheduledDischargeDate");

	ScheduledDischargeTime=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledDischargeTime),
			0,
			"VisitScheduling","ScheduledDischargeTime");

	ScheduledPatientInstitutionResidence=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledPatientInstitutionResidence),
			0,
			"VisitScheduling","ScheduledPatientInstitutionResidence");

}

char *
DC3Module_StudyRelationship::Identify(void)
{
	return "StudyRelationship";
}

DC3Module_StudyRelationship::DC3Module_StudyRelationship(DC3ListofAttributes *list)
{
	(void)list;
	StudyInstanceUID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyInstanceUID),
			0,
			"StudyRelationship","StudyInstanceUID");

	AccessionNumber=
		getDataElementUntyped(
			list,DC3TagFromName(AccessionNumber),
			0,
			"StudyRelationship","AccessionNumber");

}

char *
DC3Module_StudyIdentification::Identify(void)
{
	return "StudyIdentification";
}

DC3Module_StudyIdentification::DC3Module_StudyIdentification(DC3ListofAttributes *list)
{
	(void)list;
	StudyID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyID),
			0,
			"StudyIdentification","StudyID");

	StudyIDIssuer=
		getDataElementUntyped(
			list,DC3TagFromName(StudyIDIssuer),
			0,
			"StudyIdentification","StudyIDIssuer");

	OtherStudyNumbers=
		getDataElementUntyped(
			list,DC3TagFromName(OtherStudyNumbers),
			0,
			"StudyIdentification","OtherStudyNumbers");

}

char *
DC3Module_StudyClassification::Identify(void)
{
	return "StudyClassification";
}

DC3Module_StudyClassification::DC3Module_StudyClassification(DC3ListofAttributes *list)
{
	(void)list;
	StudyStatusID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyStatusID),
			0,
			"StudyClassification","StudyStatusID");
	DC3VerifyStringEnumValues(StudyStatusID,
		DC3StringValueDescription_StudyStatusID);

	StudyPriorityID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyPriorityID),
			0,
			"StudyClassification","StudyPriorityID");
	DC3VerifyStringEnumValues(StudyPriorityID,
		DC3StringValueDescription_Priority);

	StudyComments=
		getDataElementUntyped(
			list,DC3TagFromName(StudyComments),
			0,
			"StudyClassification","StudyComments");

}

char *
DC3Module_StudyScheduling::Identify(void)
{
	return "StudyScheduling";
}

DC3Module_StudyScheduling::DC3Module_StudyScheduling(DC3ListofAttributes *list)
{
	(void)list;
	ScheduledStudyStartDate=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyStartDate),
			0,
			"StudyScheduling","ScheduledStudyStartDate");

	ScheduledStudyStartTime=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyStartTime),
			0,
			"StudyScheduling","ScheduledStudyStartTime");

	ScheduledStudyStopDate=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyStopDate),
			0,
			"StudyScheduling","ScheduledStudyStopDate");

	ScheduledStudyStopTime=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyStopTime),
			0,
			"StudyScheduling","ScheduledStudyStopTime");

	ScheduledStudyLocation=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyLocation),
			0,
			"StudyScheduling","ScheduledStudyLocation");

	ScheduledStudyLocationAETitle=
		getDataElementUntyped(
			list,DC3TagFromName(ScheduledStudyLocationAETitle),
			0,
			"StudyScheduling","ScheduledStudyLocationAETitle");

	ReasonForStudy=
		getDataElementUntyped(
			list,DC3TagFromName(ReasonForStudy),
			0,
			"StudyScheduling","ReasonForStudy");

	RequestingPhysician=
		getDataElementUntyped(
			list,DC3TagFromName(RequestingPhysician),
			0,
			"StudyScheduling","RequestingPhysician");

	RequestingService=
		getDataElementUntyped(
			list,DC3TagFromName(RequestingService),
			0,
			"StudyScheduling","RequestingService");

	RequestedProcedureDescription=
		getDataElementUntyped(
			list,DC3TagFromName(RequestedProcedureDescription),
			0,
			"StudyScheduling","RequestedProcedureDescription");

	RequestedContrastAgent=
		getDataElementUntyped(
			list,DC3TagFromName(RequestedContrastAgent),
			0,
			"StudyScheduling","RequestedContrastAgent");

}

char *
DC3Module_StudyAcquisition::Identify(void)
{
	return "StudyAcquisition";
}

DC3Module_StudyAcquisition::DC3Module_StudyAcquisition(DC3ListofAttributes *list)
{
	(void)list;
	StudyArrivalDate=
		getDataElementUntyped(
			list,DC3TagFromName(StudyArrivalDate),
			0,
			"StudyAcquisition","StudyArrivalDate");

	StudyArrivalTime=
		getDataElementUntyped(
			list,DC3TagFromName(StudyArrivalTime),
			0,
			"StudyAcquisition","StudyArrivalTime");

	StudyDate=
		getDataElementUntyped(
			list,DC3TagFromName(StudyDate),
			0,
			"StudyAcquisition","StudyDate");

	StudyTime=
		getDataElementUntyped(
			list,DC3TagFromName(StudyTime),
			0,
			"StudyAcquisition","StudyTime");

	StudyCompletionDate=
		getDataElementUntyped(
			list,DC3TagFromName(StudyCompletionDate),
			0,
			"StudyAcquisition","StudyCompletionDate");

	StudyCompletionTime=
		getDataElementUntyped(
			list,DC3TagFromName(StudyCompletionTime),
			0,
			"StudyAcquisition","StudyCompletionTime");

	StudyVerifiedDate=
		getDataElementUntyped(
			list,DC3TagFromName(StudyVerifiedDate),
			0,
			"StudyAcquisition","StudyVerifiedDate");

	StudyVerifiedTime=
		getDataElementUntyped(
			list,DC3TagFromName(StudyVerifiedTime),
			0,
			"StudyAcquisition","StudyVerifiedTime");

	SeriesInStudy=
		getDataElementUntyped(
			list,DC3TagFromName(SeriesInStudy),
			0,
			"StudyAcquisition","SeriesInStudy");

	AcquisitionsInStudy=
		getDataElementUntyped(
			list,DC3TagFromName(AcquisitionsInStudy),
			0,
			"StudyAcquisition","AcquisitionsInStudy");

}

char *
DC3Module_StudyRead::Identify(void)
{
	return "StudyRead";
}

DC3Module_StudyRead::DC3Module_StudyRead(DC3ListofAttributes *list)
{
	(void)list;
	PhysicianReadingStudy=
		getDataElementUntyped(
			list,DC3TagFromName(PhysicianReadingStudy),
			0,
			"StudyRead","PhysicianReadingStudy");

	StudyReadDate=
		getDataElementUntyped(
			list,DC3TagFromName(StudyReadDate),
			0,
			"StudyRead","StudyReadDate");

	StudyReadTime=
		getDataElementUntyped(
			list,DC3TagFromName(StudyReadTime),
			0,
			"StudyRead","StudyReadTime");

}

char *
DC3Module_StudyComponent::Identify(void)
{
	return "StudyComponent";
}

DC3Module_StudyComponent::DC3Module_StudyComponent(DC3ListofAttributes *list)
{
	(void)list;
	StudyID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyID),
			0,
			"StudyComponent","StudyID");

	StudyInstanceUID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyInstanceUID),
			0,
			"StudyComponent","StudyInstanceUID");

}

char *
DC3Module_StudyComponentRelationship::Identify(void)
{
	return "StudyComponentRelationship";
}

DC3Module_StudyComponentRelationship::DC3Module_StudyComponentRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_StudyComponentAcquisition::Identify(void)
{
	return "StudyComponentAcquisition";
}

DC3Module_StudyComponentAcquisition::DC3Module_StudyComponentAcquisition(DC3ListofAttributes *list)
{
	(void)list;
	Modality=
		getDataElementUntyped(
			list,DC3TagFromName(Modality),
			0,
			"StudyComponentAcquisition","Modality");
	DC3VerifyStringDefinedTerms(Modality,
		DC3StringValueDescription_Modality);

	StudyDescription=
		getDataElementUntyped(
			list,DC3TagFromName(StudyDescription),
			0,
			"StudyComponentAcquisition","StudyDescription");

	PerformingPhysicianName=
		getDataElementUntyped(
			list,DC3TagFromName(PerformingPhysicianName),
			0,
			"StudyComponentAcquisition","PerformingPhysicianName");

	StudyComponentStatusID=
		getDataElementUntyped(
			list,DC3TagFromName(StudyComponentStatusID),
			0,
			"StudyComponentAcquisition","StudyComponentStatusID");
	DC3VerifyStringEnumValues(StudyComponentStatusID,
		DC3StringValueDescription_StudyComponentStatusID);

}

char *
DC3Module_ResultsRelationship::Identify(void)
{
	return "ResultsRelationship";
}

DC3Module_ResultsRelationship::DC3Module_ResultsRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_ResultsIdentification::Identify(void)
{
	return "ResultsIdentification";
}

DC3Module_ResultsIdentification::DC3Module_ResultsIdentification(DC3ListofAttributes *list)
{
	(void)list;
	ResultsID=
		getDataElementUntyped(
			list,DC3TagFromName(ResultsID),
			0,
			"ResultsIdentification","ResultsID");

	ResultsIDIssuer=
		getDataElementUntyped(
			list,DC3TagFromName(ResultsIDIssuer),
			0,
			"ResultsIdentification","ResultsIDIssuer");

}

char *
DC3Module_ResultsImpression::Identify(void)
{
	return "ResultsImpression";
}

DC3Module_ResultsImpression::DC3Module_ResultsImpression(DC3ListofAttributes *list)
{
	(void)list;
	Impressions=
		getDataElementUntyped(
			list,DC3TagFromName(Impressions),
			0,
			"ResultsImpression","Impressions");

	ResultsComments=
		getDataElementUntyped(
			list,DC3TagFromName(ResultsComments),
			0,
			"ResultsImpression","ResultsComments");

}

char *
DC3Module_InterpretationRelationship::Identify(void)
{
	return "InterpretationRelationship";
}

DC3Module_InterpretationRelationship::DC3Module_InterpretationRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_InterpretationIdentification::Identify(void)
{
	return "InterpretationIdentification";
}

DC3Module_InterpretationIdentification::DC3Module_InterpretationIdentification(DC3ListofAttributes *list)
{
	(void)list;
	InterpretationID=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationID),
			0,
			"InterpretationIdentification","InterpretationID");

	InterpretationIDIssuer=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationIDIssuer),
			0,
			"InterpretationIdentification","InterpretationIDIssuer");

}

char *
DC3Module_InterpretationState::Identify(void)
{
	return "InterpretationState";
}

DC3Module_InterpretationState::DC3Module_InterpretationState(DC3ListofAttributes *list)
{
	(void)list;
	InterpretationTypeID=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationTypeID),
			0,
			"InterpretationState","InterpretationTypeID");
	DC3VerifyStringDefinedTerms(InterpretationTypeID,
		DC3StringValueDescription_InterpretationTypeID);

	InterpretationStatusID=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationStatusID),
			0,
			"InterpretationState","InterpretationStatusID");
	DC3VerifyStringEnumValues(InterpretationStatusID,
		DC3StringValueDescription_InterpretationStatusID);

}

char *
DC3Module_InterpretationRecording::Identify(void)
{
	return "InterpretationRecording";
}

DC3Module_InterpretationRecording::DC3Module_InterpretationRecording(DC3ListofAttributes *list)
{
	(void)list;
	InterpretationRecordedDate=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationRecordedDate),
			0,
			"InterpretationRecording","InterpretationRecordedDate");

	InterpretationRecordedTime=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationRecordedTime),
			0,
			"InterpretationRecording","InterpretationRecordedTime");

	InterpretationRecorder=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationRecorder),
			0,
			"InterpretationRecording","InterpretationRecorder");

	ReferenceToRecordedSound=
		getDataElementUntyped(
			list,DC3TagFromName(ReferenceToRecordedSound),
			0,
			"InterpretationRecording","ReferenceToRecordedSound");

}

char *
DC3Module_InterpretationTranscription::Identify(void)
{
	return "InterpretationTranscription";
}

DC3Module_InterpretationTranscription::DC3Module_InterpretationTranscription(DC3ListofAttributes *list)
{
	(void)list;
	InterpretationTranscriptionDate=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationTranscriptionDate),
			0,
			"InterpretationTranscription","InterpretationTranscriptionDate");

	InterpretationTranscriptionTime=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationTranscriptionTime),
			0,
			"InterpretationTranscription","InterpretationTranscriptionTime");

	InterpretationTranscriber=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationTranscriber),
			0,
			"InterpretationTranscription","InterpretationTranscriber");

	InterpretationText=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationText),
			0,
			"InterpretationTranscription","InterpretationText");

	InterpretationAuthor=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationAuthor),
			0,
			"InterpretationTranscription","InterpretationAuthor");

}

char *
DC3Module_InterpretationApproval::Identify(void)
{
	return "InterpretationApproval";
}

DC3Module_InterpretationApproval::DC3Module_InterpretationApproval(DC3ListofAttributes *list)
{
	(void)list;
	InterpretationDiagnosisDescription=
		getDataElementUntyped(
			list,DC3TagFromName(InterpretationDiagnosisDescription),
			0,
			"InterpretationApproval","InterpretationDiagnosisDescription");

}

char *
DC3Module_Patient::Identify(void)
{
	return "Patient";
}

DC3Module_Patient::DC3Module_Patient(DC3ListofAttributes *list)
{
	(void)list;
	PatientName=
		getDataElementType2(
			list,DC3TagFromName(PatientName),
			0,
			"Patient","PatientName");

	PatientID=
		getDataElementType2(
			list,DC3TagFromName(PatientID),
			0,
			"Patient","PatientID");

	PatientBirthDate=
		getDataElementType2(
			list,DC3TagFromName(PatientBirthDate),
			0,
			"Patient","PatientBirthDate");

	PatientSex=
		getDataElementType2(
			list,DC3TagFromName(PatientSex),
			0,
			"Patient","PatientSex");
	DC3VerifyStringEnumValues(PatientSex,
		DC3StringValueDescription_Sex);

	PatientBirthTime=
		getDataElementType3(
			list,DC3TagFromName(PatientBirthTime),
			0,
			"Patient","PatientBirthTime");

	OtherPatientID=
		getDataElementType3(
			list,DC3TagFromName(OtherPatientID),
			0,
			"Patient","OtherPatientID");

	OtherPatientName=
		getDataElementType3(
			list,DC3TagFromName(OtherPatientName),
			0,
			"Patient","OtherPatientName");

	EthnicGroup=
		getDataElementType3(
			list,DC3TagFromName(EthnicGroup),
			0,
			"Patient","EthnicGroup");

	PatientComments=
		getDataElementType3(
			list,DC3TagFromName(PatientComments),
			0,
			"Patient","PatientComments");

}

char *
DC3Module_GeneralStudy::Identify(void)
{
	return "GeneralStudy";
}

DC3Module_GeneralStudy::DC3Module_GeneralStudy(DC3ListofAttributes *list)
{
	(void)list;
	StudyInstanceUID=
		getDataElementType1(
			list,DC3TagFromName(StudyInstanceUID),
			0,
			"GeneralStudy","StudyInstanceUID");

	StudyDate=
		getDataElementType2(
			list,DC3TagFromName(StudyDate),
			0,
			"GeneralStudy","StudyDate");

	StudyTime=
		getDataElementType2(
			list,DC3TagFromName(StudyTime),
			0,
			"GeneralStudy","StudyTime");

	ReferringPhysicianName=
		getDataElementType2(
			list,DC3TagFromName(ReferringPhysicianName),
			0,
			"GeneralStudy","ReferringPhysicianName");

	StudyID=
		getDataElementType2(
			list,DC3TagFromName(StudyID),
			0,
			"GeneralStudy","StudyID");

	AccessionNumber=
		getDataElementType2(
			list,DC3TagFromName(AccessionNumber),
			0,
			"GeneralStudy","AccessionNumber");

	StudyDescription=
		getDataElementType3(
			list,DC3TagFromName(StudyDescription),
			0,
			"GeneralStudy","StudyDescription");

	PhysicianReadingStudy=
		getDataElementType3(
			list,DC3TagFromName(PhysicianReadingStudy),
			0,
			"GeneralStudy","PhysicianReadingStudy");

}

char *
DC3Module_PatientStudy::Identify(void)
{
	return "PatientStudy";
}

DC3Module_PatientStudy::DC3Module_PatientStudy(DC3ListofAttributes *list)
{
	(void)list;
	AdmittingDiagnosisDescription=
		getDataElementType3(
			list,DC3TagFromName(AdmittingDiagnosisDescription),
			0,
			"PatientStudy","AdmittingDiagnosisDescription");

	PatientAge=
		getDataElementType3(
			list,DC3TagFromName(PatientAge),
			0,
			"PatientStudy","PatientAge");

	PatientSize=
		getDataElementType3(
			list,DC3TagFromName(PatientSize),
			0,
			"PatientStudy","PatientSize");

	PatientWeight=
		getDataElementType3(
			list,DC3TagFromName(PatientWeight),
			0,
			"PatientStudy","PatientWeight");

	Occupation=
		getDataElementType3(
			list,DC3TagFromName(Occupation),
			0,
			"PatientStudy","Occupation");

	AdditionalPatientHistory=
		getDataElementType3(
			list,DC3TagFromName(AdditionalPatientHistory),
			0,
			"PatientStudy","AdditionalPatientHistory");

}

char *
DC3Module_GeneralSeries::Identify(void)
{
	return "GeneralSeries";
}

DC3Module_GeneralSeries::DC3Module_GeneralSeries(DC3ListofAttributes *list)
{
	(void)list;
	Modality=
		getDataElementType1(
			list,DC3TagFromName(Modality),
			0,
			"GeneralSeries","Modality");
	DC3VerifyStringDefinedTerms(Modality,
		DC3StringValueDescription_Modality);

	SeriesInstanceUID=
		getDataElementType1(
			list,DC3TagFromName(SeriesInstanceUID),
			0,
			"GeneralSeries","SeriesInstanceUID");

	SeriesNumber=
		getDataElementType2(
			list,DC3TagFromName(SeriesNumber),
			0,
			"GeneralSeries","SeriesNumber");

	Laterality=
		getDataElementType2C(
			list,DC3TagFromName(Laterality),
			DC3Condition_Never, 0,
			"GeneralSeries","Laterality");
	DC3VerifyStringEnumValues(Laterality,
		DC3StringValueDescription_Laterality);

	SeriesDate=
		getDataElementType3(
			list,DC3TagFromName(SeriesDate),
			0,
			"GeneralSeries","SeriesDate");

	SeriesTime=
		getDataElementType3(
			list,DC3TagFromName(SeriesTime),
			0,
			"GeneralSeries","SeriesTime");

	PerformingPhysicianName=
		getDataElementType3(
			list,DC3TagFromName(PerformingPhysicianName),
			0,
			"GeneralSeries","PerformingPhysicianName");

	ProtocolName=
		getDataElementType3(
			list,DC3TagFromName(ProtocolName),
			0,
			"GeneralSeries","ProtocolName");

	SeriesDescription=
		getDataElementType3(
			list,DC3TagFromName(SeriesDescription),
			0,
			"GeneralSeries","SeriesDescription");

	OperatorName=
		getDataElementType3(
			list,DC3TagFromName(OperatorName),
			0,
			"GeneralSeries","OperatorName");

	BodyPartExamined=
		getDataElementType3(
			list,DC3TagFromName(BodyPartExamined),
			0,
			"GeneralSeries","BodyPartExamined");
	DC3VerifyStringDefinedTerms(BodyPartExamined,
		DC3StringValueDescription_BodyPartExamined);

	PatientPosition=
		getDataElementType2C(
			list,DC3TagFromName(PatientPosition),
			DC3Condition_ModalityIsCTOrMR, 0,
			"GeneralSeries","PatientPosition");
	DC3VerifyStringDefinedTerms(PatientPosition,
		DC3StringValueDescription_PatientPosition);

	SmallestPixelValueInSeries=
		getDataElementType3(
			list,DC3TagFromName(SmallestPixelValueInSeries),
			0,
			"GeneralSeries","SmallestPixelValueInSeries");

	LargestPixelValueInSeries=
		getDataElementType3(
			list,DC3TagFromName(LargestPixelValueInSeries),
			0,
			"GeneralSeries","LargestPixelValueInSeries");

}

char *
DC3Module_FrameOfReference::Identify(void)
{
	return "FrameOfReference";
}

DC3Module_FrameOfReference::DC3Module_FrameOfReference(DC3ListofAttributes *list)
{
	(void)list;
	FrameOfReferenceUID=
		getDataElementType1(
			list,DC3TagFromName(FrameOfReferenceUID),
			0,
			"FrameOfReference","FrameOfReferenceUID");

	PositionReferenceIndicator=
		getDataElementType2(
			list,DC3TagFromName(PositionReferenceIndicator),
			0,
			"FrameOfReference","PositionReferenceIndicator");

}

char *
DC3Module_GeneralEquipment::Identify(void)
{
	return "GeneralEquipment";
}

DC3Module_GeneralEquipment::DC3Module_GeneralEquipment(DC3ListofAttributes *list)
{
	(void)list;
	Manufacturer=
		getDataElementType2(
			list,DC3TagFromName(Manufacturer),
			0,
			"GeneralEquipment","Manufacturer");

	InstitutionName=
		getDataElementType3(
			list,DC3TagFromName(InstitutionName),
			0,
			"GeneralEquipment","InstitutionName");

	InstitutionAddress=
		getDataElementType3(
			list,DC3TagFromName(InstitutionAddress),
			0,
			"GeneralEquipment","InstitutionAddress");

	StationName=
		getDataElementType3(
			list,DC3TagFromName(StationName),
			0,
			"GeneralEquipment","StationName");

	InstitutionalDepartmentName=
		getDataElementType3(
			list,DC3TagFromName(InstitutionalDepartmentName),
			0,
			"GeneralEquipment","InstitutionalDepartmentName");

	ManufacturerModelName=
		getDataElementType3(
			list,DC3TagFromName(ManufacturerModelName),
			0,
			"GeneralEquipment","ManufacturerModelName");

	DeviceSerialNumber=
		getDataElementType3(
			list,DC3TagFromName(DeviceSerialNumber),
			0,
			"GeneralEquipment","DeviceSerialNumber");

	SoftwareVersion=
		getDataElementType3(
			list,DC3TagFromName(SoftwareVersion),
			0,
			"GeneralEquipment","SoftwareVersion");

	SpatialResolution=
		getDataElementType3(
			list,DC3TagFromName(SpatialResolution),
			0,
			"GeneralEquipment","SpatialResolution");

	DateOfLastCalibration=
		getDataElementType3(
			list,DC3TagFromName(DateOfLastCalibration),
			0,
			"GeneralEquipment","DateOfLastCalibration");

	TimeOfLastCalibration=
		getDataElementType3(
			list,DC3TagFromName(TimeOfLastCalibration),
			0,
			"GeneralEquipment","TimeOfLastCalibration");

	PixelPaddingValue=
		getDataElementType3(
			list,DC3TagFromName(PixelPaddingValue),
			0,
			"GeneralEquipment","PixelPaddingValue");

}

char *
DC3Module_GeneralImage::Identify(void)
{
	return "GeneralImage";
}

DC3Module_GeneralImage::DC3Module_GeneralImage(DC3ListofAttributes *list)
{
	(void)list;
	ImageNumber=
		getDataElementType2(
			list,DC3TagFromName(ImageNumber),
			0,
			"GeneralImage","ImageNumber");

	PatientOrientation=
		getDataElementType2C(
			list,DC3TagFromName(PatientOrientation),
			DC3Condition_ImagePlaneModuleNotRequired, 0,
			"GeneralImage","PatientOrientation");

	ImageDate=
		getDataElementType2C(
			list,DC3TagFromName(ImageDate),
			DC3Condition_Always, 0,
			"GeneralImage","ImageDate");

	ImageTime=
		getDataElementType2C(
			list,DC3TagFromName(ImageTime),
			DC3Condition_Always, 0,
			"GeneralImage","ImageTime");

	ImageType=
		getDataElementType3(
			list,DC3TagFromName(ImageType),
			0,
			"GeneralImage","ImageType");

	AcquisitionNumber=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionNumber),
			0,
			"GeneralImage","AcquisitionNumber");

	AcquisitionDate=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionDate),
			0,
			"GeneralImage","AcquisitionDate");

	AcquisitionTime=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionTime),
			0,
			"GeneralImage","AcquisitionTime");

	DerivationDescription=
		getDataElementType3(
			list,DC3TagFromName(DerivationDescription),
			0,
			"GeneralImage","DerivationDescription");

	ImagesInAcquisition=
		getDataElementType3(
			list,DC3TagFromName(ImagesInAcquisition),
			0,
			"GeneralImage","ImagesInAcquisition");

	ImageComments=
		getDataElementType3(
			list,DC3TagFromName(ImageComments),
			0,
			"GeneralImage","ImageComments");

}

char *
DC3Module_ImagePlane::Identify(void)
{
	return "ImagePlane";
}

DC3Module_ImagePlane::DC3Module_ImagePlane(DC3ListofAttributes *list)
{
	(void)list;
	PixelSpacing=
		getDataElementType1(
			list,DC3TagFromName(PixelSpacing),
			0,
			"ImagePlane","PixelSpacing");

	ImageOrientationPatient=
		getDataElementType1(
			list,DC3TagFromName(ImageOrientationPatient),
			0,
			"ImagePlane","ImageOrientationPatient");

	ImagePositionPatient=
		getDataElementType1(
			list,DC3TagFromName(ImagePositionPatient),
			0,
			"ImagePlane","ImagePositionPatient");

	SliceThickness=
		getDataElementType2(
			list,DC3TagFromName(SliceThickness),
			0,
			"ImagePlane","SliceThickness");

	SliceLocation=
		getDataElementType3(
			list,DC3TagFromName(SliceLocation),
			0,
			"ImagePlane","SliceLocation");

}

char *
DC3Module_ImagePixel::Identify(void)
{
	return "ImagePixel";
}

DC3Module_ImagePixel::DC3Module_ImagePixel(DC3ListofAttributes *list)
{
	(void)list;
	SamplesPerPixel=
		getDataElementType1(
			list,DC3TagFromName(SamplesPerPixel),
			0,
			"ImagePixel","SamplesPerPixel");

	PhotometricInterpretation=
		getDataElementType1(
			list,DC3TagFromName(PhotometricInterpretation),
			0,
			"ImagePixel","PhotometricInterpretation");
	DC3VerifyStringDefinedTerms(PhotometricInterpretation,
		DC3StringValueDescription_PhotometricInterpretation);

	Rows=
		getDataElementType1(
			list,DC3TagFromName(Rows),
			0,
			"ImagePixel","Rows");

	Columns=
		getDataElementType1(
			list,DC3TagFromName(Columns),
			0,
			"ImagePixel","Columns");

	BitsAllocated=
		getDataElementType1(
			list,DC3TagFromName(BitsAllocated),
			0,
			"ImagePixel","BitsAllocated");

	BitsStored=
		getDataElementType1(
			list,DC3TagFromName(BitsStored),
			0,
			"ImagePixel","BitsStored");

	HighBit=
		getDataElementType1(
			list,DC3TagFromName(HighBit),
			0,
			"ImagePixel","HighBit");

	PixelRepresentation=
		getDataElementType1(
			list,DC3TagFromName(PixelRepresentation),
			0,
			"ImagePixel","PixelRepresentation");
	DC3VerifyBinaryEnumValues(PixelRepresentation,
		DC3BinaryValueDescription_PixelRepresentation);

	PixelData=
		getDataElementType1(
			list,DC3TagFromName(PixelData),
			0,
			"ImagePixel","PixelData");

	PlanarConfiguration=
		getDataElementType1C(
			list,DC3TagFromName(PlanarConfiguration),
			DC3Condition_SamplesPerPixelGreaterThanOne, 0,
			"ImagePixel","PlanarConfiguration");
	DC3VerifyBinaryEnumValues(PlanarConfiguration,
		DC3BinaryValueDescription_PlanarConfiguration);

	PixelAspectRatio=
		getDataElementType1C(
			list,DC3TagFromName(PixelAspectRatio),
			DC3Condition_Never, 0,
			"ImagePixel","PixelAspectRatio");

	SmallestImagePixelValue=
		getDataElementType3(
			list,DC3TagFromName(SmallestImagePixelValue),
			0,
			"ImagePixel","SmallestImagePixelValue");

	LargestImagePixelValue=
		getDataElementType3(
			list,DC3TagFromName(LargestImagePixelValue),
			0,
			"ImagePixel","LargestImagePixelValue");

	RedPaletteColorLookupTableDescriptor=
		getDataElementType1C(
			list,DC3TagFromName(RedPaletteColorLookupTableDescriptor),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","RedPaletteColorLookupTableDescriptor");

	GreenPaletteColorLookupTableDescriptor=
		getDataElementType1C(
			list,DC3TagFromName(GreenPaletteColorLookupTableDescriptor),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","GreenPaletteColorLookupTableDescriptor");

	BluePaletteColorLookupTableDescriptor=
		getDataElementType1C(
			list,DC3TagFromName(BluePaletteColorLookupTableDescriptor),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","BluePaletteColorLookupTableDescriptor");

	RedPaletteColorLookupTableData=
		getDataElementType1C(
			list,DC3TagFromName(RedPaletteColorLookupTableData),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","RedPaletteColorLookupTableData");

	GreenPaletteColorLookupTableData=
		getDataElementType1C(
			list,DC3TagFromName(GreenPaletteColorLookupTableData),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","GreenPaletteColorLookupTableData");

	BluePaletteColorLookupTableData=
		getDataElementType1C(
			list,DC3TagFromName(BluePaletteColorLookupTableData),
			DC3Condition_PhotometricInterpretationNeedsPalette, 0,
			"ImagePixel","BluePaletteColorLookupTableData");

}

char *
DC3Module_ContrastBolus::Identify(void)
{
	return "ContrastBolus";
}

DC3Module_ContrastBolus::DC3Module_ContrastBolus(DC3ListofAttributes *list)
{
	(void)list;
	ContrastBolusAgent=
		getDataElementType2(
			list,DC3TagFromName(ContrastBolusAgent),
			0,
			"ContrastBolus","ContrastBolusAgent");

	ContrastBolusRoute=
		getDataElementType3(
			list,DC3TagFromName(ContrastBolusRoute),
			0,
			"ContrastBolus","ContrastBolusRoute");

	ContrastBolusVolume=
		getDataElementType3(
			list,DC3TagFromName(ContrastBolusVolume),
			0,
			"ContrastBolus","ContrastBolusVolume");

	ContrastBolusStartTime=
		getDataElementType3(
			list,DC3TagFromName(ContrastBolusStartTime),
			0,
			"ContrastBolus","ContrastBolusStartTime");

	ContrastBolusStopTime=
		getDataElementType3(
			list,DC3TagFromName(ContrastBolusStopTime),
			0,
			"ContrastBolus","ContrastBolusStopTime");

	ContrastBolusTotalDose=
		getDataElementType3(
			list,DC3TagFromName(ContrastBolusTotalDose),
			0,
			"ContrastBolus","ContrastBolusTotalDose");

}

char *
DC3Module_Cine::Identify(void)
{
	return "Cine";
}

DC3Module_Cine::DC3Module_Cine(DC3ListofAttributes *list)
{
	(void)list;
	FrameTime=
		getDataElementType1C(
			list,DC3TagFromName(FrameTime),
			DC3Condition_Never, 0,
			"Cine","FrameTime");

	FrameTimeVector=
		getDataElementType1C(
			list,DC3TagFromName(FrameTimeVector),
			DC3Condition_Never, 0,
			"Cine","FrameTimeVector");

	StartTrim=
		getDataElementType3(
			list,DC3TagFromName(StartTrim),
			0,
			"Cine","StartTrim");

	StopTrim=
		getDataElementType3(
			list,DC3TagFromName(StopTrim),
			0,
			"Cine","StopTrim");

	RecommendedDisplayFrameRate=
		getDataElementType3(
			list,DC3TagFromName(RecommendedDisplayFrameRate),
			0,
			"Cine","RecommendedDisplayFrameRate");

	CineRate=
		getDataElementType3(
			list,DC3TagFromName(CineRate),
			0,
			"Cine","CineRate");

	FrameDelay=
		getDataElementType3(
			list,DC3TagFromName(FrameDelay),
			0,
			"Cine","FrameDelay");

	EffectiveSeriesDuration=
		getDataElementType3(
			list,DC3TagFromName(EffectiveSeriesDuration),
			0,
			"Cine","EffectiveSeriesDuration");

	ActualFrameDuration=
		getDataElementType3(
			list,DC3TagFromName(ActualFrameDuration),
			0,
			"Cine","ActualFrameDuration");

}

char *
DC3Module_MultiFrame::Identify(void)
{
	return "MultiFrame";
}

DC3Module_MultiFrame::DC3Module_MultiFrame(DC3ListofAttributes *list)
{
	(void)list;
	NumberOfFrames=
		getDataElementType1(
			list,DC3TagFromName(NumberOfFrames),
			0,
			"MultiFrame","NumberOfFrames");

	FrameIncrementPointer=
		getDataElementType1(
			list,DC3TagFromName(FrameIncrementPointer),
			0,
			"MultiFrame","FrameIncrementPointer");

}

char *
DC3Module_PatientSummary::Identify(void)
{
	return "PatientSummary";
}

DC3Module_PatientSummary::DC3Module_PatientSummary(DC3ListofAttributes *list)
{
	(void)list;
	PatientName=
		getDataElementType2(
			list,DC3TagFromName(PatientName),
			0,
			"PatientSummary","PatientName");

	PatientID=
		getDataElementType2(
			list,DC3TagFromName(PatientID),
			0,
			"PatientSummary","PatientID");

}

char *
DC3Module_StudyContent::Identify(void)
{
	return "StudyContent";
}

DC3Module_StudyContent::DC3Module_StudyContent(DC3ListofAttributes *list)
{
	(void)list;
	StudyID=
		getDataElementType2(
			list,DC3TagFromName(StudyID),
			0,
			"StudyContent","StudyID");

	StudyInstanceUID=
		getDataElementType1(
			list,DC3TagFromName(StudyInstanceUID),
			0,
			"StudyContent","StudyInstanceUID");

}

char *
DC3Module_CRSeries::Identify(void)
{
	return "CRSeries";
}

DC3Module_CRSeries::DC3Module_CRSeries(DC3ListofAttributes *list)
{
	(void)list;
	BodyPartExamined=
		getDataElementType2(
			list,DC3TagFromName(BodyPartExamined),
			0,
			"CRSeries","BodyPartExamined");
	DC3VerifyStringDefinedTerms(BodyPartExamined,
		DC3StringValueDescription_BodyPartExamined);

	ViewPosition=
		getDataElementType2(
			list,DC3TagFromName(ViewPosition),
			0,
			"CRSeries","ViewPosition");
	DC3VerifyStringDefinedTerms(ViewPosition,
		DC3StringValueDescription_ViewPosition);

	FilterType=
		getDataElementType3(
			list,DC3TagFromName(FilterType),
			0,
			"CRSeries","FilterType");

	CollimatorGridName=
		getDataElementType3(
			list,DC3TagFromName(CollimatorGridName),
			0,
			"CRSeries","CollimatorGridName");

	FocalSpot=
		getDataElementType3(
			list,DC3TagFromName(FocalSpot),
			0,
			"CRSeries","FocalSpot");

	PlateType=
		getDataElementType3(
			list,DC3TagFromName(PlateType),
			0,
			"CRSeries","PlateType");

	PhosphorType=
		getDataElementType3(
			list,DC3TagFromName(PhosphorType),
			0,
			"CRSeries","PhosphorType");

}

char *
DC3Module_CRImage::Identify(void)
{
	return "CRImage";
}

DC3Module_CRImage::DC3Module_CRImage(DC3ListofAttributes *list)
{
	(void)list;
	KVP=
		getDataElementType3(
			list,DC3TagFromName(KVP),
			0,
			"CRImage","KVP");

	PlateID=
		getDataElementType3(
			list,DC3TagFromName(PlateID),
			0,
			"CRImage","PlateID");

	DistanceSourceToDetector=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToDetector),
			0,
			"CRImage","DistanceSourceToDetector");

	DistanceSourceToPatient=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToPatient),
			0,
			"CRImage","DistanceSourceToPatient");

	ExposureTime=
		getDataElementType3(
			list,DC3TagFromName(ExposureTime),
			0,
			"CRImage","ExposureTime");

	XrayTubeCurrent=
		getDataElementType3(
			list,DC3TagFromName(XrayTubeCurrent),
			0,
			"CRImage","XrayTubeCurrent");

	Exposure=
		getDataElementType3(
			list,DC3TagFromName(Exposure),
			0,
			"CRImage","Exposure");

	GeneratorPower=
		getDataElementType3(
			list,DC3TagFromName(GeneratorPower),
			0,
			"CRImage","GeneratorPower");

	AcquisitionDeviceProcessingDescription=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionDeviceProcessingDescription),
			0,
			"CRImage","AcquisitionDeviceProcessingDescription");

	AcquisitionDeviceProcessingCode=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionDeviceProcessingCode),
			0,
			"CRImage","AcquisitionDeviceProcessingCode");

	CassetteOrientation=
		getDataElementType3(
			list,DC3TagFromName(CassetteOrientation),
			0,
			"CRImage","CassetteOrientation");
	DC3VerifyStringEnumValues(CassetteOrientation,
		DC3StringValueDescription_Orientation);

	CassetteSize=
		getDataElementType3(
			list,DC3TagFromName(CassetteSize),
			0,
			"CRImage","CassetteSize");
	DC3VerifyStringDefinedTerms(CassetteSize,
		DC3StringValueDescription_CassetteSize);

	ExposuresOnPlate=
		getDataElementType3(
			list,DC3TagFromName(ExposuresOnPlate),
			0,
			"CRImage","ExposuresOnPlate");

	RelativeXrayExposure=
		getDataElementType3(
			list,DC3TagFromName(RelativeXrayExposure),
			0,
			"CRImage","RelativeXrayExposure");

	Sensitivity=
		getDataElementType3(
			list,DC3TagFromName(Sensitivity),
			0,
			"CRImage","Sensitivity");

}

char *
DC3Module_CTImage::Identify(void)
{
	return "CTImage";
}

DC3Module_CTImage::DC3Module_CTImage(DC3ListofAttributes *list)
{
	(void)list;
	ImageType=
		getDataElementType1(
			list,DC3TagFromName(ImageType),
			0,
			"CTImage","ImageType");

	SamplesPerPixel=
		getDataElementType1(
			list,DC3TagFromName(SamplesPerPixel),
			0,
			"CTImage","SamplesPerPixel");
	DC3VerifyBinaryEnumValues(SamplesPerPixel,
		DC3BinaryValueDescription_SamplesPerPixelIsOne);

	PhotometricInterpretation=
		getDataElementType1(
			list,DC3TagFromName(PhotometricInterpretation),
			0,
			"CTImage","PhotometricInterpretation");
	DC3VerifyStringEnumValues(PhotometricInterpretation,
		DC3StringValueDescription_PhotometricInterpretationMonochrome);

	BitsAllocated=
		getDataElementType1(
			list,DC3TagFromName(BitsAllocated),
			0,
			"CTImage","BitsAllocated");
	DC3VerifyBinaryEnumValues(BitsAllocated,
		DC3BinaryValueDescription_BitsAre16);

	BitsStored=
		getDataElementType1(
			list,DC3TagFromName(BitsStored),
			0,
			"CTImage","BitsStored");
	DC3VerifyBinaryEnumValues(BitsStored,
		DC3BinaryValueDescription_BitsAre12Or16);

	HighBit=
		getDataElementType1(
			list,DC3TagFromName(HighBit),
			0,
			"CTImage","HighBit");
	DC3VerifyBinaryEnumValues(HighBit,
		DC3BinaryValueDescription_BitsAre11Or15);

	RescaleIntercept=
		getDataElementType1(
			list,DC3TagFromName(RescaleIntercept),
			0,
			"CTImage","RescaleIntercept");

	RescaleSlope=
		getDataElementType1(
			list,DC3TagFromName(RescaleSlope),
			0,
			"CTImage","RescaleSlope");

	KVP=
		getDataElementType2(
			list,DC3TagFromName(KVP),
			0,
			"CTImage","KVP");

	AcquisitionNumber=
		getDataElementType2(
			list,DC3TagFromName(AcquisitionNumber),
			0,
			"CTImage","AcquisitionNumber");

	ScanOptions=
		getDataElementType3(
			list,DC3TagFromName(ScanOptions),
			0,
			"CTImage","ScanOptions");

	DataCollectionDiameter=
		getDataElementType3(
			list,DC3TagFromName(DataCollectionDiameter),
			0,
			"CTImage","DataCollectionDiameter");

	DistanceSourceToDetector=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToDetector),
			0,
			"CTImage","DistanceSourceToDetector");

	DistanceSourceToPatient=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToPatient),
			0,
			"CTImage","DistanceSourceToPatient");

	GantryDetectorTilt=
		getDataElementType3(
			list,DC3TagFromName(GantryDetectorTilt),
			0,
			"CTImage","GantryDetectorTilt");

	TableHeight=
		getDataElementType3(
			list,DC3TagFromName(TableHeight),
			0,
			"CTImage","TableHeight");

	RotationDirection=
		getDataElementType3(
			list,DC3TagFromName(RotationDirection),
			0,
			"CTImage","RotationDirection");
	DC3VerifyStringEnumValues(RotationDirection,
		DC3StringValueDescription_RotationDirection);

	ExposureTime=
		getDataElementType3(
			list,DC3TagFromName(ExposureTime),
			0,
			"CTImage","ExposureTime");

	XrayTubeCurrent=
		getDataElementType3(
			list,DC3TagFromName(XrayTubeCurrent),
			0,
			"CTImage","XrayTubeCurrent");

	Exposure=
		getDataElementType3(
			list,DC3TagFromName(Exposure),
			0,
			"CTImage","Exposure");

	FilterType=
		getDataElementType3(
			list,DC3TagFromName(FilterType),
			0,
			"CTImage","FilterType");

	GeneratorPower=
		getDataElementType3(
			list,DC3TagFromName(GeneratorPower),
			0,
			"CTImage","GeneratorPower");

	FocalSpot=
		getDataElementType3(
			list,DC3TagFromName(FocalSpot),
			0,
			"CTImage","FocalSpot");

	ConvolutionKernel=
		getDataElementType3(
			list,DC3TagFromName(ConvolutionKernel),
			0,
			"CTImage","ConvolutionKernel");

}

char *
DC3Module_MRImage::Identify(void)
{
	return "MRImage";
}

DC3Module_MRImage::DC3Module_MRImage(DC3ListofAttributes *list)
{
	(void)list;
	ImageType=
		getDataElementType1(
			list,DC3TagFromName(ImageType),
			0,
			"MRImage","ImageType");

	SamplesPerPixel=
		getDataElementType1(
			list,DC3TagFromName(SamplesPerPixel),
			0,
			"MRImage","SamplesPerPixel");
	DC3VerifyBinaryEnumValues(SamplesPerPixel,
		DC3BinaryValueDescription_SamplesPerPixelIsOne);

	PhotometricInterpretation=
		getDataElementType1(
			list,DC3TagFromName(PhotometricInterpretation),
			0,
			"MRImage","PhotometricInterpretation");
	DC3VerifyStringEnumValues(PhotometricInterpretation,
		DC3StringValueDescription_PhotometricInterpretationMonochrome);

	BitsAllocated=
		getDataElementType1(
			list,DC3TagFromName(BitsAllocated),
			0,
			"MRImage","BitsAllocated");
	DC3VerifyBinaryEnumValues(BitsAllocated,
		DC3BinaryValueDescription_BitsAre16);

	ScanningSequence=
		getDataElementType1(
			list,DC3TagFromName(ScanningSequence),
			0,
			"MRImage","ScanningSequence");
	DC3VerifyStringEnumValues(ScanningSequence,
		DC3StringValueDescription_ScanningSequence);

	SequenceVariant=
		getDataElementType1(
			list,DC3TagFromName(SequenceVariant),
			0,
			"MRImage","SequenceVariant");
	DC3VerifyStringDefinedTerms(SequenceVariant,
		DC3StringValueDescription_SequenceVariant);

	ScanOptions=
		getDataElementType2(
			list,DC3TagFromName(ScanOptions),
			0,
			"MRImage","ScanOptions");
	DC3VerifyStringDefinedTerms(ScanOptions,
		DC3StringValueDescription_ScanOptions);

	MRAcquisitionType=
		getDataElementType2(
			list,DC3TagFromName(MRAcquisitionType),
			0,
			"MRImage","MRAcquisitionType");
	DC3VerifyStringEnumValues(MRAcquisitionType,
		DC3StringValueDescription_MRAcquisitionType);

	RepetitionTime=
		getDataElementType2C(
			list,DC3TagFromName(RepetitionTime),
			DC3Condition_MRIsNotEchoPlanarNotSegmentedKSpace, 0,
			"MRImage","RepetitionTime");

	EchoTime=
		getDataElementType2(
			list,DC3TagFromName(EchoTime),
			0,
			"MRImage","EchoTime");

	EchoTrainLength=
		getDataElementType2(
			list,DC3TagFromName(EchoTrainLength),
			0,
			"MRImage","EchoTrainLength");

	InversionTime=
		getDataElementType2C(
			list,DC3TagFromName(InversionTime),
			DC3Condition_MRIsInversionRecovery, 0,
			"MRImage","InversionTime");

	TriggerTime=
		getDataElementType2C(
			list,DC3TagFromName(TriggerTime),
			DC3Condition_MRIsCardiacOrPulseGated, 0,
			"MRImage","TriggerTime");

	SequenceName=
		getDataElementType3(
			list,DC3TagFromName(SequenceName),
			0,
			"MRImage","SequenceName");

	AngioFlag=
		getDataElementType3(
			list,DC3TagFromName(AngioFlag),
			0,
			"MRImage","AngioFlag");
	DC3VerifyStringEnumValues(AngioFlag,
		DC3StringValueDescription_AngioFlag);

	NumberOfAverages=
		getDataElementType3(
			list,DC3TagFromName(NumberOfAverages),
			0,
			"MRImage","NumberOfAverages");

	ImagingFrequency=
		getDataElementType3(
			list,DC3TagFromName(ImagingFrequency),
			0,
			"MRImage","ImagingFrequency");

	ImagedNucleus=
		getDataElementType3(
			list,DC3TagFromName(ImagedNucleus),
			0,
			"MRImage","ImagedNucleus");

	EchoNumber=
		getDataElementType3(
			list,DC3TagFromName(EchoNumber),
			0,
			"MRImage","EchoNumber");

	MagneticFieldStrength=
		getDataElementType3(
			list,DC3TagFromName(MagneticFieldStrength),
			0,
			"MRImage","MagneticFieldStrength");

	SpacingBetweenSlices=
		getDataElementType3(
			list,DC3TagFromName(SpacingBetweenSlices),
			0,
			"MRImage","SpacingBetweenSlices");

	NumberOfPhaseEncodingSteps=
		getDataElementType3(
			list,DC3TagFromName(NumberOfPhaseEncodingSteps),
			0,
			"MRImage","NumberOfPhaseEncodingSteps");

	PercentSampling=
		getDataElementType3(
			list,DC3TagFromName(PercentSampling),
			0,
			"MRImage","PercentSampling");

	PercentPhaseFieldOfView=
		getDataElementType3(
			list,DC3TagFromName(PercentPhaseFieldOfView),
			0,
			"MRImage","PercentPhaseFieldOfView");

	PixelBandwidth=
		getDataElementType3(
			list,DC3TagFromName(PixelBandwidth),
			0,
			"MRImage","PixelBandwidth");

	NominalInterval=
		getDataElementType3(
			list,DC3TagFromName(NominalInterval),
			0,
			"MRImage","NominalInterval");

	BeatRejectionFlag=
		getDataElementType3(
			list,DC3TagFromName(BeatRejectionFlag),
			0,
			"MRImage","BeatRejectionFlag");
	DC3VerifyStringEnumValues(BeatRejectionFlag,
		DC3StringValueDescription_YesNoLetter);

	LowRRValue=
		getDataElementType3(
			list,DC3TagFromName(LowRRValue),
			0,
			"MRImage","LowRRValue");

	HighRRValue=
		getDataElementType3(
			list,DC3TagFromName(HighRRValue),
			0,
			"MRImage","HighRRValue");

	IntervalsAcquired=
		getDataElementType3(
			list,DC3TagFromName(IntervalsAcquired),
			0,
			"MRImage","IntervalsAcquired");

	IntervalsRejected=
		getDataElementType3(
			list,DC3TagFromName(IntervalsRejected),
			0,
			"MRImage","IntervalsRejected");

	PVCRejection=
		getDataElementType3(
			list,DC3TagFromName(PVCRejection),
			0,
			"MRImage","PVCRejection");

	SkipBeats=
		getDataElementType3(
			list,DC3TagFromName(SkipBeats),
			0,
			"MRImage","SkipBeats");

	HeartRate=
		getDataElementType3(
			list,DC3TagFromName(HeartRate),
			0,
			"MRImage","HeartRate");

	CardiacNumberOfImages=
		getDataElementType3(
			list,DC3TagFromName(CardiacNumberOfImages),
			0,
			"MRImage","CardiacNumberOfImages");

	TriggerWindow=
		getDataElementType3(
			list,DC3TagFromName(TriggerWindow),
			0,
			"MRImage","TriggerWindow");

	ReconstructionDiameter=
		getDataElementType3(
			list,DC3TagFromName(ReconstructionDiameter),
			0,
			"MRImage","ReconstructionDiameter");

	ReceivingCoil=
		getDataElementType3(
			list,DC3TagFromName(ReceivingCoil),
			0,
			"MRImage","ReceivingCoil");

	TransmittingCoil=
		getDataElementType3(
			list,DC3TagFromName(TransmittingCoil),
			0,
			"MRImage","TransmittingCoil");

	AcquisitionMatrix=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionMatrix),
			0,
			"MRImage","AcquisitionMatrix");

	PhaseEncodingDirection=
		getDataElementType3(
			list,DC3TagFromName(PhaseEncodingDirection),
			0,
			"MRImage","PhaseEncodingDirection");
	DC3VerifyStringEnumValues(PhaseEncodingDirection,
		DC3StringValueDescription_PhaseEncodingDirection);

	FlipAngle=
		getDataElementType3(
			list,DC3TagFromName(FlipAngle),
			0,
			"MRImage","FlipAngle");

	SAR=
		getDataElementType3(
			list,DC3TagFromName(SAR),
			0,
			"MRImage","SAR");

	VariableFlipAngleFlag=
		getDataElementType3(
			list,DC3TagFromName(VariableFlipAngleFlag),
			0,
			"MRImage","VariableFlipAngleFlag");
	DC3VerifyStringEnumValues(VariableFlipAngleFlag,
		DC3StringValueDescription_YesNoLetter);

	dBdt=
		getDataElementType3(
			list,DC3TagFromName(dBdt),
			0,
			"MRImage","dBdt");

	TemporalPositionIdentifier=
		getDataElementType3(
			list,DC3TagFromName(TemporalPositionIdentifier),
			0,
			"MRImage","TemporalPositionIdentifier");

	NumberOfTemporalPositions=
		getDataElementType3(
			list,DC3TagFromName(NumberOfTemporalPositions),
			0,
			"MRImage","NumberOfTemporalPositions");

	TemporalResolution=
		getDataElementType3(
			list,DC3TagFromName(TemporalResolution),
			0,
			"MRImage","TemporalResolution");

}

char *
DC3Module_NMSeries::Identify(void)
{
	return "NMSeries";
}

DC3Module_NMSeries::DC3Module_NMSeries(DC3ListofAttributes *list)
{
	(void)list;
	Radionuclide=
		getDataElementType2(
			list,DC3TagFromName(Radionuclide),
			0,
			"NMSeries","Radionuclide");

	NuclearMedicineSeriesType=
		getDataElementType2(
			list,DC3TagFromName(NuclearMedicineSeriesType),
			0,
			"NMSeries","NuclearMedicineSeriesType");
	DC3VerifyStringDefinedTerms(NuclearMedicineSeriesType,
		DC3StringValueDescription_NuclearMedicineSeriesType);

	ScanVelocity=
		getDataElementType2C(
			list,DC3TagFromName(ScanVelocity),
			DC3Condition_NMIsWholeBody, 0,
			"NMSeries","ScanVelocity");

	WholeBodyTechnique=
		getDataElementType2C(
			list,DC3TagFromName(WholeBodyTechnique),
			DC3Condition_NMIsWholeBody, 0,
			"NMSeries","WholeBodyTechnique");
	DC3VerifyStringEnumValues(WholeBodyTechnique,
		DC3StringValueDescription_WholeBodyTechnique);

	ScanLength=
		getDataElementType2C(
			list,DC3TagFromName(ScanLength),
			DC3Condition_NMIsWholeBody, 0,
			"NMSeries","ScanLength");

	Radiopharmaceutical=
		getDataElementType3(
			list,DC3TagFromName(Radiopharmaceutical),
			0,
			"NMSeries","Radiopharmaceutical");

	EnergyWindowCenterline=
		getDataElementType3(
			list,DC3TagFromName(EnergyWindowCenterline),
			0,
			"NMSeries","EnergyWindowCenterline");

	EnergyWindowTotalWidth=
		getDataElementType3(
			list,DC3TagFromName(EnergyWindowTotalWidth),
			0,
			"NMSeries","EnergyWindowTotalWidth");

	InterventionalDrugName=
		getDataElementType3(
			list,DC3TagFromName(InterventionalDrugName),
			0,
			"NMSeries","InterventionalDrugName");

	InterventionalDrugStartTime=
		getDataElementType3(
			list,DC3TagFromName(InterventionalDrugStartTime),
			0,
			"NMSeries","InterventionalDrugStartTime");

	EffectiveSeriesDuration=
		getDataElementType3(
			list,DC3TagFromName(EffectiveSeriesDuration),
			0,
			"NMSeries","EffectiveSeriesDuration");

	SyringeCounts=
		getDataElementType3(
			list,DC3TagFromName(SyringeCounts),
			0,
			"NMSeries","SyringeCounts");

	TriggerSourceOrType=
		getDataElementType3(
			list,DC3TagFromName(TriggerSourceOrType),
			0,
			"NMSeries","TriggerSourceOrType");

	RadionuclideRoute=
		getDataElementType3(
			list,DC3TagFromName(RadionuclideRoute),
			0,
			"NMSeries","RadionuclideRoute");

	RadionuclideVolume=
		getDataElementType3(
			list,DC3TagFromName(RadionuclideVolume),
			0,
			"NMSeries","RadionuclideVolume");

	RadionuclideStartTime=
		getDataElementType3(
			list,DC3TagFromName(RadionuclideStartTime),
			0,
			"NMSeries","RadionuclideStartTime");

	RadionuclideStopTime=
		getDataElementType3(
			list,DC3TagFromName(RadionuclideStopTime),
			0,
			"NMSeries","RadionuclideStopTime");

	RadionuclideTotalDose=
		getDataElementType3(
			list,DC3TagFromName(RadionuclideTotalDose),
			0,
			"NMSeries","RadionuclideTotalDose");

	GantryDetectorTilt=
		getDataElementType3(
			list,DC3TagFromName(GantryDetectorTilt),
			0,
			"NMSeries","GantryDetectorTilt");

	IsotopeNumber=
		getDataElementType3(
			list,DC3TagFromName(IsotopeNumber),
			0,
			"NMSeries","IsotopeNumber");

}

char *
DC3Module_NMEquipment::Identify(void)
{
	return "NMEquipment";
}

DC3Module_NMEquipment::DC3Module_NMEquipment(DC3ListofAttributes *list)
{
	(void)list;
	CenterOfRotationOffset=
		getDataElementType3(
			list,DC3TagFromName(CenterOfRotationOffset),
			0,
			"NMEquipment","CenterOfRotationOffset");

	FieldOfViewShape=
		getDataElementType3(
			list,DC3TagFromName(FieldOfViewShape),
			0,
			"NMEquipment","FieldOfViewShape");
	DC3VerifyStringDefinedTerms(FieldOfViewShape,
		DC3StringValueDescription_FieldOfViewShape);

	FieldOfViewDimension=
		getDataElementType3(
			list,DC3TagFromName(FieldOfViewDimension),
			0,
			"NMEquipment","FieldOfViewDimension");

	CollimatorGridName=
		getDataElementType3(
			list,DC3TagFromName(CollimatorGridName),
			0,
			"NMEquipment","CollimatorGridName");

	CollimatorType=
		getDataElementType3(
			list,DC3TagFromName(CollimatorType),
			0,
			"NMEquipment","CollimatorType");
	DC3VerifyStringDefinedTerms(CollimatorType,
		DC3StringValueDescription_CollimatorType);

	FocalDistance=
		getDataElementType3(
			list,DC3TagFromName(FocalDistance),
			0,
			"NMEquipment","FocalDistance");

	XFocusCenter=
		getDataElementType3(
			list,DC3TagFromName(XFocusCenter),
			0,
			"NMEquipment","XFocusCenter");

	YFocusCenter=
		getDataElementType3(
			list,DC3TagFromName(YFocusCenter),
			0,
			"NMEquipment","YFocusCenter");

}

char *
DC3Module_NMImage::Identify(void)
{
	return "NMImage";
}

DC3Module_NMImage::DC3Module_NMImage(DC3ListofAttributes *list)
{
	(void)list;
	FrameIncrementPointer=
		getDataElementType1C(
			list,DC3TagFromName(FrameIncrementPointer),
			DC3Condition_Never, 0,
			"NMImage","FrameIncrementPointer");

	ZoomFactor=
		getDataElementType2(
			list,DC3TagFromName(ZoomFactor),
			0,
			"NMImage","ZoomFactor");

	CountsAccumulated=
		getDataElementType2(
			list,DC3TagFromName(CountsAccumulated),
			0,
			"NMImage","CountsAccumulated");

	AcquisitionTerminationCondition=
		getDataElementType3(
			list,DC3TagFromName(AcquisitionTerminationCondition),
			0,
			"NMImage","AcquisitionTerminationCondition");
	DC3VerifyStringDefinedTerms(AcquisitionTerminationCondition,
		DC3StringValueDescription_AcquisitionTerminationCondition);

	ReconstructionDiameter=
		getDataElementType3(
			list,DC3TagFromName(ReconstructionDiameter),
			0,
			"NMImage","ReconstructionDiameter");

	DistanceSourceToDetector=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToDetector),
			0,
			"NMImage","DistanceSourceToDetector");

	TableHeight=
		getDataElementType3(
			list,DC3TagFromName(TableHeight),
			0,
			"NMImage","TableHeight");

	TableTraverse=
		getDataElementType3(
			list,DC3TagFromName(TableTraverse),
			0,
			"NMImage","TableTraverse");

	AngularPosition=
		getDataElementType3(
			list,DC3TagFromName(AngularPosition),
			0,
			"NMImage","AngularPosition");

	RadialPosition=
		getDataElementType3(
			list,DC3TagFromName(RadialPosition),
			0,
			"NMImage","RadialPosition");

	ConvolutionKernel=
		getDataElementType3(
			list,DC3TagFromName(ConvolutionKernel),
			0,
			"NMImage","ConvolutionKernel");

	ActualFrameDuration=
		getDataElementType3(
			list,DC3TagFromName(ActualFrameDuration),
			0,
			"NMImage","ActualFrameDuration");

	CountRate=
		getDataElementType3(
			list,DC3TagFromName(CountRate),
			0,
			"NMImage","CountRate");

	PreprocessingFunction=
		getDataElementType3(
			list,DC3TagFromName(PreprocessingFunction),
			0,
			"NMImage","PreprocessingFunction");

	PostprocessingFunction=
		getDataElementType3(
			list,DC3TagFromName(PostprocessingFunction),
			0,
			"NMImage","PostprocessingFunction");

	PhaseNumber=
		getDataElementType3(
			list,DC3TagFromName(PhaseNumber),
			0,
			"NMImage","PhaseNumber");

	IntervalNumber=
		getDataElementType3(
			list,DC3TagFromName(IntervalNumber),
			0,
			"NMImage","IntervalNumber");

	TimeSlotNumber=
		getDataElementType3(
			list,DC3TagFromName(TimeSlotNumber),
			0,
			"NMImage","TimeSlotNumber");

	AngleNumber=
		getDataElementType3(
			list,DC3TagFromName(AngleNumber),
			0,
			"NMImage","AngleNumber");

	ZoomCenter=
		getDataElementType3(
			list,DC3TagFromName(ZoomCenter),
			0,
			"NMImage","ZoomCenter");

	CorrectedImage=
		getDataElementType3(
			list,DC3TagFromName(CorrectedImage),
			0,
			"NMImage","CorrectedImage");
	DC3VerifyStringDefinedTerms(CorrectedImage,
		DC3StringValueDescription_CorrectedImage);

}

char *
DC3Module_NMSPECTAcquisitionImage::Identify(void)
{
	return "NMSPECTAcquisitionImage";
}

DC3Module_NMSPECTAcquisitionImage::DC3Module_NMSPECTAcquisitionImage(DC3ListofAttributes *list)
{
	(void)list;
	FrameIncrementPointer=
		getDataElementType1(
			list,DC3TagFromName(FrameIncrementPointer),
			0,
			"NMSPECTAcquisitionImage","FrameIncrementPointer");

	AngularStep=
		getDataElementType1(
			list,DC3TagFromName(AngularStep),
			0,
			"NMSPECTAcquisitionImage","AngularStep");

	ZoomFactor=
		getDataElementType2(
			list,DC3TagFromName(ZoomFactor),
			0,
			"NMSPECTAcquisitionImage","ZoomFactor");

	ScanArc=
		getDataElementType2C(
			list,DC3TagFromName(ScanArc),
			DC3Condition_Never, 0,
			"NMSPECTAcquisitionImage","ScanArc");

	ReconstructionDiameter=
		getDataElementType3(
			list,DC3TagFromName(ReconstructionDiameter),
			0,
			"NMSPECTAcquisitionImage","ReconstructionDiameter");

	DistanceSourceToDetector=
		getDataElementType3(
			list,DC3TagFromName(DistanceSourceToDetector),
			0,
			"NMSPECTAcquisitionImage","DistanceSourceToDetector");

	TableHeight=
		getDataElementType3(
			list,DC3TagFromName(TableHeight),
			0,
			"NMSPECTAcquisitionImage","TableHeight");

	TableTraverse=
		getDataElementType3(
			list,DC3TagFromName(TableTraverse),
			0,
			"NMSPECTAcquisitionImage","TableTraverse");

	RotationDirection=
		getDataElementType3(
			list,DC3TagFromName(RotationDirection),
			0,
			"NMSPECTAcquisitionImage","RotationDirection");
	DC3VerifyStringEnumValues(RotationDirection,
		DC3StringValueDescription_RotationDirection);

	AngularPosition=
		getDataElementType3(
			list,DC3TagFromName(AngularPosition),
			0,
			"NMSPECTAcquisitionImage","AngularPosition");

	RadialPosition=
		getDataElementType3(
			list,DC3TagFromName(RadialPosition),
			0,
			"NMSPECTAcquisitionImage","RadialPosition");

	RotationOffset=
		getDataElementType3(
			list,DC3TagFromName(RotationOffset),
			0,
			"NMSPECTAcquisitionImage","RotationOffset");

	AngleNumber=
		getDataElementType3(
			list,DC3TagFromName(AngleNumber),
			0,
			"NMSPECTAcquisitionImage","AngleNumber");

	ZoomCenter=
		getDataElementType3(
			list,DC3TagFromName(ZoomCenter),
			0,
			"NMSPECTAcquisitionImage","ZoomCenter");

}

char *
DC3Module_NMMultiGatedAcquisitionImage::Identify(void)
{
	return "NMMultiGatedAcquisitionImage";
}

DC3Module_NMMultiGatedAcquisitionImage::DC3Module_NMMultiGatedAcquisitionImage(DC3ListofAttributes *list)
{
	(void)list;
	FrameIncrementPointer=
		getDataElementType1(
			list,DC3TagFromName(FrameIncrementPointer),
			0,
			"NMMultiGatedAcquisitionImage","FrameIncrementPointer");

	TriggerSourceOrType=
		getDataElementType2(
			list,DC3TagFromName(TriggerSourceOrType),
			0,
			"NMMultiGatedAcquisitionImage","TriggerSourceOrType");

	FrameTime=
		getDataElementType2(
			list,DC3TagFromName(FrameTime),
			0,
			"NMMultiGatedAcquisitionImage","FrameTime");

	TriggerTime=
		getDataElementType3(
			list,DC3TagFromName(TriggerTime),
			0,
			"NMMultiGatedAcquisitionImage","TriggerTime");

	NominalInterval=
		getDataElementType3(
			list,DC3TagFromName(NominalInterval),
			0,
			"NMMultiGatedAcquisitionImage","NominalInterval");

	FramingType=
		getDataElementType3(
			list,DC3TagFromName(FramingType),
			0,
			"NMMultiGatedAcquisitionImage","FramingType");

	BeatRejectionFlag=
		getDataElementType3(
			list,DC3TagFromName(BeatRejectionFlag),
			0,
			"NMMultiGatedAcquisitionImage","BeatRejectionFlag");
	DC3VerifyStringEnumValues(BeatRejectionFlag,
		DC3StringValueDescription_YesNoLetter);

	LowRRValue=
		getDataElementType3(
			list,DC3TagFromName(LowRRValue),
			0,
			"NMMultiGatedAcquisitionImage","LowRRValue");

	HighRRValue=
		getDataElementType3(
			list,DC3TagFromName(HighRRValue),
			0,
			"NMMultiGatedAcquisitionImage","HighRRValue");

	IntervalsAcquired=
		getDataElementType3(
			list,DC3TagFromName(IntervalsAcquired),
			0,
			"NMMultiGatedAcquisitionImage","IntervalsAcquired");

	IntervalsRejected=
		getDataElementType3(
			list,DC3TagFromName(IntervalsRejected),
			0,
			"NMMultiGatedAcquisitionImage","IntervalsRejected");

	PVCRejection=
		getDataElementType3(
			list,DC3TagFromName(PVCRejection),
			0,
			"NMMultiGatedAcquisitionImage","PVCRejection");

	SkipBeats=
		getDataElementType3(
			list,DC3TagFromName(SkipBeats),
			0,
			"NMMultiGatedAcquisitionImage","SkipBeats");

	HeartRate=
		getDataElementType3(
			list,DC3TagFromName(HeartRate),
			0,
			"NMMultiGatedAcquisitionImage","HeartRate");

	CardiacNumberOfImages=
		getDataElementType3(
			list,DC3TagFromName(CardiacNumberOfImages),
			0,
			"NMMultiGatedAcquisitionImage","CardiacNumberOfImages");

}

char *
DC3Module_USFrameOfReference::Identify(void)
{
	return "USFrameOfReference";
}

DC3Module_USFrameOfReference::DC3Module_USFrameOfReference(DC3ListofAttributes *list)
{
	(void)list;
	RegionLocationMinX0=
		getDataElementType1(
			list,DC3TagFromName(RegionLocationMinX0),
			0,
			"USFrameOfReference","RegionLocationMinX0");

	RegionLocationMinY0=
		getDataElementType1(
			list,DC3TagFromName(RegionLocationMinY0),
			0,
			"USFrameOfReference","RegionLocationMinY0");

	RegionLocationMaxX1=
		getDataElementType1(
			list,DC3TagFromName(RegionLocationMaxX1),
			0,
			"USFrameOfReference","RegionLocationMaxX1");

	RegionLocationMaxY1=
		getDataElementType1(
			list,DC3TagFromName(RegionLocationMaxY1),
			0,
			"USFrameOfReference","RegionLocationMaxY1");

	PhysicalUnitsXDirection=
		getDataElementType1(
			list,DC3TagFromName(PhysicalUnitsXDirection),
			0,
			"USFrameOfReference","PhysicalUnitsXDirection");

	PhysicalUnitsYDirection=
		getDataElementType1(
			list,DC3TagFromName(PhysicalUnitsYDirection),
			0,
			"USFrameOfReference","PhysicalUnitsYDirection");

	PhysicalDeltaX=
		getDataElementType1(
			list,DC3TagFromName(PhysicalDeltaX),
			0,
			"USFrameOfReference","PhysicalDeltaX");

	PhysicalDeltaY=
		getDataElementType1(
			list,DC3TagFromName(PhysicalDeltaY),
			0,
			"USFrameOfReference","PhysicalDeltaY");

	ReferencePixelX0=
		getDataElementType3(
			list,DC3TagFromName(ReferencePixelX0),
			0,
			"USFrameOfReference","ReferencePixelX0");

	ReferencePixelY0=
		getDataElementType3(
			list,DC3TagFromName(ReferencePixelY0),
			0,
			"USFrameOfReference","ReferencePixelY0");

	ReferencePixelPhysicalValueX=
		getDataElementType3(
			list,DC3TagFromName(ReferencePixelPhysicalValueX),
			0,
			"USFrameOfReference","ReferencePixelPhysicalValueX");

	ReferencePixelPhysicalValueY=
		getDataElementType3(
			list,DC3TagFromName(ReferencePixelPhysicalValueY),
			0,
			"USFrameOfReference","ReferencePixelPhysicalValueY");

}

char *
DC3Module_USRegionCalibration::Identify(void)
{
	return "USRegionCalibration";
}

DC3Module_USRegionCalibration::DC3Module_USRegionCalibration(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_USImage::Identify(void)
{
	return "USImage";
}

DC3Module_USImage::DC3Module_USImage(DC3ListofAttributes *list)
{
	(void)list;
	PhotometricInterpretation=
		getDataElementType1(
			list,DC3TagFromName(PhotometricInterpretation),
			0,
			"USImage","PhotometricInterpretation");
	DC3VerifyStringDefinedTerms(PhotometricInterpretation,
		DC3StringValueDescription_USPhotometricInterpretation);

	PixelRepresentation=
		getDataElementType1(
			list,DC3TagFromName(PixelRepresentation),
			0,
			"USImage","PixelRepresentation");
	DC3VerifyBinaryEnumValues(PixelRepresentation,
		DC3BinaryValueDescription_PixelRepresentationUnsigned);

	FrameIncrementPointer=
		getDataElementType1C(
			list,DC3TagFromName(FrameIncrementPointer),
			DC3Condition_Never, 0,
			"USImage","FrameIncrementPointer");

	ImageType=
		getDataElementType2(
			list,DC3TagFromName(ImageType),
			0,
			"USImage","ImageType");

	NumberOfStages=
		getDataElementType2C(
			list,DC3TagFromName(NumberOfStages),
			DC3Condition_Never, 0,
			"USImage","NumberOfStages");

	NumberOfViewsInStage=
		getDataElementType2C(
			list,DC3TagFromName(NumberOfViewsInStage),
			DC3Condition_Never, 0,
			"USImage","NumberOfViewsInStage");

	StageName=
		getDataElementUntyped(
			list,DC3TagFromName(StageName),
			0,
			"USImage","StageName");

	StageNumber=
		getDataElementType3(
			list,DC3TagFromName(StageNumber),
			0,
			"USImage","StageNumber");

	ViewNumber=
		getDataElementType3(
			list,DC3TagFromName(ViewNumber),
			0,
			"USImage","ViewNumber");

	NumberOfEventTimers=
		getDataElementType3(
			list,DC3TagFromName(NumberOfEventTimers),
			0,
			"USImage","NumberOfEventTimers");

	EventElapsedTime=
		getDataElementType3(
			list,DC3TagFromName(EventElapsedTime),
			0,
			"USImage","EventElapsedTime");

	EventTimerName=
		getDataElementType3(
			list,DC3TagFromName(EventTimerName),
			0,
			"USImage","EventTimerName");

	TransducerPosition=
		getDataElementType3(
			list,DC3TagFromName(TransducerPosition),
			0,
			"USImage","TransducerPosition");
	DC3VerifyStringDefinedTerms(TransducerPosition,
		DC3StringValueDescription_USTransducerPosition);

	TransducerOrientation=
		getDataElementType3(
			list,DC3TagFromName(TransducerOrientation),
			0,
			"USImage","TransducerOrientation");
	DC3VerifyStringDefinedTerms(TransducerOrientation,
		DC3StringValueDescription_USTransducerOrientation);

	AnatomicStructure=
		getDataElementType3(
			list,DC3TagFromName(AnatomicStructure),
			0,
			"USImage","AnatomicStructure");
	DC3VerifyStringDefinedTerms(AnatomicStructure,
		DC3StringValueDescription_USAnatomicStructure);

	TriggerTime=
		getDataElementType3(
			list,DC3TagFromName(TriggerTime),
			0,
			"USImage","TriggerTime");

	NominalInterval=
		getDataElementType3(
			list,DC3TagFromName(NominalInterval),
			0,
			"USImage","NominalInterval");

	BeatRejectionFlag=
		getDataElementType3(
			list,DC3TagFromName(BeatRejectionFlag),
			0,
			"USImage","BeatRejectionFlag");
	DC3VerifyStringEnumValues(BeatRejectionFlag,
		DC3StringValueDescription_YesNoLetter);

	LowRRValue=
		getDataElementType3(
			list,DC3TagFromName(LowRRValue),
			0,
			"USImage","LowRRValue");

	HighRRValue=
		getDataElementType3(
			list,DC3TagFromName(HighRRValue),
			0,
			"USImage","HighRRValue");

	HeartRate=
		getDataElementType3(
			list,DC3TagFromName(HeartRate),
			0,
			"USImage","HeartRate");

	OutputPower=
		getDataElementType3(
			list,DC3TagFromName(OutputPower),
			0,
			"USImage","OutputPower");

	TransducerData=
		getDataElementType3(
			list,DC3TagFromName(TransducerData),
			0,
			"USImage","TransducerData");

	TransducerType=
		getDataElementType3(
			list,DC3TagFromName(TransducerType),
			0,
			"USImage","TransducerType");
	DC3VerifyStringDefinedTerms(TransducerType,
		DC3StringValueDescription_USTransducerType);

	FocusDepth=
		getDataElementType3(
			list,DC3TagFromName(FocusDepth),
			0,
			"USImage","FocusDepth");

	PreprocessingFunction=
		getDataElementType3(
			list,DC3TagFromName(PreprocessingFunction),
			0,
			"USImage","PreprocessingFunction");

	MechanicalIndex=
		getDataElementType3(
			list,DC3TagFromName(MechanicalIndex),
			0,
			"USImage","MechanicalIndex");

	ThermalIndex=
		getDataElementType3(
			list,DC3TagFromName(ThermalIndex),
			0,
			"USImage","ThermalIndex");

	CranialThermalIndex=
		getDataElementType3(
			list,DC3TagFromName(CranialThermalIndex),
			0,
			"USImage","CranialThermalIndex");

	SoftTissueThermalIndex=
		getDataElementType3(
			list,DC3TagFromName(SoftTissueThermalIndex),
			0,
			"USImage","SoftTissueThermalIndex");

	SoftTissueFocusThermalIndex=
		getDataElementType3(
			list,DC3TagFromName(SoftTissueFocusThermalIndex),
			0,
			"USImage","SoftTissueFocusThermalIndex");

	SoftTissueSurfaceThermalIndex=
		getDataElementType3(
			list,DC3TagFromName(SoftTissueSurfaceThermalIndex),
			0,
			"USImage","SoftTissueSurfaceThermalIndex");

	DepthOfScanField=
		getDataElementType3(
			list,DC3TagFromName(DepthOfScanField),
			0,
			"USImage","DepthOfScanField");

	ImageTransformationMatrix=
		getDataElementType3(
			list,DC3TagFromName(ImageTransformationMatrix),
			0,
			"USImage","ImageTransformationMatrix");

	ImageTranslationVector=
		getDataElementType3(
			list,DC3TagFromName(ImageTranslationVector),
			0,
			"USImage","ImageTranslationVector");

}

char *
DC3Module_SCImageEquipment::Identify(void)
{
	return "SCImageEquipment";
}

DC3Module_SCImageEquipment::DC3Module_SCImageEquipment(DC3ListofAttributes *list)
{
	(void)list;
	ConversionType=
		getDataElementType1(
			list,DC3TagFromName(ConversionType),
			0,
			"SCImageEquipment","ConversionType");
	DC3VerifyStringDefinedTerms(ConversionType,
		DC3StringValueDescription_ConversionType);

	Modality=
		getDataElementType3(
			list,DC3TagFromName(Modality),
			0,
			"SCImageEquipment","Modality");
	DC3VerifyStringEnumValues(Modality,
		DC3StringValueDescription_Modality);

	SecondaryCaptureDeviceID=
		getDataElementType3(
			list,DC3TagFromName(SecondaryCaptureDeviceID),
			0,
			"SCImageEquipment","SecondaryCaptureDeviceID");

	SecondaryCaptureDeviceManufacturer=
		getDataElementType3(
			list,DC3TagFromName(SecondaryCaptureDeviceManufacturer),
			0,
			"SCImageEquipment","SecondaryCaptureDeviceManufacturer");

	SecondaryCaptureDeviceManufacturerModelName=
		getDataElementType3(
			list,DC3TagFromName(SecondaryCaptureDeviceManufacturerModelName),
			0,
			"SCImageEquipment","SecondaryCaptureDeviceManufacturerModelName");

	SecondaryCaptureDeviceSoftwareVersion=
		getDataElementType3(
			list,DC3TagFromName(SecondaryCaptureDeviceSoftwareVersion),
			0,
			"SCImageEquipment","SecondaryCaptureDeviceSoftwareVersion");

	VideoImageFormatAcquired=
		getDataElementType3(
			list,DC3TagFromName(VideoImageFormatAcquired),
			0,
			"SCImageEquipment","VideoImageFormatAcquired");

	DigitalImageFormatAcquired=
		getDataElementType3(
			list,DC3TagFromName(DigitalImageFormatAcquired),
			0,
			"SCImageEquipment","DigitalImageFormatAcquired");

}

char *
DC3Module_SCImage::Identify(void)
{
	return "SCImage";
}

DC3Module_SCImage::DC3Module_SCImage(DC3ListofAttributes *list)
{
	(void)list;
	DateOfSecondaryCapture=
		getDataElementType3(
			list,DC3TagFromName(DateOfSecondaryCapture),
			0,
			"SCImage","DateOfSecondaryCapture");

	TimeOfSecondaryCapture=
		getDataElementType3(
			list,DC3TagFromName(TimeOfSecondaryCapture),
			0,
			"SCImage","TimeOfSecondaryCapture");

}

char *
DC3Module_OverlayIdentification::Identify(void)
{
	return "OverlayIdentification";
}

DC3Module_OverlayIdentification::DC3Module_OverlayIdentification(DC3ListofAttributes *list)
{
	(void)list;
	OverlayNumber=
		getDataElementType2(
			list,DC3TagFromName(OverlayNumber),
			0,
			"OverlayIdentification","OverlayNumber");

	OverlayDate=
		getDataElementType3(
			list,DC3TagFromName(OverlayDate),
			0,
			"OverlayIdentification","OverlayDate");

	OverlayTime=
		getDataElementType3(
			list,DC3TagFromName(OverlayTime),
			0,
			"OverlayIdentification","OverlayTime");

}

char *
DC3Module_OverlayPlane::Identify(void)
{
	return "OverlayPlane";
}

DC3Module_OverlayPlane::DC3Module_OverlayPlane(DC3ListofAttributes *list)
{
	(void)list;
	OverlayRows=
		getDataElementType1(
			list,DC3TagFromName(OverlayRows),
			0,
			"OverlayPlane","OverlayRows");

	OverlayColumns=
		getDataElementType1(
			list,DC3TagFromName(OverlayColumns),
			0,
			"OverlayPlane","OverlayColumns");

	OverlayType=
		getDataElementType1(
			list,DC3TagFromName(OverlayType),
			0,
			"OverlayPlane","OverlayType");
	DC3VerifyStringEnumValues(OverlayType,
		DC3StringValueDescription_OverlayType);

	OverlayOrigin=
		getDataElementType1(
			list,DC3TagFromName(OverlayOrigin),
			0,
			"OverlayPlane","OverlayOrigin");

	OverlayBitsAllocated=
		getDataElementType1(
			list,DC3TagFromName(OverlayBitsAllocated),
			0,
			"OverlayPlane","OverlayBitsAllocated");

	OverlayBitPosition=
		getDataElementType1(
			list,DC3TagFromName(OverlayBitPosition),
			0,
			"OverlayPlane","OverlayBitPosition");

	OverlayData=
		getDataElementType1C(
			list,DC3TagFromName(OverlayData),
			DC3Condition_Never, 0,
			"OverlayPlane","OverlayData");

	ROIArea=
		getDataElementType3(
			list,DC3TagFromName(ROIArea),
			0,
			"OverlayPlane","ROIArea");

	ROIMean=
		getDataElementType3(
			list,DC3TagFromName(ROIMean),
			0,
			"OverlayPlane","ROIMean");

	ROIStandardDeviation=
		getDataElementType3(
			list,DC3TagFromName(ROIStandardDeviation),
			0,
			"OverlayPlane","ROIStandardDeviation");

	OverlayDescriptorGray=
		getDataElementType3(
			list,DC3TagFromName(OverlayDescriptorGray),
			0,
			"OverlayPlane","OverlayDescriptorGray");

	OverlayDescriptorRed=
		getDataElementType3(
			list,DC3TagFromName(OverlayDescriptorRed),
			0,
			"OverlayPlane","OverlayDescriptorRed");

	OverlayDescriptorGreen=
		getDataElementType3(
			list,DC3TagFromName(OverlayDescriptorGreen),
			0,
			"OverlayPlane","OverlayDescriptorGreen");

	OverlayDescriptorBlue=
		getDataElementType3(
			list,DC3TagFromName(OverlayDescriptorBlue),
			0,
			"OverlayPlane","OverlayDescriptorBlue");

	OverlayGray=
		getDataElementType3(
			list,DC3TagFromName(OverlayGray),
			0,
			"OverlayPlane","OverlayGray");

	OverlayRed=
		getDataElementType3(
			list,DC3TagFromName(OverlayRed),
			0,
			"OverlayPlane","OverlayRed");

	OverlayGreen=
		getDataElementType3(
			list,DC3TagFromName(OverlayGreen),
			0,
			"OverlayPlane","OverlayGreen");

	OverlayBlue=
		getDataElementType3(
			list,DC3TagFromName(OverlayBlue),
			0,
			"OverlayPlane","OverlayBlue");

}

char *
DC3Module_MultiFrameOverlay::Identify(void)
{
	return "MultiFrameOverlay";
}

DC3Module_MultiFrameOverlay::DC3Module_MultiFrameOverlay(DC3ListofAttributes *list)
{
	(void)list;
	OverlayNumberOfFrames=
		getDataElementType1(
			list,DC3TagFromName(OverlayNumberOfFrames),
			0,
			"MultiFrameOverlay","OverlayNumberOfFrames");

}

char *
DC3Module_CurveIdentification::Identify(void)
{
	return "CurveIdentification";
}

DC3Module_CurveIdentification::DC3Module_CurveIdentification(DC3ListofAttributes *list)
{
	(void)list;
	CurveNumber=
		getDataElementType2(
			list,DC3TagFromName(CurveNumber),
			0,
			"CurveIdentification","CurveNumber");

	CurveDate=
		getDataElementType3(
			list,DC3TagFromName(CurveDate),
			0,
			"CurveIdentification","CurveDate");

	CurveTime=
		getDataElementType3(
			list,DC3TagFromName(CurveTime),
			0,
			"CurveIdentification","CurveTime");

}

char *
DC3Module_Curve::Identify(void)
{
	return "Curve";
}

DC3Module_Curve::DC3Module_Curve(DC3ListofAttributes *list)
{
	(void)list;
	CurveDimensions=
		getDataElementType1(
			list,DC3TagFromName(CurveDimensions),
			0,
			"Curve","CurveDimensions");

	NumberOfPoints=
		getDataElementType1(
			list,DC3TagFromName(NumberOfPoints),
			0,
			"Curve","NumberOfPoints");

	TypeOfData=
		getDataElementType1(
			list,DC3TagFromName(TypeOfData),
			0,
			"Curve","TypeOfData");
	DC3VerifyStringDefinedTerms(TypeOfData,
		DC3StringValueDescription_CurveTypeOfData);

	DataValueRepresentation=
		getDataElementType1(
			list,DC3TagFromName(DataValueRepresentation),
			0,
			"Curve","DataValueRepresentation");
	DC3VerifyBinaryEnumValues(DataValueRepresentation,
		DC3BinaryValueDescription_CurveDataValueRepresentation);

	CurveData=
		getDataElementType1(
			list,DC3TagFromName(CurveData),
			0,
			"Curve","CurveData");

	CurveDescription=
		getDataElementType3(
			list,DC3TagFromName(CurveDescription),
			0,
			"Curve","CurveDescription");

	AxisUnits=
		getDataElementType3(
			list,DC3TagFromName(AxisUnits),
			0,
			"Curve","AxisUnits");
	DC3VerifyStringDefinedTerms(AxisUnits,
		DC3StringValueDescription_CurveAxisUnits);

	AxisLabels=
		getDataElementType3(
			list,DC3TagFromName(AxisLabels),
			0,
			"Curve","AxisLabels");

	MinimumCoordinateValue=
		getDataElementType3(
			list,DC3TagFromName(MinimumCoordinateValue),
			0,
			"Curve","MinimumCoordinateValue");

	MaximumCoordinateValue=
		getDataElementType3(
			list,DC3TagFromName(MaximumCoordinateValue),
			0,
			"Curve","MaximumCoordinateValue");

	CurveRange=
		getDataElementType3(
			list,DC3TagFromName(CurveRange),
			0,
			"Curve","CurveRange");

	CurveDataDescriptor=
		getDataElementType1C(
			list,DC3TagFromName(CurveDataDescriptor),
			DC3Condition_Never, 0,
			"Curve","CurveDataDescriptor");
	DC3VerifyBinaryEnumValues(CurveDataDescriptor,
		DC3BinaryValueDescription_CurveDataDescriptor);

	CoordinateStartValue=
		getDataElementType1C(
			list,DC3TagFromName(CoordinateStartValue),
			DC3Condition_CurveDataDescriptorPresent, 0,
			"Curve","CoordinateStartValue");

	CoordinateStepValue=
		getDataElementType1C(
			list,DC3TagFromName(CoordinateStepValue),
			DC3Condition_CurveDataDescriptorPresent, 0,
			"Curve","CoordinateStepValue");

}

char *
DC3Module_Audio::Identify(void)
{
	return "Audio";
}

DC3Module_Audio::DC3Module_Audio(DC3ListofAttributes *list)
{
	(void)list;
	AudioType=
		getDataElementType1(
			list,DC3TagFromName(AudioType),
			0,
			"Audio","AudioType");
	DC3VerifyBinaryEnumValues(AudioType,
		DC3BinaryValueDescription_AudioType);

	AudioSampleFormat=
		getDataElementType1(
			list,DC3TagFromName(AudioSampleFormat),
			0,
			"Audio","AudioSampleFormat");
	DC3VerifyBinaryEnumValues(AudioSampleFormat,
		DC3BinaryValueDescription_AudioSampleFormat);

	NumberOfChannels=
		getDataElementType1(
			list,DC3TagFromName(NumberOfChannels),
			0,
			"Audio","NumberOfChannels");
	DC3VerifyBinaryEnumValues(NumberOfChannels,
		DC3BinaryValueDescription_NumberOfChannels);

	NumberOfSamples=
		getDataElementType1(
			list,DC3TagFromName(NumberOfSamples),
			0,
			"Audio","NumberOfSamples");

	SampleRate=
		getDataElementType1(
			list,DC3TagFromName(SampleRate),
			0,
			"Audio","SampleRate");

	TotalTime=
		getDataElementType1(
			list,DC3TagFromName(TotalTime),
			0,
			"Audio","TotalTime");

	AudioSampleData=
		getDataElementType1(
			list,DC3TagFromName(AudioSampleData),
			0,
			"Audio","AudioSampleData");

	AudioComments=
		getDataElementUntyped(
			list,DC3TagFromName(AudioComments),
			0,
			"Audio","AudioComments");

}

char *
DC3Module_ModalityLUT::Identify(void)
{
	return "ModalityLUT";
}

DC3Module_ModalityLUT::DC3Module_ModalityLUT(DC3ListofAttributes *list)
{
	(void)list;
	RescaleIntercept=
		getDataElementType1C(
			list,DC3TagFromName(RescaleIntercept),
			DC3Condition_ModalityLUTSequenceNotPresent, 0,
			"ModalityLUT","RescaleIntercept");

	RescaleSlope=
		getDataElementType1C(
			list,DC3TagFromName(RescaleSlope),
			DC3Condition_RescaleInterceptPresent, 0,
			"ModalityLUT","RescaleSlope");

	RescaleType=
		getDataElementType1C(
			list,DC3TagFromName(RescaleType),
			DC3Condition_RescaleInterceptPresent, 0,
			"ModalityLUT","RescaleType");

}

char *
DC3Module_VOILUT::Identify(void)
{
	return "VOILUT";
}

DC3Module_VOILUT::DC3Module_VOILUT(DC3ListofAttributes *list)
{
	(void)list;
	WindowCenter=
		getDataElementType3(
			list,DC3TagFromName(WindowCenter),
			0,
			"VOILUT","WindowCenter");

	WindowWidth=
		getDataElementType1C(
			list,DC3TagFromName(WindowWidth),
			DC3Condition_WindowCenterPresent, 0,
			"VOILUT","WindowWidth");

	WindowCenterWidthExplanation=
		getDataElementType3(
			list,DC3TagFromName(WindowCenterWidthExplanation),
			0,
			"VOILUT","WindowCenterWidthExplanation");

}

char *
DC3Module_LUTIdentification::Identify(void)
{
	return "LUTIdentification";
}

DC3Module_LUTIdentification::DC3Module_LUTIdentification(DC3ListofAttributes *list)
{
	(void)list;
	LUTNumber=
		getDataElementType2(
			list,DC3TagFromName(LUTNumber),
			0,
			"LUTIdentification","LUTNumber");

}

char *
DC3Module_SOPCommon::Identify(void)
{
	return "SOPCommon";
}

DC3Module_SOPCommon::DC3Module_SOPCommon(DC3ListofAttributes *list)
{
	(void)list;
	SOPClassUID=
		getDataElementType1C(
			list,DC3TagFromName(SOPClassUID),
			DC3Condition_Always, 0,
			"SOPCommon","SOPClassUID");

	SOPInstanceUID=
		getDataElementType1C(
			list,DC3TagFromName(SOPInstanceUID),
			DC3Condition_Always, 0,
			"SOPCommon","SOPInstanceUID");

	SpecificCharacterSet=
		getDataElementType1C(
			list,DC3TagFromName(SpecificCharacterSet),
			DC3Condition_Never, 0,
			"SOPCommon","SpecificCharacterSet");
	DC3VerifyStringDefinedTerms(SpecificCharacterSet,
		DC3StringValueDescription_SpecificCharacterSet);

	InstanceCreationDate=
		getDataElementType3(
			list,DC3TagFromName(InstanceCreationDate),
			0,
			"SOPCommon","InstanceCreationDate");

	InstanceCreationTime=
		getDataElementType3(
			list,DC3TagFromName(InstanceCreationTime),
			0,
			"SOPCommon","InstanceCreationTime");

	InstanceCreatorUID=
		getDataElementType3(
			list,DC3TagFromName(InstanceCreatorUID),
			0,
			"SOPCommon","InstanceCreatorUID");

}

char *
DC3Module_BasicFilmSessionPresentation::Identify(void)
{
	return "BasicFilmSessionPresentation";
}

DC3Module_BasicFilmSessionPresentation::DC3Module_BasicFilmSessionPresentation(DC3ListofAttributes *list)
{
	(void)list;
	NumberOfCopies=
		getDataElementUntyped(
			list,DC3TagFromName(NumberOfCopies),
			0,
			"BasicFilmSessionPresentation","NumberOfCopies");

	PrintPriority=
		getDataElementUntyped(
			list,DC3TagFromName(PrintPriority),
			0,
			"BasicFilmSessionPresentation","PrintPriority");
	DC3VerifyStringEnumValues(PrintPriority,
		DC3StringValueDescription_Priority);

	MediumType=
		getDataElementUntyped(
			list,DC3TagFromName(MediumType),
			0,
			"BasicFilmSessionPresentation","MediumType");
	DC3VerifyStringDefinedTerms(MediumType,
		DC3StringValueDescription_MediumType);

	FilmDestination=
		getDataElementUntyped(
			list,DC3TagFromName(FilmDestination),
			0,
			"BasicFilmSessionPresentation","FilmDestination");
	DC3VerifyStringEnumValues(FilmDestination,
		DC3StringValueDescription_FilmDestination);

	FilmSessionLabel=
		getDataElementUntyped(
			list,DC3TagFromName(FilmSessionLabel),
			0,
			"BasicFilmSessionPresentation","FilmSessionLabel");

	MemoryAllocation=
		getDataElementUntyped(
			list,DC3TagFromName(MemoryAllocation),
			0,
			"BasicFilmSessionPresentation","MemoryAllocation");

}

char *
DC3Module_BasicFilmSessionRelationship::Identify(void)
{
	return "BasicFilmSessionRelationship";
}

DC3Module_BasicFilmSessionRelationship::DC3Module_BasicFilmSessionRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_BasicFilmBoxPresentation::Identify(void)
{
	return "BasicFilmBoxPresentation";
}

DC3Module_BasicFilmBoxPresentation::DC3Module_BasicFilmBoxPresentation(DC3ListofAttributes *list)
{
	(void)list;
	ImageDisplayFormat=
		getDataElementUntyped(
			list,DC3TagFromName(ImageDisplayFormat),
			0,
			"BasicFilmBoxPresentation","ImageDisplayFormat");
	DC3VerifyStringDefinedTerms(ImageDisplayFormat,
		DC3StringValueDescription_ImageDisplayFormat);

	AnnotationDisplayFormatID=
		getDataElementUntyped(
			list,DC3TagFromName(AnnotationDisplayFormatID),
			0,
			"BasicFilmBoxPresentation","AnnotationDisplayFormatID");

	FilmOrientation=
		getDataElementUntyped(
			list,DC3TagFromName(FilmOrientation),
			0,
			"BasicFilmBoxPresentation","FilmOrientation");
	DC3VerifyStringEnumValues(FilmOrientation,
		DC3StringValueDescription_Orientation);

	FilmSizeID=
		getDataElementUntyped(
			list,DC3TagFromName(FilmSizeID),
			0,
			"BasicFilmBoxPresentation","FilmSizeID");
	DC3VerifyStringDefinedTerms(FilmSizeID,
		DC3StringValueDescription_FilmSizeID);

	MagnificationType=
		getDataElementUntyped(
			list,DC3TagFromName(MagnificationType),
			0,
			"BasicFilmBoxPresentation","MagnificationType");
	DC3VerifyStringDefinedTerms(MagnificationType,
		DC3StringValueDescription_MagnificationType);

	SmoothingType=
		getDataElementUntyped(
			list,DC3TagFromName(SmoothingType),
			0,
			"BasicFilmBoxPresentation","SmoothingType");

	BorderDensity=
		getDataElementUntyped(
			list,DC3TagFromName(BorderDensity),
			0,
			"BasicFilmBoxPresentation","BorderDensity");
	DC3VerifyStringDefinedTerms(BorderDensity,
		DC3StringValueDescription_Density);

	EmptyImageDensity=
		getDataElementUntyped(
			list,DC3TagFromName(EmptyImageDensity),
			0,
			"BasicFilmBoxPresentation","EmptyImageDensity");
	DC3VerifyStringDefinedTerms(EmptyImageDensity,
		DC3StringValueDescription_Density);

	MinDensity=
		getDataElementUntyped(
			list,DC3TagFromName(MinDensity),
			0,
			"BasicFilmBoxPresentation","MinDensity");

	MaxDensity=
		getDataElementUntyped(
			list,DC3TagFromName(MaxDensity),
			0,
			"BasicFilmBoxPresentation","MaxDensity");

	Trim=
		getDataElementUntyped(
			list,DC3TagFromName(Trim),
			0,
			"BasicFilmBoxPresentation","Trim");
	DC3VerifyStringEnumValues(Trim,
		DC3StringValueDescription_YesNoFull);

	ConfigurationInformation=
		getDataElementUntyped(
			list,DC3TagFromName(ConfigurationInformation),
			0,
			"BasicFilmBoxPresentation","ConfigurationInformation");

}

char *
DC3Module_BasicFilmBoxRelationship::Identify(void)
{
	return "BasicFilmBoxRelationship";
}

DC3Module_BasicFilmBoxRelationship::DC3Module_BasicFilmBoxRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_ImageBoxPixelPresentation::Identify(void)
{
	return "ImageBoxPixelPresentation";
}

DC3Module_ImageBoxPixelPresentation::DC3Module_ImageBoxPixelPresentation(DC3ListofAttributes *list)
{
	(void)list;
	ImagePosition=
		getDataElementUntyped(
			list,DC3TagFromName(ImagePosition),
			0,
			"ImageBoxPixelPresentation","ImagePosition");

	Polarity=
		getDataElementUntyped(
			list,DC3TagFromName(Polarity),
			0,
			"ImageBoxPixelPresentation","Polarity");
	DC3VerifyStringEnumValues(Polarity,
		DC3StringValueDescription_Polarity);

	MagnificationType=
		getDataElementUntyped(
			list,DC3TagFromName(MagnificationType),
			0,
			"ImageBoxPixelPresentation","MagnificationType");
	DC3VerifyStringDefinedTerms(MagnificationType,
		DC3StringValueDescription_MagnificationType);

	SmoothingType=
		getDataElementUntyped(
			list,DC3TagFromName(SmoothingType),
			0,
			"ImageBoxPixelPresentation","SmoothingType");

	RequestedImageSize=
		getDataElementUntyped(
			list,DC3TagFromName(RequestedImageSize),
			0,
			"ImageBoxPixelPresentation","RequestedImageSize");

}

char *
DC3Module_ImageBoxRelationship::Identify(void)
{
	return "ImageBoxRelationship";
}

DC3Module_ImageBoxRelationship::DC3Module_ImageBoxRelationship(DC3ListofAttributes *list)
{
	(void)list;
}

char *
DC3Module_BasicAnnotationPresentation::Identify(void)
{
	return "BasicAnnotationPresentation";
}

DC3Module_BasicAnnotationPresentation::DC3Module_BasicAnnotationPresentation(DC3ListofAttributes *list)
{
	(void)list;
	AnnotationPosition=
		getDataElementUntyped(
			list,DC3TagFromName(AnnotationPosition),
			0,
			"BasicAnnotationPresentation","AnnotationPosition");

	TextString=
		getDataElementUntyped(
			list,DC3TagFromName(TextString),
			0,
			"BasicAnnotationPresentation","TextString");

}

char *
DC3Module_PrintJob::Identify(void)
{
	return "PrintJob";
}

DC3Module_PrintJob::DC3Module_PrintJob(DC3ListofAttributes *list)
{
	(void)list;
	ExecutionStatus=
		getDataElementUntyped(
			list,DC3TagFromName(ExecutionStatus),
			0,
			"PrintJob","ExecutionStatus");
	DC3VerifyStringEnumValues(ExecutionStatus,
		DC3StringValueDescription_PrintExecutionStatus);

	ExecutionStatusInfo=
		getDataElementUntyped(
			list,DC3TagFromName(ExecutionStatusInfo),
			0,
			"PrintJob","ExecutionStatusInfo");
	DC3VerifyStringDefinedTerms(ExecutionStatusInfo,
		DC3StringValueDescription_PrintExecutionStatusInfo);

	CreationDate=
		getDataElementUntyped(
			list,DC3TagFromName(CreationDate),
			0,
			"PrintJob","CreationDate");

	CreationTime=
		getDataElementUntyped(
			list,DC3TagFromName(CreationTime),
			0,
			"PrintJob","CreationTime");

	PrintPriority=
		getDataElementUntyped(
			list,DC3TagFromName(PrintPriority),
			0,
			"PrintJob","PrintPriority");

	PrinterName=
		getDataElementUntyped(
			list,DC3TagFromName(PrinterName),
			0,
			"PrintJob","PrinterName");

	Originator=
		getDataElementUntyped(
			list,DC3TagFromName(Originator),
			0,
			"PrintJob","Originator");

}

char *
DC3Module_Printer::Identify(void)
{
	return "Printer";
}

DC3Module_Printer::DC3Module_Printer(DC3ListofAttributes *list)
{
	(void)list;
	PrinterStatus=
		getDataElementUntyped(
			list,DC3TagFromName(PrinterStatus),
			0,
			"Printer","PrinterStatus");
	DC3VerifyStringEnumValues(PrinterStatus,
		DC3StringValueDescription_PrinterStatus);

	PrinterStatusInfo=
		getDataElementUntyped(
			list,DC3TagFromName(PrinterStatusInfo),
			0,
			"Printer","PrinterStatusInfo");
	DC3VerifyStringDefinedTerms(PrinterStatusInfo,
		DC3StringValueDescription_PrinterStatusInfo);

	PrinterName=
		getDataElementUntyped(
			list,DC3TagFromName(PrinterName),
			0,
			"Printer","PrinterName");

	Manufacturer=
		getDataElementUntyped(
			list,DC3TagFromName(Manufacturer),
			0,
			"Printer","Manufacturer");

	ManufacturerModelName=
		getDataElementUntyped(
			list,DC3TagFromName(ManufacturerModelName),
			0,
			"Printer","ManufacturerModelName");

	DeviceSerialNumber=
		getDataElementUntyped(
			list,DC3TagFromName(DeviceSerialNumber),
			0,
			"Printer","DeviceSerialNumber");

	SoftwareVersion=
		getDataElementUntyped(
			list,DC3TagFromName(SoftwareVersion),
			0,
			"Printer","SoftwareVersion");

	DateOfLastCalibration=
		getDataElementUntyped(
			list,DC3TagFromName(DateOfLastCalibration),
			0,
			"Printer","DateOfLastCalibration");

	TimeOfLastCalibration=
		getDataElementUntyped(
			list,DC3TagFromName(TimeOfLastCalibration),
			0,
			"Printer","TimeOfLastCalibration");

}

char *
DC3Module_ImageOverlayBoxPresentation::Identify(void)
{
	return "ImageOverlayBoxPresentation";
}

DC3Module_ImageOverlayBoxPresentation::DC3Module_ImageOverlayBoxPresentation(DC3ListofAttributes *list)
{
	(void)list;
	OverlayMagnificationType=
		getDataElementUntyped(
			list,DC3TagFromName(OverlayMagnificationType),
			0,
			"ImageOverlayBoxPresentation","OverlayMagnificationType");
	DC3VerifyStringDefinedTerms(OverlayMagnificationType,
		DC3StringValueDescription_MagnificationType);

	OverlaySmoothingType=
		getDataElementUntyped(
			list,DC3TagFromName(OverlaySmoothingType),
			0,
			"ImageOverlayBoxPresentation","OverlaySmoothingType");

	OverlayForegroundDensity=
		getDataElementUntyped(
			list,DC3TagFromName(OverlayForegroundDensity),
			0,
			"ImageOverlayBoxPresentation","OverlayForegroundDensity");
	DC3VerifyStringDefinedTerms(OverlayForegroundDensity,
		DC3StringValueDescription_Density);

	OverlayMode=
		getDataElementUntyped(
			list,DC3TagFromName(OverlayMode),
			0,
			"ImageOverlayBoxPresentation","OverlayMode");
	DC3VerifyStringDefinedTerms(OverlayMode,
		DC3StringValueDescription_OverlayMode);

	ThresholdDensity=
		getDataElementUntyped(
			list,DC3TagFromName(ThresholdDensity),
			0,
			"ImageOverlayBoxPresentation","ThresholdDensity");
	DC3VerifyStringDefinedTerms(ThresholdDensity,
		DC3StringValueDescription_Density);

}

char *
DC3Module_ImageOverlayBoxRelationship::Identify(void)
{
	return "ImageOverlayBoxRelationship";
}

DC3Module_ImageOverlayBoxRelationship::DC3Module_ImageOverlayBoxRelationship(DC3ListofAttributes *list)
{
	(void)list;
}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
