/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by strval.awk with options method

#include "tstrvalt.h"
#include "tstrval.h"

static struct DC3StringValueEntry
DC3StringValueTable_YesNoLetter[] = {
	"Y",	"Yes",
	"N",	"No",
	0,0
};

char *
DC3StringValueDescription_YesNoLetter(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_YesNoLetter,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_YesNoFull[] = {
	"YES",	"",
	"NO",	"",
	0,0
};

char *
DC3StringValueDescription_YesNoFull(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_YesNoFull,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Priority[] = {
	"LOW",	"",
	"MED",	"",
	"HIGH",	"",
	0,0
};

char *
DC3StringValueDescription_Priority(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Priority,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_SmokingStatus[] = {
	"YES",	"",
	"NO",	"",
	"UNKNOWN",	"",
	0,0
};

char *
DC3StringValueDescription_SmokingStatus(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_SmokingStatus,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Orientation[] = {
	"LANDSCAPE",	"",
	"PORTRAIT",	"",
	0,0
};

char *
DC3StringValueDescription_Orientation(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Orientation,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_DiagnosticCodingSchemes[] = {
	"ACR",	"ACR Inex for Radiological Diagnosis",
	"CE",	"CEN ECG Diagnostic Codes",
	"E",	"Euclides",
	"I9",	"ICD9",
	"I9C",	"ICD9-CM",
	"I10",	"ICD10",
	"LB",	"Local Billing Code",
	"RC",	"Read Classification",
	"SNM",	"SNOMED",
	"S3",	"SNOMED III",
	"UML",	"Unified Medical Language",
	0,0
};

char *
DC3StringValueDescription_DiagnosticCodingSchemes(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_DiagnosticCodingSchemes,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ProcedureCodeScheme[] = {
	"AS4",	"ASTM",
	"C4",	"CPT-4",
	"C5",	"CPT-5",
	"E",	"Euclides",
	"FDK",	"FDA K10",
	"HB",	"HIBCC",
	"ICS",	"ICCS",
	"I9C",	"ICD-9CM",
	"IBT",	"ISBT",
	"IUC",	"IUPAC/IFCC",
	"MCR",	"Medicare",
	"MCD",	"Madicaid",
	"UC",	"UCDS",
	"JC8",	"Japanese Chemistry",
	"HI",	"Health Outcomes",
	"E6",	"Euclides Lab Method Codes",
	"E7",	"Euclides Lab Equipment Codes",
	"E5",	"Euclides Kind Of Quantity Codes",
	"CAS",	"Chemical Abstract Codes",
	"NDC",	"National Drug Codes",
	"W1",	"WHO Record Number 6 Digit Drug Codes",
	"W2",	"WHO Record Number 8 Digit Drug Codes",
	"W4",	"WHO Record Number With ASTM Extensions",
	"WC",	"WHO ATC",
	"UMD",	"MDNS",
	0,0
};

char *
DC3StringValueDescription_ProcedureCodeScheme(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ProcedureCodeScheme,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_VisitStatusID[] = {
	"CREATED",	"",
	"SCHEDULED",	"",
	"ADMITTED",	"",
	"DISCHARGED",	"",
	0,0
};

char *
DC3StringValueDescription_VisitStatusID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_VisitStatusID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_StudyStatusID[] = {
	"CREATED",	"",
	"SCHEDULED",	"",
	"ARRIVED",	"",
	"STARTED",	"",
	"COMPLETED",	"",
	"VERIFIED",	"",
	"READ",	"",
	0,0
};

char *
DC3StringValueDescription_StudyStatusID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_StudyStatusID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_StudyComponentStatusID[] = {
	"CREATED",	"",
	"INCOMPLETE",	"",
	"COMPLETED",	"",
	"VERIFIED",	"",
	"POSTINTERPRET",	"",
	0,0
};

char *
DC3StringValueDescription_StudyComponentStatusID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_StudyComponentStatusID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_InterpretationTypeID[] = {
	"REPORT",	"",
	"AMMENDMENT",	"",
	0,0
};

char *
DC3StringValueDescription_InterpretationTypeID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_InterpretationTypeID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_InterpretationStatusID[] = {
	"CREATED",	"",
	"RECORDED",	"",
	"TRANSCRIBED",	"",
	"APPROVED",	"",
	0,0
};

char *
DC3StringValueDescription_InterpretationStatusID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_InterpretationStatusID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Sex[] = {
	"M",	"Male",
	"F",	"Female",
	"O",	"Other",
	0,0
};

char *
DC3StringValueDescription_Sex(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Sex,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Laterality[] = {
	"R",	"Right",
	"L",	"Left",
	0,0
};

char *
DC3StringValueDescription_Laterality(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Laterality,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_BodyPartExamined[] = {
	"SKULL",	"",
	"CSPINE",	"",
	"TSPINE",	"",
	"LSPINE",	"",
	"SSPINE",	"",
	"COCCYX",	"",
	"CHEST",	"",
	"CLAVICLE",	"",
	"BREAST",	"",
	"ABDOMEN",	"",
	"PELVIS",	"",
	"HIP",	"",
	"SHOULDER",	"",
	"ELBOW",	"",
	"KNEE",	"",
	"ANKLE",	"",
	"HAND",	"",
	"FOOT",	"",
	"EXTREMITY",	"",
	0,0
};

char *
DC3StringValueDescription_BodyPartExamined(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_BodyPartExamined,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Modality[] = {
	"CR",	"Computed Radiography",
	"CT",	"Computed Tomography",
	"DS",	"Digital Subtraction Angiography",
	"MR",	"Magnetic Resonance",
	"NM",	"Nuclear Medicine",
	"US",	"Ultrasound",
	"OT",	"Other",
	"AS",	"Angioscopy",
	"BI",	"Biomagnetic Imaging",
	"CD",	"Color Flow Doppler",
	"CF",	"Cinefluorography",
	"CP",	"Culposcopy",
	"CS",	"Cystoscopy",
	"DD",	"Duplex Doppler",
	"DF",	"Digital Fluoroscopy",
	"DG",	"Diaphanography",
	"DM",	"Digital Microscopy",
	"EC",	"Echocardiography",
	"ES",	"Endoscopy",
	"FA",	"Flouroscein Angiography",
	"FS",	"Fundoscopy",
	"LP",	"Laparoscopy",
	"LS",	"Laser Surface Scan",
	"MA",	"Magnetic Resonance Angiography",
	"MS",	"Magnetic Resonance Spectroscopy",
	"PT",	"Positron Emmission Tomography",
	"RG",	"Radiographic Imaging Conventional Film Screen",
	"ST",	"Single Photon Emission Computed Tomography",
	"TG",	"Thermography",
	"VG",	"Videofluorography",
	0,0
};

char *
DC3StringValueDescription_Modality(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Modality,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PatientPosition[] = {
	"HFP",	"Head First Prone",
	"HFS",	"Head First Supine",
	"HFDR",	"Head First Decubitus Right",
	"HFDL",	"Head First Decubitus Right",
	"FFP",	"Feet First Prone",
	"FFS",	"Feet First Supine",
	"FFDR",	"Feet First Decubitus Right",
	"FFDL",	"Feet First Decubitus Right",
	0,0
};

char *
DC3StringValueDescription_PatientPosition(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PatientPosition,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ViewPosition[] = {
	"AP",	"Anterior Posterior",
	"PA",	"Posterior Anterior",
	"LL",	"Left Lateral",
	"RL",	"Right Lateral",
	"RLD",	"Right Lateral Decubitus",
	"LLD",	"Left Lateral Decubitus",
	"RLO",	"Right Lateral Oblique",
	"LLO",	"Left Lateral Oblique",
	0,0
};

char *
DC3StringValueDescription_ViewPosition(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ViewPosition,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CassetteSize[] = {
	"18CMX24CM",	"",
	"8INX10IN",	"",
	"24CMX30CM",	"",
	"10INX12IN",	"",
	"30CMX35CM",	"",
	"30CMX40CM",	"",
	"11INX14IN",	"",
	"35CMX35CM",	"",
	"14INX14IN",	"",
	"35CMX43CM",	"",
	"14INX17IN",	"",
	0,0
};

char *
DC3StringValueDescription_CassetteSize(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CassetteSize,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_RotationDirection[] = {
	"CW",	"Clockwise",
	"CC",	"CounterClockwise",
	0,0
};

char *
DC3StringValueDescription_RotationDirection(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_RotationDirection,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ScanningSequence[] = {
	"SE",	"Spin Echo",
	"IR",	"Inversion Recovery",
	"GR",	"Gradient Recalled",
	"EP",	"Echo Planar",
	"RM",	"Research Mode",
	0,0
};

char *
DC3StringValueDescription_ScanningSequence(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ScanningSequence,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_SequenceVariant[] = {
	"SK",	"Segmented K Space",
	"MTC",	"Magnetization Transfer CDontrast",
	"SS",	"Steady State",
	"TRSS",	"Time Reversed Steady State",
	"SP",	"Spoiled",
	"MP",	"Magnetization Prepared",
	"OSP",	"Oversampling Phase",
	"NONE",	"No Sequence Variant",
	0,0
};

char *
DC3StringValueDescription_SequenceVariant(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_SequenceVariant,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ScanOptions[] = {
	"PER",	"Phase Encode Reordering",
	"RG",	"Respiratory Gating",
	"CG",	"Cardiac Gating",
	"PPG",	"Peripheral Pulse Gating",
	"FC",	"Flow Compensation",
	"PFF",	"Partial Fourier Frequency",
	"PFP",	"Partial Fourier Phase",
	"SP",	"Spatial Presaturation",
	"FS",	"Fat Saturation",
	0,0
};

char *
DC3StringValueDescription_ScanOptions(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ScanOptions,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_MRAcquisitionType[] = {
	"2D",	"Frequency x Phase",
	"3D",	"Frequency x Phase x Phase",
	0,0
};

char *
DC3StringValueDescription_MRAcquisitionType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_MRAcquisitionType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_AngioFlag[] = {
	"Y",	"Image is Angio",
	"N",	"Image is not Angio",
	0,0
};

char *
DC3StringValueDescription_AngioFlag(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_AngioFlag,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PhaseEncodingDirection[] = {
	"ROW",	"Phase Encoded in Rows",
	"COL",	"Phase Encoded in Columns",
	0,0
};

char *
DC3StringValueDescription_PhaseEncodingDirection(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PhaseEncodingDirection,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_NuclearMedicineSeriesType[] = {
	"STATIC",	"",
	"DYNAMIC",	"",
	"GATED",	"",
	"WHOLE BODY",	"",
	"STEP",	"",
	"CONTINUOUS TOMO",	"",
	"GATED TOMO",	"",
	0,0
};

char *
DC3StringValueDescription_NuclearMedicineSeriesType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_NuclearMedicineSeriesType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_WholeBodyTechnique[] = {
	"1PS",	"One Pass",
	"2PS",	"Two Pass",
	"PCN",	"Patient Contour Following Employed",
	"DIV",	"Diverging Collimator Used",
	"MSP",	"Multiple Static Images Collected Into a Whole Body Image",
	0,0
};

char *
DC3StringValueDescription_WholeBodyTechnique(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_WholeBodyTechnique,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_FieldOfViewShape[] = {
	"RECTANGLE",	"",
	"ROUND",	"",
	"HEXAGONAL",	"",
	0,0
};

char *
DC3StringValueDescription_FieldOfViewShape(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_FieldOfViewShape,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CollimatorType[] = {
	"PARA",	"Parallel",
	"PINH",	"PinHole",
	"FANB",	"Fan Beam",
	"CONE",	"Cone Beam",
	"SLNT",	"Slant Hole",
	"ASTG",	"Astigmatic",
	0,0
};

char *
DC3StringValueDescription_CollimatorType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CollimatorType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_AcquisitionTerminationCondition[] = {
	"CNTS",	"Counts",
	"DENS",	"Density",
	"MANU",	"Manual",
	"OVFL",	"Data Overflow",
	"TIME",	"Time",
	"TRIG",	"Physiological Trigger",
	0,0
};

char *
DC3StringValueDescription_AcquisitionTerminationCondition(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_AcquisitionTerminationCondition,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CorrectedImage[] = {
	"UNIF",	"Flood Corrected",
	"COR",	"Center of Rotation Corrected",
	"NCO",	"Non-circular Orbit Corrected",
	"DECY",	"Decay Corrected",
	"ATTN",	"Attenuation Corrected",
	"SCAT",	"Scatter Corrected",
	"DTIM",	"Dead Time Corrected",
	0,0
};

char *
DC3StringValueDescription_CorrectedImage(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CorrectedImage,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PhotometricInterpretation[] = {
	"MONOCHROME1",	"",
	"MONOCHROME2",	"",
	"PALETTE COLOR",	"",
	"RGB",	"",
	"HSV",	"",
	"ARGB",	"",
	"CMYK",	"",
	0,0
};

char *
DC3StringValueDescription_PhotometricInterpretation(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PhotometricInterpretation,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PhotometricInterpretationMonochrome[] = {
	"MONOCHROME1",	"",
	"MONOCHROME2",	"",
	0,0
};

char *
DC3StringValueDescription_PhotometricInterpretationMonochrome(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PhotometricInterpretationMonochrome,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PhotometricInterpretationRGB[] = {
	"RGB",	"",
	0,0
};

char *
DC3StringValueDescription_PhotometricInterpretationRGB(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PhotometricInterpretationRGB,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USPhotometricInterpretation[] = {
	"MONOCHROME2",	"",
	"PALETTE COLOR",	"",
	"RGB",	"",
	"ARGB",	"",
	0,0
};

char *
DC3StringValueDescription_USPhotometricInterpretation(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USPhotometricInterpretation,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ImageType1[] = {
	"ORIGINAL",	"",
	"DERIVED",	"",
	0,0
};

char *
DC3StringValueDescription_ImageType1(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ImageType1,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ImageType2[] = {
	"PRIMARY",	"",
	"SECONDARY",	"",
	0,0
};

char *
DC3StringValueDescription_ImageType2(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ImageType2,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CTImageType3[] = {
	"AXIAL",	"",
	"LOCALIZER",	"",
	0,0
};

char *
DC3StringValueDescription_CTImageType3(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CTImageType3,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_MRImageType3[] = {
	"MPR",	"",
	"PROJECTION IMAGE",	"",
	"T1 MAP",	"",
	"T2 MAP",	"",
	"DIFFUSION MAP",	"",
	"DENSITY MAP",	"",
	"PHASE MAP",	"",
	"VELOCITY MAP",	"",
	"IMAGE ADDITION",	"",
	"PHASE SUBTRACT",	"",
	"MODULUS SUBTRACT",	"",
	"OTHER",	"",
	0,0
};

char *
DC3StringValueDescription_MRImageType3(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_MRImageType3,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USImageType3[] = {
	"ABDOMINAL",	"",
	"BREAST",	"",
	"CHEST",	"",
	"ENDOCAVITARY",	"",
	"ENDORECTAL",	"",
	"ENDOVAGINAL",	"",
	"EPICARDIAL",	"",
	"FETAL HEART",	"",
	"GYNECOLOGY",	"",
	"INTRACARDIAC",	"",
	"INTRAOPERATIVE",	"",
	"INTRAVASCULAR",	"",
	"MUSCULOSKELETAL",	"",
	"NEONATAL HEAD",	"",
	"OBSTETRICAL",	"",
	"OPHTHALMIC",	"",
	"PEDIATRIC",	"",
	"PELVIC",	"",
	"RETROPERITONEAL",	"",
	"SCROTAL",	"",
	"SMALL PARTS",	"",
	"TEE",	"",
	"THYROID",	"",
	"TRANSCRANIAL",	"",
	"TTE",	"",
	"USBIOPSY",	"",
	"VASCULAR",	"",
	0,0
};

char *
DC3StringValueDescription_USImageType3(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USImageType3,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USTransducerPosition[] = {
	"ANTERIOR",	"",
	"AORTA",	"",
	"APICAL",	"",
	"ARTERY",	"",
	"BASAL ESOPHAGUS",	"",
	"BYPASS GRAFT",	"",
	"CAUDAL",	"",
	"CRANIAL",	"",
	"DISTAL",	"",
	"ENDOVAGINAL",	"",
	"ENDORECTAL",	"",
	"EPICARDIAL",	"",
	"ESOPHAGUS",	"",
	"GASTRIC",	"",
	"INFERIOR",	"",
	"L ATRIUM",	"",
	"L CORONARY ART",	"",
	"L LIQ",	"",
	"L LOQ",	"",
	"L PARASTERN",	"",
	"L SUBCLAVIAN",	"",
	"L SUPRACLAVICULAR",	"",
	"L UIQ",	"",
	"L UOQ",	"",
	"L VENTRICLE LATER",	"",
	"LEFT",	"",
	"LEFT PARA",	"",
	"LOWER ESOPHAGUS",	"",
	"MEDIAL",	"",
	"MID ESOPHAGUS",	"",
	"MIDLINE",	"",
	"OCCIPITAL",	"",
	"POSTERIOR",	"",
	"PROXIMAL",	"",
	"PULMONARY ART",	"",
	"R ATRIUM",	"",
	"R CORONARY ART",	"",
	"R LIQ",	"",
	"R LOQ",	"",
	"R PARASTERN",	"",
	"R SUBCLAVIAN",	"",
	"RSUPRACLAVICULAR",	"",
	"R UIQ",	"",
	"R UOQ",	"",
	"R VENTRICLE",	"",
	"RIGHT",	"",
	"RIGHT PARA",	"",
	"SUBCLAVIAN",	"",
	"SUBCOSTAL",	"",
	"SUP STERN NOTCH",	"",
	"SUPERIOR",	"",
	"SUPRACLAVICULAR",	"",
	"SURFACE",	"",
	"TRANSGASTRIC",	"",
	"TRANSORBITAL",	"",
	"TRANSTEMPORAL",	"",
	"UPPER ESOPHAGUS",	"",
	"VEIN",	"",
	0,0
};

char *
DC3StringValueDescription_USTransducerPosition(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USTransducerPosition,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USTransducerOrientation[] = {
	"2 CHAMBER",	"",
	"4 CHAMBER",	"",
	"5 CHAMBER",	"",
	"AXIAL",	"",
	"CORONAL",	"",
	"L PARASAG",	"",
	"LONG AXIS",	"",
	"LONGITUDINAL",	"",
	"OBLIQUE",	"",
	"R PARASAG",	"",
	"SAGITTAL",	"",
	"SHORT AXIS",	"",
	"TRANSVERSE",	"",
	0,0
};

char *
DC3StringValueDescription_USTransducerOrientation(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USTransducerOrientation,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USAnatomicStructure[] = {
	"4 CH HEART",	"",
	"3RD VENTRICLE",	"",
	"4TH VENTRICLE",	"",
	"AC",	"",
	"ADRENAL",	"",
	"AMNIOTIC FLUID",	"",
	"AORTA",	"",
	"APPENDIX",	"",
	"ASCENDING COLON",	"",
	"BASILAR ART",	"",
	"BILE DUCT",	"",
	"BLADDER",	"",
	"BPD",	"",
	"C SPINE",	"",
	"CELIAC ART",	"",
	"CENTRAL ZONE",	"",
	"CEREBELLUM",	"",
	"CEREB HEMISPHERE",	"",
	"CERVIX",	"",
	"COLON",	"",
	"CUL DE SAC",	"",
	"DESCENDING COLON",	"",
	"DUODENUM",	"",
	"ENDOMETRIUM",	"",
	"FETAL ARMS",	"",
	"FETAL DIGITS",	"",
	"FETAL HEART",	"",
	"FETAL LEGS",	"",
	"FETAL POLE",	"",
	"FEMUR LENGTH",	"",
	"FUNDUS",	"",
	"GALLBLADDER",	"",
	"GEST SAC",	"",
	"HC",	"",
	"HEPATIC ART",	"",
	"ILEUM",	"",
	"ISTHMUS",	"",
	"INF MES ART",	"",
	"INF VENA CAVA",	"",
	"L ACA",	"",
	"L AXILLARY A",	"",
	"L AXILLARY V",	"",
	"L BRACHIAL A",	"",
	"L BRACHIAL V",	"",
	"L BREAST",	"",
	"L BULB",	"",
	"L CCA",	"",
	"L CFA",	"",
	"L CFV",	"",
	"L CHOROID PLEXUS",	"",
	"L COM ILIAC ART",	"",
	"L COM ILIAC V",	"",
	"L ECA",	"",
	"L EPIDIDYMIS",	"",
	"L EXT ILIAC A",	"",
	"L EXT ILIAC V",	"",
	"L EXT JUG V",	"",
	"L EYE",	"",
	"L FEMUR",	"",
	"L GSV",	"",
	"L HEPATIC V",	"",
	"L HUMERUS",	"",
	"L ICA",	"",
	"L ILIAC A",	"",
	"L ILIAC V",	"",
	"L INT JUG V",	"",
	"L KIDNEY",	"",
	"L MCA",	"",
	"L OVARY",	"",
	"L PCA",	"",
	"L POP A",	"",
	"L POP V",	"",
	"L PROF FEM A",	"",
	"L PROF FEM V",	"",
	"L RADIAL A",	"",
	"L RADIUS",	"",
	"L RENAL ART",	"",
	"L RENAL V",	"",
	"L SEM VESICLE",	"",
	"L SAPH V",	"",
	"L SFA",	"",
	"L SFV",	"",
	"L SPINE",	"",
	"L SUBCLAVIAN A",	"",
	"L SUBCLAVIAN V",	"",
	"L TESTIS",	"",
	"L THALAMUS",	"",
	"L TIB FIB",	"",
	"L ULNA",	"",
	"L ULNAR ART",	"",
	"L VENTRICLE",	"",
	"L VERT",	"",
	"LAT VENTRICLES",	"",
	"LIVER",	"",
	"L PORTAL V",	"",
	"MID HEPATIC V",	"",
	"MORRISONS POUCH",	"",
	"OFD",	"",
	"PANCREAS",	"",
	"PENILE VESSELS",	"",
	"PERIPHERAL ZONE",	"",
	"PLACENTA",	"",
	"PORTAL V",	"",
	"PROSTATE",	"",
	"R ACA",	"",
	"R AXILLARY A",	"",
	"R AXILLARY V",	"",
	"R BRACHIAL A",	"",
	"R BRACHIAL V",	"",
	"R BREAST",	"",
	"R BULB",	"",
	"R CCA",	"",
	"R CFA",	"",
	"R CFV",	"",
	"R CHOROID PLEXUS",	"",
	"R COM ILIAC ART",	"",
	"R COM ILIAC V",	"",
	"R ECA",	"",
	"R EYE",	"",
	"R EPIDIDYMIS",	"",
	"R EXT ILIAC A",	"",
	"R EXT ILIAC V",	"",
	"R EXT JUV V",	"",
	"R FEMUR",	"",
	"R GSV",	"",
	"R HEPATIC V",	"",
	"R HUMERUS",	"",
	"R ICA",	"",
	"R ILIAC A",	"",
	"R ILIAC V",	"",
	"R INT JUG V",	"",
	"R KIDNEY",	"",
	"R MCA",	"",
	"R OVARY",	"",
	"R PCAR POP A",	"",
	"R POP V",	"",
	"R PROF FEM A",	"",
	"R PROF FEM V",	"",
	"R RADIAL A",	"",
	"R RADIUS",	"",
	"R RENAL ART",	"",
	"R RENAL V",	"",
	"R SAPH V",	"",
	"R SEM VESICLE",	"",
	"R SFA",	"",
	"R SFV",	"",
	"R SUBCLAVIAN A",	"",
	"R SUBCLAVIAN V",	"",
	"R TESTIS",	"",
	"R THALAMUS",	"",
	"R TIB FIB",	"",
	"R ULNA",	"",
	"R ULNAR ART",	"",
	"R VENTRICLE",	"",
	"R VERT",	"",
	"R PORTAL V",	"",
	"RECTUM",	"",
	"RETROPERITONEUM",	"",
	"SACRUM",	"",
	"SCROTUM",	"",
	"SIGMOID",	"",
	"SMA",	"",
	"SMALL INTESTINE",	"",
	"SMV",	"",
	"SPLEEN",	"",
	"SPLENIC ART",	"",
	"SPLENIC V",	"",
	"STOMACH",	"",
	"TESTICLE",	"",
	"T SPINE",	"",
	"THYROID",	"",
	"TRANSITION ZONE",	"",
	"TRANSVERSE COLON",	"",
	"SIGMOID",	"",
	"UMB CORD",	"",
	"UTERINE FUNDUS",	"",
	"UTERUS",	"",
	"VAGINA",	"",
	"YOLK SAC",	"",
	"ABD AO",	"",
	"AO ANNULUS",	"",
	"AO ARCH",	"",
	"AO LFLT TIPS",	"",
	"AO VALVE",	"",
	"ASCENDING AO",	"",
	"ASD",	"",
	"AZYGOS VEIN",	"",
	"CORONARY SINUS",	"",
	"DIAGONAL",	"",
	"DISTAL LAD",	"",
	"DISTAL LCX",	"",
	"DISTAL RCA",	"",
	"IAS",	"",
	"INNOMINATE A",	"",
	"INT ATRIAL SEPT",	"",
	"INT VENT SEPT",	"",
	"IVS",	"",
	"L ATRIAL APPEN",	"",
	"L ATRIUM",	"",
	"L FOOT",	"",
	"L GERMINAL MATRX",	"",
	"L HIP",	"",
	"L SHOULDER",	"",
	"L MAIN COR ART",	"",
	"L SAPH V",	"",
	"L SVC",	"",
	"LAD",	"",
	"LAD D1",	"",
	"LAD D2",	"",
	"LAD D3",	"",
	"LAD S1",	"",
	"LAD S2",	"",
	"LCX",	"",
	"LCXDM1",	"",
	"LCXDM2",	"",
	"LIMA",	"",
	"LLPV",	"",
	"LOWER DESC AO",	"",
	"LPA",	"",
	"LPV",	"",
	"LUPV",	"",
	"LV APEX",	"",
	"LV BASE",	"",
	"LV CAVITY",	"",
	"LV MID",	"",
	"LVOT",	"",
	"MAIN PA",	"",
	"MID LAD",	"",
	"MID LCX",	"",
	"MID RCA",	"",
	"MITRAL ANNULUS",	"",
	"MITRAL LFLT TIPS",	"",
	"MITRAL VALVE",	"",
	"OBTUSE MARGINAL",	"",
	"PERINEUM",	"",
	"PLV COR ART",	"",
	"POST DESC ART",	"",
	"POST LV BRANCH",	"",
	"PROX CIRC",	"",
	"PROX LAD",	"",
	"PROX LCX",	"",
	"PROX RCA",	"",
	"PULM ANNULUS",	"",
	"PULM VALVE",	"",
	"PULM VEIN",	"",
	"PV TIPS",	"",
	"R ATRIUM",	"",
	"R FOOT",	"",
	"R GERMINAL MATRX",	"",
	"R HIP",	"",
	"R PV",	"",
	"R SAPH V",	"",
	"R SHOULDER",	"",
	"RAA",	"",
	"RCA",	"",
	"RIMA",	"",
	"RLPV",	"",
	"RPA",	"",
	"RUPV",	"",
	"RV CAVITY",	"",
	"RVOT",	"",
	"SAPH V GRAFT LAD",	"",
	"SUP VENA CAVA",	"",
	"SVG D",	"",
	"SVG LAD",	"",
	"SVG LCX",	"",
	"SVG OM",	"",
	"SVG PDA",	"",
	"SVG PLV",	"",
	"SVG RCA",	"",
	"TRICUSPID ANN",	"",
	"TRICUSPID TIPS",	"",
	"TRICUSPID VALVE",	"",
	"UPPER DESC AO",	"",
	"VSD",	"",
	0,0
};

char *
DC3StringValueDescription_USAnatomicStructure(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USAnatomicStructure,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_USTransducerType[] = {
	"SECTOR",	"",
	"SECTOR",	"",
	"SECTOR",	"",
	"LINEAR",	"",
	"CURVED LINEAR",	"",
	"SINGLE CRYSTAL",	"",
	"SPLIT XTAL CWD",	"",
	"IV",	"",
	"IV",	"",
	"IV",	"",
	"ENDOCAV",	"",
	"ENDOCAV",	"",
	"ENDOCAV",	"",
	"ENDOCAV",	"",
	"ENDOCAV",	"",
	"VECTOR",	"",
	0,0
};

char *
DC3StringValueDescription_USTransducerType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_USTransducerType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ConversionType[] = {
	"DV",	"Digitized Video",
	"DI",	"Digital Interface",
	"DF",	"Digitized Film",
	"WSD",	"Workstation",
	0,0
};

char *
DC3StringValueDescription_ConversionType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ConversionType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_OverlayType[] = {
	"G",	"Graphics",
	"R",	"ROI",
	0,0
};

char *
DC3StringValueDescription_OverlayType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_OverlayType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CurveTypeOfData[] = {
	"TAC",	"Time Activity Curve",
	"PROF",	"Image Profile",
	"HIST",	"Histogram",
	"ROI",	"Polygraphic Region Of Interest",
	"TABL",	"Table of Values",
	"FILT",	"Filter Kernel",
	"POLY",	"Poly Line",
	"ECG",	"ECG Data",
	"PRESSURE",	"Pressure Data",
	"FLOW",	"Flow Data",
	"PHYSIO",	"Physiological Data",
	"RESP",	"Respiration Trace",
	0,0
};

char *
DC3StringValueDescription_CurveTypeOfData(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CurveTypeOfData,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_CurveAxisUnits[] = {
	"SEC",	"Seconds",
	"CNTS",	"Counts",
	"MM",	"millimeters",
	"PIXL",	"Pixels",
	"NONE",	"Unitless",
	"BPM",	"beats/min",
	"CM",	"centimeters",
	"CMS",	"centimeters/second",
	"CM2",	"cm**2",
	"CMS2",	"cm**2/second",
	"CM3",	"cm**3",
	"CM3S",	"cm**3/second",
	"CMS2",	"cm/second**2",
	"DB",	"dB",
	"DBS",	"dB/second",
	"DEG",	"degrees",
	"GM",	"gram",
	"GMM2",	"gram/meter**2",
	"HZ",	"Hertz",
	"IN",	"inch",
	"KG",	"kg",
	"LMIN",	"liters/minute",
	"LMINM2",	"liters/minute/meter**2",
	"M2",	"meters **2",
	"MS2",	"meters/sec**2",
	"MLM2",	"milliliters/meter**2",
	"MILS",	"milliseconds",
	"MILV",	"millivolts",
	"MMHG",	"mmHg",
	"PCNT",	"percent",
	"LB",	"pound",
	0,0
};

char *
DC3StringValueDescription_CurveAxisUnits(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_CurveAxisUnits,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ModalityLUTType[] = {
	"OD",	"Optical Density (thousandths)",
	"US",	"Unspecified",
	0,0
};

char *
DC3StringValueDescription_ModalityLUTType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ModalityLUTType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_SpecificCharacterSet[] = {
	"ISO",	"Latin alphabet No. 1 supplementary set",
	"ISO",	"Latin alphabet No. 2 supplementary set",
	"ISO",	"Latin alphabet No. 3 supplementary set",
	"ISO",	"Latin alphabet No. 4 supplementary set",
	"ISO",	"Cyrillic supplementary set",
	"ISO",	"Arabic supplementary set",
	"ISO",	"Greek supplementary set",
	"ISO",	"Hebrew supplementary set",
	"ISO",	"Latin alphabet No. 5 supplementary set",
	0,0
};

char *
DC3StringValueDescription_SpecificCharacterSet(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_SpecificCharacterSet,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_MediumType[] = {
	"PAPER",	"",
	"CLEAR FILM",	"",
	"BLUE FILM",	"",
	0,0
};

char *
DC3StringValueDescription_MediumType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_MediumType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_FilmDestination[] = {
	"MAGAZINE",	"",
	"PROCESSOR",	"",
	0,0
};

char *
DC3StringValueDescription_FilmDestination(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_FilmDestination,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_ImageDisplayFormat[] = {
	"SLIDE",	"",
	"SUPERSLIDE",	"",
	0,0
};

char *
DC3StringValueDescription_ImageDisplayFormat(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_ImageDisplayFormat,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_FilmSizeID[] = {
	"8INX10IN",	"",
	"10INX12IN",	"",
	"10INX14IN",	"",
	"11INX14IN",	"",
	"14INX14IN",	"",
	"14INX17IN",	"",
	"24CMX24CM",	"",
	"24CMX30CM",	"",
	0,0
};

char *
DC3StringValueDescription_FilmSizeID(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_FilmSizeID,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_MagnificationType[] = {
	"REPLICATE",	"",
	"BILINEAR",	"",
	"CUBIC",	"",
	"NONE",	"",
	0,0
};

char *
DC3StringValueDescription_MagnificationType(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_MagnificationType,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Density[] = {
	"BLACK",	"",
	"WHITE",	"",
	0,0
};

char *
DC3StringValueDescription_Density(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Density,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_Polarity[] = {
	"NORMAL",	"",
	"REVERSE",	"",
	0,0
};

char *
DC3StringValueDescription_Polarity(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_Polarity,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PrintExecutionStatus[] = {
	"PENDING",	"",
	"PRINTING",	"",
	"DONE",	"",
	"FAILURE",	"",
	0,0
};

char *
DC3StringValueDescription_PrintExecutionStatus(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PrintExecutionStatus,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PrintExecutionStatusInfo[] = {
	"QUEUED",	"",
	"NO SUPPLY MGZ",	"",
	"NO RECEIVE MGZ",	"",
	"SUPPLY EMPTY",	"",
	"RECEIVER FULL",	"",
	"FILM JAM",	"",
	0,0
};

char *
DC3StringValueDescription_PrintExecutionStatusInfo(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PrintExecutionStatusInfo,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PrinterStatus[] = {
	"NORMAL",	"",
	"WARNING",	"",
	"FAILURE",	"",
	0,0
};

char *
DC3StringValueDescription_PrinterStatus(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PrinterStatus,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_PrinterStatusInfo[] = {
	"SUPPLY EMPTY",	"",
	"SUPPLY LOW",	"",
	"RECEIVER FULL",	"",
	"FILM JAM",	"",
	0,0
};

char *
DC3StringValueDescription_PrinterStatusInfo(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_PrinterStatusInfo,value);
}

static struct DC3StringValueEntry
DC3StringValueTable_OverlayMode[] = {
	"REPLACE",	"",
	"THRESHHOLDREPLACE",	"",
	"COMPLEMENT",	"",
	0,0
};

char *
DC3StringValueDescription_OverlayMode(char * value)
{
	return DC3StringValueDescription(DC3StringValueTable_OverlayMode,value);
}






/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
