/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */




// Automatically generated from template - EDITS WILL BE LOST

// Generated by strval.awk with options header

#ifndef _DC3tstrval_HEADER_
#define _DC3tstrval_HEADER_

char *	DC3StringValueDescription_YesNoLetter(char * value);
char *	DC3StringValueDescription_YesNoFull(char * value);
char *	DC3StringValueDescription_Priority(char * value);
char *	DC3StringValueDescription_SmokingStatus(char * value);
char *	DC3StringValueDescription_Orientation(char * value);
char *	DC3StringValueDescription_DiagnosticCodingSchemes(char * value);
char *	DC3StringValueDescription_ProcedureCodeScheme(char * value);
char *	DC3StringValueDescription_VisitStatusID(char * value);
char *	DC3StringValueDescription_StudyStatusID(char * value);
char *	DC3StringValueDescription_StudyComponentStatusID(char * value);
char *	DC3StringValueDescription_InterpretationTypeID(char * value);
char *	DC3StringValueDescription_InterpretationStatusID(char * value);
char *	DC3StringValueDescription_Sex(char * value);
char *	DC3StringValueDescription_Laterality(char * value);
char *	DC3StringValueDescription_BodyPartExamined(char * value);
char *	DC3StringValueDescription_Modality(char * value);
char *	DC3StringValueDescription_PatientPosition(char * value);
char *	DC3StringValueDescription_ViewPosition(char * value);
char *	DC3StringValueDescription_CassetteSize(char * value);
char *	DC3StringValueDescription_RotationDirection(char * value);
char *	DC3StringValueDescription_ScanningSequence(char * value);
char *	DC3StringValueDescription_SequenceVariant(char * value);
char *	DC3StringValueDescription_ScanOptions(char * value);
char *	DC3StringValueDescription_MRAcquisitionType(char * value);
char *	DC3StringValueDescription_AngioFlag(char * value);
char *	DC3StringValueDescription_PhaseEncodingDirection(char * value);
char *	DC3StringValueDescription_NuclearMedicineSeriesType(char * value);
char *	DC3StringValueDescription_WholeBodyTechnique(char * value);
char *	DC3StringValueDescription_FieldOfViewShape(char * value);
char *	DC3StringValueDescription_CollimatorType(char * value);
char *	DC3StringValueDescription_AcquisitionTerminationCondition(char * value);
char *	DC3StringValueDescription_CorrectedImage(char * value);
char *	DC3StringValueDescription_PhotometricInterpretation(char * value);
char *	DC3StringValueDescription_PhotometricInterpretationMonochrome(char * value);
char *	DC3StringValueDescription_PhotometricInterpretationRGB(char * value);
char *	DC3StringValueDescription_USPhotometricInterpretation(char * value);
char *	DC3StringValueDescription_ImageType1(char * value);
char *	DC3StringValueDescription_ImageType2(char * value);
char *	DC3StringValueDescription_CTImageType3(char * value);
char *	DC3StringValueDescription_MRImageType3(char * value);
char *	DC3StringValueDescription_USImageType3(char * value);
char *	DC3StringValueDescription_USTransducerPosition(char * value);
char *	DC3StringValueDescription_USTransducerOrientation(char * value);
char *	DC3StringValueDescription_USAnatomicStructure(char * value);
char *	DC3StringValueDescription_USTransducerType(char * value);
char *	DC3StringValueDescription_ConversionType(char * value);
char *	DC3StringValueDescription_OverlayType(char * value);
char *	DC3StringValueDescription_CurveTypeOfData(char * value);
char *	DC3StringValueDescription_CurveAxisUnits(char * value);
char *	DC3StringValueDescription_ModalityLUTType(char * value);
char *	DC3StringValueDescription_SpecificCharacterSet(char * value);
char *	DC3StringValueDescription_MediumType(char * value);
char *	DC3StringValueDescription_FilmDestination(char * value);
char *	DC3StringValueDescription_ImageDisplayFormat(char * value);
char *	DC3StringValueDescription_FilmSizeID(char * value);
char *	DC3StringValueDescription_MagnificationType(char * value);
char *	DC3StringValueDescription_Density(char * value);
char *	DC3StringValueDescription_Polarity(char * value);
char *	DC3StringValueDescription_PrintExecutionStatus(char * value);
char *	DC3StringValueDescription_PrintExecutionStatusInfo(char * value);
char *	DC3StringValueDescription_PrinterStatus(char * value);
char *	DC3StringValueDescription_PrinterStatusInfo(char * value);
char *	DC3StringValueDescription_OverlayMode(char * value);

#endif /* _DC3tstrval_HEADER_ */





/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
  ! Copyright (C) 1998 Dtack Inc. All Rights Reserved
  ! To use this file, you must have signed a license agreement with Dtack Inc.
  ! Under no circumstances may you redistribute this file.
  ! This software is provided AS IS with no warranty expressed or implied.
  ! Dtack Inc. accepts no liability for use or misuse of this file.
  ! http://www.dtack.com  dtack@dtack.com  telephone +360.417.6700
  ! Dtack Inc, P.O. Box 3061, Port Angeles, WA USA 98362
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
